import FormalProofs.Econometrics.Overidentification

/-!
# FormalProofs/Econometrics/Overidentification/CoverageChecklist

Build-time checklist for the numbered claims tracked in
`lean3/docs/OVERIDENTIFICATION_REGULAR_MODELS_MAP.md`.

If any exported name below disappears, this module fails to elaborate.
-/

#check Econometrics.OveridentificationRegularModels.DQMPath
#check Econometrics.OveridentificationRegularModels.CenteredScoreSpace
#check Econometrics.OveridentificationRegularModels.squareRootDensity
#check Econometrics.OveridentificationRegularModels.localAlternativeScale
#check Econometrics.OveridentificationRegularModels.baseSampleMeasure
#check Econometrics.OveridentificationRegularModels.sampleMeasure
#check Econometrics.OveridentificationRegularModels.sampleLogLikelihoodRatio
#check Econometrics.OveridentificationRegularModels.normalizedScoreSum
#check Econometrics.OveridentificationRegularModels.ProductLogLikelihoodRatioWitness
#check Econometrics.OveridentificationRegularModels.ProductLANWitness
#check Econometrics.OveridentificationRegularModels.ExponentialTiltPath
#check Econometrics.OveridentificationRegularModels.exponentialTiltSampleLogLikelihoodRatio
#check Econometrics.OveridentificationRegularModels.FiniteProbeFamily
#check Econometrics.OveridentificationRegularModels.FiniteProbeCLT
#check Econometrics.OveridentificationRegularModels.CramerWoldWitness
#check Econometrics.OveridentificationRegularModels.FiniteProbeThirdLemmaWitness
#check Econometrics.OveridentificationRegularModels.pathwiseTangentSpace
#check Econometrics.OveridentificationRegularModels.HasFirstOrderLocalExperimentExpansion
#check Econometrics.OveridentificationRegularModels.LocallyContiguous
#check Econometrics.OveridentificationRegularModels.ConcreteGaussianShiftExperiment
#check Econometrics.OveridentificationRegularModels.IsPathwiseLocallyJustIdentified
#check Econometrics.OveridentificationRegularModels.IsPathwiseLocallyOveridentified
#check Econometrics.OveridentificationRegularModels.IsLocallyJustIdentified
#check Econometrics.OveridentificationRegularModels.IsLocallyOveridentified

#check Econometrics.OveridentificationRegularModels.dqmPathScore_mem_pathwiseTangentSpace
#check Econometrics.OveridentificationRegularModels.localLogLikelihoodRatio_vanishesAtBase
#check Econometrics.OveridentificationRegularModels.pathwiseTangentSpace_mono
#check Econometrics.OveridentificationRegularModels.pathwiseTangentSpace_union_eq_closedSup
#check Econometrics.OveridentificationRegularModels.pathwiseLocalJustIdentification_iff_generatedTangent_eq_top
#check Econometrics.OveridentificationRegularModels.pathwiseGeneratedScores_dense_iff_tangent_eq_top
#check Econometrics.OveridentificationRegularModels.dqmFirstOrderLocalExperimentExpansion_of_tendsto
#check Econometrics.OveridentificationRegularModels.dqmLocalAlternatives_contiguous
#check Econometrics.OveridentificationRegularModels.sampleLogLikelihoodRatio_vanishesAtBase
#check Econometrics.OveridentificationRegularModels.sampleLogLikelihoodRatio_ae_eq_true_of_witness
#check Econometrics.OveridentificationRegularModels.productLAN_ae_eq_quadratic_plus_remainder
#check Econometrics.OveridentificationRegularModels.scalarCLT_to_finiteProbe_dim1
#check Econometrics.OveridentificationRegularModels.finiteProbeCLT_dim1_iff_scalar
#check Econometrics.OveridentificationRegularModels.finiteProbeDrift_eq_zero_of_orthogonal
#check Econometrics.OveridentificationRegularModels.thirdLemma_shiftedMean_eq_finiteProbeDrift
#check Econometrics.OveridentificationRegularModels.exponentialTilt_localLogLikelihoodRatio_eq
#check Econometrics.OveridentificationRegularModels.exponentialTilt_sampleLogLikelihoodRatio_eq
#check Econometrics.OveridentificationRegularModels.exponentialTilt_localAlternativeExpansion
#check Econometrics.OveridentificationRegularModels.dominatedDqmFamily_gaussianShiftExperiment
#check Econometrics.OveridentificationRegularModels.dqmGaussianShift_orthogonalCoordinates_eq_zero
#check Econometrics.OveridentificationRegularModels.dqmGaussianShift_coordinateDecomposition
#check Econometrics.OveridentificationRegularModels.dqmGaussianShift_scalarizedConvolution

#check Econometrics.OveridentificationRegularModels.localJustIdentification_iff_trivialOrthogonalComplement
#check Econometrics.OveridentificationRegularModels.localOveridentification_iff_nontrivialOrthogonalComplement
#check Econometrics.OveridentificationRegularModels.localOveridentification_iff_exists_nonzeroOrthogonalScore
#check Econometrics.OveridentificationRegularModels.pathwiseLocalJustIdentification_iff_trivialOrthogonalComplement
#check Econometrics.OveridentificationRegularModels.pathwiseLocalOveridentification_iff_exists_nonzeroOrthogonalScore

#check Econometrics.OveridentificationRegularModels.regularEstimators_firstOrderEquivalent
#check Econometrics.OveridentificationRegularModels.pathwiseRegularEstimators_firstOrderEquivalent
#check Econometrics.OveridentificationRegularModels.regularEstimatorDifference_isOrthogonal
#check Econometrics.OveridentificationRegularModels.distinctRegularEstimators_exist_underOveridentification
#check Econometrics.OveridentificationRegularModels.varianceDecomposition
#check Econometrics.OveridentificationRegularModels.varianceEquality_onDenseSet_iff_localJustIdentification
#check Econometrics.OveridentificationRegularModels.maintainedModelScoreDecomposition
#check Econometrics.OveridentificationRegularModels.fullScoreDecomposition
#check Econometrics.OveridentificationRegularModels.incrementalSarganOrthogonalCharacterization

#check Econometrics.OveridentificationRegularModels.gaussianShift_coordinateDecomposition
#check Econometrics.OveridentificationRegularModels.gaussianShift_scalarizedConvolution

#check Econometrics.OveridentificationRegularModels.coneLocalJustIdentification_iff_trivialInnerDual
#check Econometrics.OveridentificationRegularModels.coneLocalOveridentification_iff_nontrivialInnerDual
#check Econometrics.OveridentificationRegularModels.coneLocalOveridentification_iff_exists_nonzeroInnerDual
#check Econometrics.OveridentificationRegularModels.noNontrivialInnerDual_underLocalJustIdentification

#check Econometrics.OveridentificationRegularModels.LinearGMMModel
#check Econometrics.OveridentificationRegularModels.LinearGMMDQMAssociatedFamily
#check Econometrics.OveridentificationRegularModels.gmmResidualMaker
#check Econometrics.OveridentificationRegularModels.gmmOrthogonalRestrictionSpace
#check Econometrics.OveridentificationRegularModels.gmmLocalJustIdentification_iff_residualMaker_zero
#check Econometrics.OveridentificationRegularModels.gmmLocalOveridentification_iff_exists_nonzeroRestriction
#check Econometrics.OveridentificationRegularModels.gmmIncrementalSargan_expansion
#check Econometrics.OveridentificationRegularModels.gmmJustIdentified_killsOrthogonalComplement
#check Econometrics.OveridentificationRegularModels.gmmOveridentified_yieldsNontrivialJDirection
#check Econometrics.OveridentificationRegularModels.gmmLocalMomentDrift
#check Econometrics.OveridentificationRegularModels.gmmHansenJLocalDrift
#check Econometrics.OveridentificationRegularModels.gmmHausmanLocalDrift
#check Econometrics.OveridentificationRegularModels.gmmIncrementalSarganLocalDrift
#check Econometrics.OveridentificationRegularModels.gmmOveridentified_yieldsPositiveHansenJDrift
#check Econometrics.OveridentificationRegularModels.gmmOveridentified_yieldsPositiveIncrementalSarganDrift
#check Econometrics.OveridentificationRegularModels.gmmPathwiseLocalJustIdentification_iff
#check Econometrics.OveridentificationRegularModels.gmmPathwiseLocalOveridentification_iff
#check Econometrics.OveridentificationRegularModels.gmmPathwiseOveridentified_yieldsPositiveHansenJDrift
#check Econometrics.OveridentificationRegularModels.gmmPathwiseOveridentified_yieldsPositiveIncrementalSarganDrift

#check Econometrics.OveridentificationRegularModels.LinearizedConditionalMomentModel
#check Econometrics.OveridentificationRegularModels.ConditionalMomentDQMAssociatedFamily
#check Econometrics.OveridentificationRegularModels.conditionalMomentOrthogonalScoreSpace_eq_bot_iff_denseRange
#check Econometrics.OveridentificationRegularModels.conditionalMomentDenseRange_iff_trivialAdjointKernel
#check Econometrics.OveridentificationRegularModels.conditionalMomentFullEfficiency_onDenseSet_iff_denseRange
#check Econometrics.OveridentificationRegularModels.conditionalMomentLocalOveridentification_iff_exists_nonzeroScore
#check Econometrics.OveridentificationRegularModels.conditionalMomentOrthogonalScoreLocalDrift
#check Econometrics.OveridentificationRegularModels.conditionalMomentPathwiseLocalJustIdentification_iff
#check Econometrics.OveridentificationRegularModels.conditionalMomentPathwiseLocalOveridentification_iff
#check Econometrics.OveridentificationRegularModels.conditionalMomentPathwiseOveridentified_yieldsPositiveScoreDrift

#check Econometrics.OveridentificationRegularModels.conditionalMeanExample_locallyJustIdentified
#check Econometrics.OveridentificationRegularModels.conditionalMeanExample_pathwiseLocallyJustIdentified
#check Econometrics.OveridentificationRegularModels.conditionalMeanAssociatedFamily
#check Econometrics.OveridentificationRegularModels.conditionalMeanExample_pathwiseLocallyJustIdentified_of_tangent_eq_top
#check Econometrics.OveridentificationRegularModels.quantileExample_locallyJustIdentified
#check Econometrics.OveridentificationRegularModels.quantileExample_pathwiseLocallyJustIdentified
#check Econometrics.OveridentificationRegularModels.quantileAssociatedFamily
#check Econometrics.OveridentificationRegularModels.quantileExample_pathwiseLocallyJustIdentified_of_tangent_eq_top
#check Econometrics.OveridentificationRegularModels.partiallyLinearExample_locallyOveridentified
#check Econometrics.OveridentificationRegularModels.partiallyLinearExample_pathwiseLocallyOveridentified
