/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 63fd80bb-f3fc-48a8-b303-0763c849e171

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of Summarizer, Eg (Expectation), and D (Distortion).
-/
def Summarizer (α : Type*) := α → PMF α

noncomputable def Eg {α : Type*} (g : Summarizer α) (f : α → ℝ) (x : α) : ℝ :=
  ∑' z, (g x z).toReal * f z

variable {Y : Type*} [PseudoMetricSpace Y]

def D {α : Type*} (fstar : α → Y) (z x : α) : ℝ :=
  dist (fstar z) (fstar x)

/-
Definitions of BinTree, Realized String (S), Hierarchical Reduction (reduce), Multi-Round Reduction (ZR), and Tree Accessors.
-/
inductive BinTree (α : Type*) : Type _
| leaf : α → BinTree α
| node : BinTree α → BinTree α → BinTree α

variable {Strings : Type*} [Monoid Strings]

def S : BinTree Strings → Strings
| BinTree.leaf b => b
| BinTree.node T_L T_R => S T_L * S T_R

variable (g : Summarizer Strings)

def reduce : BinTree Strings → PMF Strings
| BinTree.leaf b => g b
| BinTree.node T_L T_R => (reduce T_L).bind (fun s_L => (reduce T_R).bind (fun s_R => g (s_L * s_R)))

def ZR (x : Strings) (R : ℕ) (T : BinTree Strings) : PMF Strings :=
  match R with
  | 0 => PMF.pure x -- Should not happen based on 1-indexing in paper, but need base case
  | 1 => reduce g T
  | n + 1 => (ZR x n T).bind g

def root {α : Type*} (T : BinTree α) : BinTree α := T

def leaves {α : Type*} : BinTree α → List α
| BinTree.leaf b => [b]
| BinTree.node T_L T_R => leaves T_L ++ leaves T_R

def internal_nodes {α : Type*} : BinTree α → List (BinTree α × BinTree α)
| BinTree.leaf _ => []
| BinTree.node T_L T_R => (T_L, T_R) :: (internal_nodes T_L ++ internal_nodes T_R)

/-- Count leaves in a binary tree -/
def numLeaves {α : Type*} : BinTree α → ℕ
| BinTree.leaf _ => 1
| BinTree.node T_L T_R => numLeaves T_L + numLeaves T_R

/-- Count internal nodes in a binary tree -/
def numInternalNodes {α : Type*} : BinTree α → ℕ
| BinTree.leaf _ => 0
| BinTree.node T_L T_R => 1 + numInternalNodes T_L + numInternalNodes T_R

/-- List length equals count for leaves -/
lemma leaves_length_eq {α : Type*} (T : BinTree α) : (leaves T).length = numLeaves T := by
  induction T with
  | leaf b => simp [leaves, numLeaves]
  | node T_L T_R ih_L ih_R => simp [leaves, numLeaves, ih_L, ih_R]

/-- List length equals count for internal nodes -/
lemma internal_nodes_length_eq {α : Type*} (T : BinTree α) :
    (internal_nodes T).length = numInternalNodes T := by
  induction T with
  | leaf b => simp [internal_nodes, numInternalNodes]
  | node T_L T_R ih_L ih_R =>
    simp only [internal_nodes, List.length_cons, List.length_append, ih_L, ih_R, numInternalNodes]
    ring

/-- A binary tree always has at least one leaf -/
lemma numLeaves_pos {α : Type*} (T : BinTree α) : 0 < numLeaves T := by
  induction T with
  | leaf _ => simp [numLeaves]
  | node T_L T_R ih_L _ => simp [numLeaves]; omega

/-- Standard binary tree property: internal nodes = leaves - 1 -/
lemma internal_eq_leaves_minus_one {α : Type*} (T : BinTree α) :
    numInternalNodes T = numLeaves T - 1 := by
  induction T with
  | leaf b => simp [numLeaves, numInternalNodes]
  | node T_L T_R ih_L ih_R =>
    simp only [numLeaves, numInternalNodes]
    have h1 : 0 < numLeaves T_L := numLeaves_pos T_L
    have h2 : 0 < numLeaves T_R := numLeaves_pos T_R
    omega

/-
Definitions of Egu (Tree Expectation), subtrees, and Local Laws L1, L2, L3.
-/
variable {Strings : Type*} [Monoid Strings]
variable {Y : Type*} [PseudoMetricSpace Y]

def Egu (g : Summarizer Strings) (T : BinTree Strings) (f : Strings → ℝ) : ℝ :=
  ∑' z, (reduce g T z).toReal * f z

def subtrees {α : Type*} : BinTree α → List (BinTree α)
| BinTree.leaf b => [BinTree.leaf b]
| BinTree.node T_L T_R => BinTree.node T_L T_R :: (subtrees T_L ++ subtrees T_R)

def L1 (g : Summarizer Strings) (T : BinTree Strings) (fstar : Strings → Y) : Prop :=
  ∀ b, b ∈ leaves T → Eg g (fun z => D fstar z b) b = 0

def L2 (g : Summarizer Strings) (T : BinTree Strings) (fstar : Strings → Y) : Prop :=
  ∀ p, p ∈ internal_nodes T →
    let (T_L, T_R) := p
    Egu g (BinTree.node T_L T_R) (fun z => D fstar z (S (BinTree.node T_L T_R))) = 0

def InRange (g : Summarizer Strings) (z : Strings) : Prop := ∃ x, z ∈ (g x).support

def L3 (g : Summarizer Strings) (fstar : Strings → Y) : Prop :=
  ∀ Z, InRange g Z → Eg g (fun z => D fstar z Z) Z = 0

/-
Nodewise Preservation: If L1 and L2 hold for T, then for any subtree u of T, the expected distortion is 0.
-/
theorem nodewise_preservation (g : Summarizer Strings) (T : BinTree Strings) (u : BinTree Strings) (fstar : Strings → Y)
  (h_sub : u ∈ subtrees T) (h1 : L1 g T fstar) (h2 : L2 g T fstar) :
  Egu g u (fun z => D fstar z (S u)) = 0 := by
    revert h_sub h1 h2;
    rintro hu h1 h2;
    induction' T with T_L T_R hT_L hT_R generalizing u;
    · cases hu;
      · convert h1 T_L ?_;
        simp only [leaves, List.mem_singleton];
      · contradiction;
    · -- Since $u$ is in the subtrees of $T_R.node hT_L$, it must be either in the subtrees of $T_R$ or in the subtrees of $hT_L$.
      by_cases hu_T_R : u ∈ subtrees T_R;
      · apply hT_R u hu_T_R;
        · intro b hb;
          apply h1 b;
          exact List.mem_append_left _ hb;
        · intro p hp;
          apply h2;
          exact List.mem_cons_of_mem _ ( List.mem_append_left _ hp );
      · by_cases hu_hT_L : u ∈ subtrees hT_L;
        · rename_i ih;
          apply ih u hu_hT_L;
          · intro b hb;
            exact h1 b ( by
              exact List.mem_append_right _ hb );
          · intro p hp;
            apply h2;
            -- Since $p$ is in the internal nodes of $hT_L$, it must be in the internal nodes of $T_R.node hT_L$ as well.
            simp [internal_nodes] at hp ⊢;
            exact Or.inr <| Or.inr hp;
        · cases hu;
          · exact h2 ( T_R, hT_L ) ( by simp +decide [ internal_nodes ] );
          · cases List.mem_append.mp ‹_› <;> tauto

/-
One-Pass Preservation: If L1 and L2 hold, then the expected distortion of the reduction of the root is 0.
-/
theorem one_pass (g : Summarizer Strings) (T : BinTree Strings) (x : Strings) (fstar : Strings → Y)
  (hp : S T = x) (h1 : L1 g T fstar) (h2 : L2 g T fstar) :
  Egu g (root T) (fun z => D fstar z x) = 0 := by
    have h_root : root T ∈ subtrees T := by
      cases T <;> tauto;
    have := nodewise_preservation g T ( root T ) fstar h_root h1 h2; aesop;

/-
Schedule Invariance: If two trees have the same leaves, and L1/L2 hold for both, then their expected distortions are equal (both 0).
-/
theorem schedule_invariance (g : Summarizer Strings) (T T' : BinTree Strings) (fstar : Strings → Y)
  (h_l : leaves T = leaves T') (h1 : L1 g T fstar) (h2 : L2 g T fstar) (h1' : L1 g T' fstar) (h2' : L2 g T' fstar) :
  Egu g (root T) (fun z => D fstar z (S T)) = Egu g (root T') (fun z => D fstar z (S T')) := by
    -- By definition of expected distortion, we know that if the leaves of two trees are the same, then their expected distortions are equal.
    have h_eq_dist : Egu g (root T) (fun z => D fstar z (S T)) = 0 ∧ Egu g (root T') (fun z => D fstar z (S T')) = 0 := by
      exact ⟨ one_pass g T ( S T ) fstar rfl h1 h2, one_pass g T' ( S T' ) fstar rfl h1' h2' ⟩;
    rw [ h_eq_dist.1, h_eq_dist.2 ]

/-
Fold-of-Folds Invariance: If L1, L2, and L3 hold, then the expected distortion is 0.
-/
theorem fold_of_folds (g : Summarizer Strings) (T_comp : BinTree Strings) (x : Strings) (fstar : Strings → Y)
  (hp : S T_comp = x) (h1 : L1 g T_comp fstar) (h2 : L2 g T_comp fstar) (_h3 : L3 g fstar) :
  Egu g (root T_comp) (fun z => D fstar z x) = 0 := by
    exact one_pass g T_comp x fstar hp h1 h2

/-
Any string in the support of reduce g T is in the range of g.
-/
theorem reduce_support_in_range (g : Summarizer Strings) (T : BinTree Strings) :
  ∀ z ∈ (reduce g T).support, InRange g z := by
    intro z hz;
    induction' T with T_L T_R ih_L ih_R;
    · exact ⟨ T_L, hz ⟩;
    · unfold reduce at hz;
      contrapose! hz; simp_all +decide [ PMF.support ] ;
      intro x hx y hy; unfold InRange at hz; aesop;

/-
For R >= 1, any string in the support of ZR is in the range of g.
-/
theorem ZR_support_in_range (g : Summarizer Strings) (x : Strings) (R : ℕ) (T : BinTree Strings) (hR : R ≥ 1) :
  ∀ z ∈ (ZR g x R T).support, InRange g z := by
    induction' hR with R hR ih generalizing x T;
    · simp only [ZR]; exact reduce_support_in_range g T;
    · intro z hz;
      -- By definition of bind, there exists some y in (ZR g x R T).support such that z is in the support of g y.
      obtain ⟨y, hy⟩ : ∃ y ∈ (ZR g x R T).support, z ∈ (g y).support := by
        have h_bind : (ZR g x (Nat.succ R) T) = (ZR g x R T).bind g := by
          cases R <;> tauto;
        contrapose! hz; aesop;
      exact ⟨ y, hy.2 ⟩

/-
Definition of Expectation over a PMF.
-/
def Exp {α : Type*} (p : PMF α) (f : α → ℝ) : ℝ := ∑' z, (p z).toReal * f z

/-
Helper lemma: The expected distortion added by one more round of summarization is 0, because the input to the new round is in the range of g (by previous rounds) and L3 ensures idempotence on the range.
-/
lemma multi_round_step (g : Summarizer Strings) (x : Strings) (R : ℕ) (T : BinTree Strings) (fstar : Strings → Y)
  (h3 : L3 g fstar) (h_supp : ∀ z ∈ (ZR g x R T).support, InRange g z) :
  Exp (ZR g x R T) (fun z => Eg g (fun w => D fstar w z) z) = 0 := by
    unfold Exp;
    convert tsum_zero with z;
    by_cases hz : z ∈ ( ZR g x R T ).support <;> aesop

/-
Definition of ExpENN (Expectation in ENNReal) and Law of Iterated Expectation for ExpENN.
-/
def ExpENN {α : Type*} (p : PMF α) (f : α → ENNReal) : ENNReal := ∑' z, p z * f z

lemma ExpENN_bind {α : Type*} (p : PMF α) (g : α → PMF α) (f : α → ENNReal) :
  ExpENN (p.bind g) f = ExpENN p (fun x => ExpENN (g x) f) := by
    unfold ExpENN;
    simp +decide [ PMF.bind_apply, mul_assoc, mul_comm, mul_left_comm, ← ENNReal.tsum_mul_left ];
    rw [ ← ENNReal.tsum_comm ]

/-
Relating Exp (Real) and ExpENN (ENNReal) for non-negative functions.
-/
lemma Exp_eq_ExpENN_toReal {α : Type*} (p : PMF α) (f : α → ℝ) (hf : ∀ x, 0 ≤ f x) :
  Exp p f = (ExpENN p (fun x => ENNReal.ofReal (f x))).toReal := by
    unfold Exp ExpENN;
    rw [ ENNReal.tsum_toReal_eq ];
    · rw [ tsum_congr ] ; intros ; rw [ ENNReal.toReal_mul ] ; aesop;
    · exact fun x => ENNReal.mul_ne_top ( p.apply_ne_top x ) ( ENNReal.ofReal_ne_top )

/-
If a summable series of non-negative real numbers sums to 0, then each term is 0.
-/
lemma tsum_eq_zero_of_nonneg {α : Type*} (f : α → ℝ) (hf : ∀ x, 0 ≤ f x) (h_summable : Summable f) (h_sum : ∑' x, f x = 0) :
  ∀ x, f x = 0 := by
    contrapose! h_sum;
    exact ne_of_gt ( lt_of_lt_of_le ( lt_of_le_of_ne ( hf _ ) ( Ne.symm h_sum.choose_spec ) ) ( Summable.le_tsum h_summable _ fun x _ => hf x ) )

/-
If L3 holds and the expected distortion is summable, then distortion is 0 on the support.
-/
lemma L3_implies_dist_zero_on_support (g : Summarizer Strings) (fstar : Strings → Y) (h3 : L3 g fstar) (Z : Strings) (hZ : InRange g Z)
  (h_summable : Summable (fun z => (g Z z).toReal * D fstar z Z)) :
  ∀ z ∈ (g Z).support, D fstar z Z = 0 := by
    -- By definition of $L3$, we know that $\sum_{z} (g Z z).toReal * D fstar z Z = 0$.
    have h_sum_zero : ∑' z, (g Z z).toReal * D fstar z Z = 0 := by
      exact h3 Z hZ;
    intro z hz; contrapose! h_sum_zero; simp_all +decide [ dist_eq_zero ] ;
    refine' ne_of_gt ( lt_of_lt_of_le _ ( Summable.le_tsum _ z _ ) );
    · exact mul_pos ( ENNReal.toReal_pos hz ( by
        exact PMF.apply_ne_top (g Z) z ) ) ( lt_of_le_of_ne ( dist_nonneg ) ( Ne.symm h_sum_zero ) );
    · exact h_summable;
    · exact fun _ _ => mul_nonneg ( ENNReal.toReal_nonneg ) ( dist_nonneg )

/-
If L3 holds, then each term in the expected distortion sum is zero.
-/
lemma L3_implies_term_zero (g : Summarizer Strings) (fstar : Strings → Y) (h3 : L3 g fstar) (Z : Strings) (hZ : InRange g Z)
  (h_summable : Summable (fun z => (g Z z).toReal * D fstar z Z)) :
  ∀ z, (g Z z).toReal * D fstar z Z = 0 := by
    -- Since (g Z z).toReal is zero when z is not in the support of g Z, the product is zero.
    intros z
    by_cases hz : z ∈ (g Z).support
    · exact (by
      have h_dist_zero : D fstar z Z = 0 := by
        apply L3_implies_dist_zero_on_support g fstar h3 Z hZ h_summable z hz;
      rw [ h_dist_zero, MulZeroClass.mul_zero ])
    · exact (by
      aesop)

/-
If L3 holds and expected distortion is summable, then ExpENN of distortion is 0.
-/
lemma L3_implies_ExpENN_zero (g : Summarizer Strings) (fstar : Strings → Y) (h3 : L3 g fstar) (Z : Strings) (hZ : InRange g Z)
  (h_summable : Summable (fun z => (g Z z).toReal * D fstar z Z)) :
  ExpENN (g Z) (fun z => ENNReal.ofReal (D fstar z Z)) = 0 := by
    -- Since each term in the sum is zero, the sum itself is zero.
    have h_zero_terms : ∀ z, (g Z z) * ENNReal.ofReal (D fstar z Z) = 0 := by
      by_contra h_nonzero;
      -- By definition of L3, we know that for any Z in the range of g, the expected distortion is zero.
      have h_exp_zero : ∀ z ∈ (g Z).support, D fstar z Z = 0 := by
        exact L3_implies_dist_zero_on_support g fstar h3 Z hZ h_summable;
      aesop;
    exact ENNReal.tsum_eq_zero.mpr fun _ => h_zero_terms _

/-
Helper: Exp over ZR at R=1 equals Egu over root.
-/
lemma Exp_ZR_one_eq_Egu (g : Summarizer Strings) (x : Strings) (T : BinTree Strings) (f : Strings → ℝ) :
  Exp (ZR g x 1 T) f = Egu g (root T) f := by
    unfold Exp Egu ZR root
    rfl

/-
Helper: Triangle inequality for distortion.
-/
lemma D_triangle (fstar : Strings → Y) (w z x : Strings) :
  D fstar w x ≤ D fstar w z + D fstar z x := by
    unfold D
    exact dist_triangle (fstar w) (fstar z) (fstar x)

/-
Helper: Exp is linear (for adding functions).
-/
lemma Exp_add (p : PMF Strings) (f₁ f₂ : Strings → ℝ)
  (hf₁ : Summable (fun z => (p z).toReal * f₁ z))
  (hf₂ : Summable (fun z => (p z).toReal * f₂ z)) :
  Exp p (fun z => f₁ z + f₂ z) = Exp p f₁ + Exp p f₂ := by
    unfold Exp
    rw [← tsum_add hf₁ hf₂]
    congr 1
    ext z
    ring

/-
Helper: Exp is monotone for non-negative functions.
-/
lemma Exp_mono (p : PMF Strings) (f₁ f₂ : Strings → ℝ) (h : ∀ z, f₁ z ≤ f₂ z) :
  Exp p f₁ ≤ Exp p f₂ := by
    unfold Exp
    apply tsum_le_tsum
    · intro z; exact mul_le_mul_of_nonneg_left (h z) ENNReal.toReal_nonneg
    · exact PMF.summable_coe_real_mul p f₁
    · exact PMF.summable_coe_real_mul p f₂

/-
Helper: ZR at R+1 is bind of ZR at R with g, when R ≥ 1.
-/
lemma ZR_succ_eq_bind (g : Summarizer Strings) (x : Strings) (R : ℕ) (T : BinTree Strings) (hR : R ≥ 1) :
  ZR g x (R + 1) T = (ZR g x R T).bind g := by
    cases R with
    | zero => exact absurd hR (by decide)
    | succ n => rfl

/-
Helper: Law of iterated expectation - the key lemma relating Exp of bind to nested Exp.
For non-negative f, Exp (p.bind g) f = Exp p (fun z => Exp (g z) f).
This is a standard result (Fubini/Tonelli for discrete measures).

Proof sketch: By definition,
  LHS = ∑' w, (∑' z, p z * g z w).toReal * f w
  RHS = ∑' z, (p z).toReal * (∑' w, (g z w).toReal * f w)
These are equal by Fubini's theorem for non-negative summable functions.
-/
lemma Exp_bind_eq (p : PMF Strings) (g : Summarizer Strings) (f : Strings → ℝ) (hf : ∀ z, 0 ≤ f z) :
  Exp (p.bind g) f = Exp p (fun z => Exp (g z) f) := by
    -- Step 1: Inner expectations are non-negative
    have hExp_nonneg : ∀ z, 0 ≤ Exp (g z) f := fun z => by
      unfold Exp; apply tsum_nonneg; intro w; exact mul_nonneg ENNReal.toReal_nonneg (hf w)
    -- Step 2: Convert both sides to ENNReal
    rw [Exp_eq_ExpENN_toReal (p.bind g) f hf]
    rw [Exp_eq_ExpENN_toReal p (fun z => Exp (g z) f) hExp_nonneg]
    -- Step 3: Show the ENNReal expressions are equal
    congr 1
    -- Step 4: Use ExpENN_bind (already proven)
    rw [ExpENN_bind]
    -- Step 5: Show ExpENN (g z) (ofReal ∘ f) = ofReal (Exp (g z) f) for each z
    congr 1; ext z
    unfold ExpENN Exp
    symm
    rw [ENNReal.ofReal_tsum_of_nonneg]
    · congr 1; ext w
      rw [ENNReal.toReal_mul, ENNReal.ofReal_mul (hf w)]
      rw [ENNReal.ofReal_toReal ((g z).apply_ne_top w)]
    · intro w; exact mul_nonneg ENNReal.toReal_nonneg (hf w)
    · exact PMF.summable_coe_real_mul (g z) f

lemma Exp_bind_le (p : PMF Strings) (g : Summarizer Strings) (f : Strings → ℝ) (hf : ∀ z, 0 ≤ f z) :
  Exp (p.bind g) f ≤ Exp p (fun z => Exp (g z) f) := by
    rw [Exp_bind_eq p g f hf]

/-
Multi-Round Preservation (Theorem 2): If L1, L2, L3 hold and R ≥ 1, then the expected distortion after R rounds is 0.
-/
theorem multi_round (g : Summarizer Strings) (T : BinTree Strings) (x : Strings) (R : ℕ) (fstar : Strings → Y)
  (hp : S T = x) (h1 : L1 g T fstar) (h2 : L2 g T fstar) (h3 : L3 g fstar) (hR : R ≥ 1) :
  Exp (ZR g x R T) (fun z => D fstar z x) = 0 := by
    induction' hR with R' hR' ih generalizing x T
    -- Base case: R = 1
    · rw [Exp_ZR_one_eq_Egu]
      exact one_pass g T x fstar hp h1 h2
    -- Inductive case: R = R' + 1 where R' ≥ 1
    · rw [ZR_succ_eq_bind g x R' T hR']
      -- We show Exp ((ZR g x R' T).bind g) (D fstar · x) = 0
      -- Strategy: D(w, x) ≤ D(w, z) + D(z, x), so
      --   E[D(W, x)] ≤ E[D(W, Z)] + E[D(Z, x)]
      --   where Z ~ ZR R', W ~ g(Z)
      -- First term is 0 by L3, second by IH
      have hD_nonneg : ∀ z, 0 ≤ D fstar z x := fun z => dist_nonneg
      have h_exp_nonneg : 0 ≤ Exp ((ZR g x R' T).bind g) (fun z => D fstar z x) := by
        unfold Exp
        apply tsum_nonneg
        intro z
        exact mul_nonneg ENNReal.toReal_nonneg (hD_nonneg z)
      -- By triangle inequality and iterated expectation
      have h_bound : Exp ((ZR g x R' T).bind g) (fun w => D fstar w x) ≤
                     Exp (ZR g x R' T) (fun z => Eg g (fun w => D fstar w z) z) +
                     Exp (ZR g x R' T) (fun z => D fstar z x) := by
        calc Exp ((ZR g x R' T).bind g) (fun w => D fstar w x)
          ≤ Exp (ZR g x R' T) (fun z => Exp (g z) (fun w => D fstar w x)) := by
              exact Exp_bind_le (ZR g x R' T) g (fun w => D fstar w x) hD_nonneg
          _ ≤ Exp (ZR g x R' T) (fun z => Exp (g z) (fun w => D fstar w z + D fstar z x)) := by
              apply Exp_mono
              intro z
              apply Exp_mono
              intro w
              exact D_triangle fstar w z x
          _ = Exp (ZR g x R' T) (fun z => Exp (g z) (fun w => D fstar w z) + Exp (g z) (fun _ => D fstar z x)) := by
              congr 1; ext z
              rw [Exp_add]
              · exact PMF.summable_coe_real_mul (g z) _
              · exact PMF.summable_coe_real_mul (g z) _
          _ = Exp (ZR g x R' T) (fun z => Eg g (fun w => D fstar w z) z + D fstar z x) := by
              congr 1; ext z
              unfold Eg Exp
              congr 1
              -- Exp (g z) (fun _ => D fstar z x) = D fstar z x since PMF sums to 1
              simp only [tsum_mul_right]
              rw [PMF.toReal_tsum_coe]
              ring
          _ ≤ Exp (ZR g x R' T) (fun z => Eg g (fun w => D fstar w z) z) +
              Exp (ZR g x R' T) (fun z => D fstar z x) := by
              rw [Exp_add]
              · exact PMF.summable_coe_real_mul (ZR g x R' T) _
              · exact PMF.summable_coe_real_mul (ZR g x R' T) _
      -- First term is 0 by multi_round_step (uses L3)
      have h_first_zero : Exp (ZR g x R' T) (fun z => Eg g (fun w => D fstar w z) z) = 0 :=
        multi_round_step g x R' T fstar h3 (ZR_support_in_range g x R' T hR')
      -- Second term is 0 by IH
      have h_second_zero : Exp (ZR g x R' T) (fun z => D fstar z x) = 0 := ih T x hp h1 h2
      -- Combine: 0 ≤ result ≤ 0 + 0 = 0
      linarith

-- =============================================================================
-- Section 8: Global Variant
-- =============================================================================

/-
A1: Global Sufficiency
Stronger than L1: holds for ALL strings, not just realized leaves.
-/
def A1_global (g : Strings → Strings) (fstar : Strings → Y) : Prop :=
  ∀ z : Strings, D fstar (g z) z = 0

/-
A2: Global Compatibility
Two-route identity: going direct or through double summarization gives same oracle value.
-/
def A2_global (g : Strings → Strings) (fstar : Strings → Y) : Prop :=
  ∀ u v : Strings, D fstar (u * v) (g (g u * g v)) = 0

/-
A3: Merge Depends on Oracle
There exists a merge function M on oracle values that:
1. Correctly computes the merged oracle value
2. Respects equivalence (zero distance implies zero distance of merge)
-/
def A3_global (g : Strings → Strings) (fstar : Strings → Y) : Prop :=
  ∃ M : Y → Y → Y,
    (∀ u v : Strings, D fstar (g (g u * g v)) (M (fstar (g u)) (fstar (g v))) = 0) ∧
    (∀ y₁ y₁' y₂ y₂' : Y, dist y₁ y₁' = 0 → dist y₂ y₂' = 0 →
      dist (M y₁ y₂) (M y₁' y₂') = 0)

/-
InOracleRange: y is in the range of f* ∘ g
-/
def InOracleRange (g : Strings → Strings) (fstar : Strings → Y) (y : Y) : Prop :=
  ∃ z : Strings, fstar (g z) = y

/-
Helper: D is symmetric (since dist is symmetric in a PseudoMetricSpace)
-/
lemma D_symm (fstar : Strings → Y) (x y : Strings) : D fstar x y = D fstar y x := by
  unfold D
  exact dist_comm (fstar x) (fstar y)

/-
Helper: D satisfies triangle inequality
-/
lemma D_triangle' (fstar : Strings → Y) (x y z : Strings) :
  D fstar x z ≤ D fstar x y + D fstar y z := by
  unfold D
  exact dist_triangle (fstar x) (fstar y) (fstar z)

/-
Concatenation Congruence: If f*(a) ≈ f*(a') and f*(b) ≈ f*(b'), then f*(a⊕b) ≈ f*(a'⊕b').
This follows from A1, A2, A3 using triangle inequality.
-/
theorem concat_congruence (g : Strings → Strings) (fstar : Strings → Y)
  (hA1 : A1_global g fstar) (hA2 : A2_global g fstar) (hA3 : A3_global g fstar)
  (a a' b b' : Strings) (ha : D fstar a a' = 0) (hb : D fstar b b' = 0) :
  D fstar (a * b) (a' * b') = 0 := by
    -- Get the merge function M from A3
    obtain ⟨M, hM1, hM2⟩ := hA3
    -- Let U = g(g(a) ⊕ g(b)) and U' = g(g(a') ⊕ g(b'))
    set U := g (g a * g b) with hU_def
    set U' := g (g a' * g b') with hU'_def
    -- By triangle inequality:
    -- D(a⊕b, a'⊕b') ≤ D(a⊕b, U) + D(U, U') + D(U', a'⊕b')
    have h_tri : D fstar (a * b) (a' * b') ≤
                 D fstar (a * b) U + D fstar U U' + D fstar U' (a' * b') := by
      calc D fstar (a * b) (a' * b')
        ≤ D fstar (a * b) U + D fstar U (a' * b') := D_triangle' fstar (a * b) U (a' * b')
        _ ≤ D fstar (a * b) U + (D fstar U U' + D fstar U' (a' * b')) := by
            linarith [D_triangle' fstar U U' (a' * b')]
        _ = D fstar (a * b) U + D fstar U U' + D fstar U' (a' * b') := by ring
    -- First term: D(a⊕b, U) = 0 by A2
    have h1 : D fstar (a * b) U = 0 := hA2 a b
    -- Third term: D(U', a'⊕b') = 0 by A2 (symmetry)
    have h3 : D fstar U' (a' * b') = 0 := by rw [D_symm]; exact hA2 a' b'
    -- Second term: D(U, U') = 0
    -- We need to show f*(g(g(a)⊕g(b))) ≈ f*(g(g(a')⊕g(b')))
    -- By A3, f*(U) ≈ M(f*(g(a)), f*(g(b))) and f*(U') ≈ M(f*(g(a')), f*(g(b')))
    -- By A1, f*(g(a)) ≈ f*(a) and f*(g(a')) ≈ f*(a'), so f*(g(a)) ≈ f*(g(a'))
    -- Similarly for b. Then by A3's second property, M(...) ≈ M(...).
    have hga : dist (fstar (g a)) (fstar (g a')) = 0 := by
      have hga1 : D fstar (g a) a = 0 := hA1 a
      have hga'1 : D fstar (g a') a' = 0 := hA1 a'
      unfold D at hga1 hga'1 ha
      calc dist (fstar (g a)) (fstar (g a'))
        ≤ dist (fstar (g a)) (fstar a) + dist (fstar a) (fstar (g a')) := dist_triangle _ _ _
        _ = dist (fstar (g a)) (fstar a) + dist (fstar a) (fstar a') +
            dist (fstar a') (fstar (g a')) - dist (fstar a) (fstar a') := by ring
        _ ≤ dist (fstar (g a)) (fstar a) +
            (dist (fstar a) (fstar a') + dist (fstar a') (fstar (g a'))) := by
            linarith [dist_triangle (fstar a) (fstar a') (fstar (g a'))]
        _ = 0 + (0 + 0) := by rw [hga1, ha, dist_comm (fstar a') (fstar (g a')), hga'1]
        _ = 0 := by ring
    have hgb : dist (fstar (g b)) (fstar (g b')) = 0 := by
      have hgb1 : D fstar (g b) b = 0 := hA1 b
      have hgb'1 : D fstar (g b') b' = 0 := hA1 b'
      unfold D at hgb1 hgb'1 hb
      calc dist (fstar (g b)) (fstar (g b'))
        ≤ dist (fstar (g b)) (fstar b) + dist (fstar b) (fstar (g b')) := dist_triangle _ _ _
        _ ≤ dist (fstar (g b)) (fstar b) +
            (dist (fstar b) (fstar b') + dist (fstar b') (fstar (g b'))) := by
            linarith [dist_triangle (fstar b) (fstar b') (fstar (g b'))]
        _ = 0 + (0 + 0) := by rw [hgb1, hb, dist_comm (fstar b') (fstar (g b')), hgb'1]
        _ = 0 := by ring
    have hM_eq : dist (M (fstar (g a)) (fstar (g b))) (M (fstar (g a')) (fstar (g b'))) = 0 :=
      hM2 _ _ _ _ hga hgb
    have h2 : D fstar U U' = 0 := by
      have hU_M : D fstar U (M (fstar (g a)) (fstar (g b))) = 0 := by
        unfold D; calc dist (fstar U) (M (fstar (g a)) (fstar (g b)))
          = dist (fstar (g (g a * g b))) (M (fstar (g a)) (fstar (g b))) := rfl
          _ = 0 := by unfold D at hM1; exact hM1 a b
      have hU'_M : D fstar U' (M (fstar (g a')) (fstar (g b'))) = 0 := by
        unfold D; exact hM1 a' b'
      unfold D
      calc dist (fstar U) (fstar U')
        ≤ dist (fstar U) (M (fstar (g a)) (fstar (g b))) +
          dist (M (fstar (g a)) (fstar (g b))) (fstar U') := dist_triangle _ _ _
        _ ≤ dist (fstar U) (M (fstar (g a)) (fstar (g b))) +
          (dist (M (fstar (g a)) (fstar (g b))) (M (fstar (g a')) (fstar (g b'))) +
           dist (M (fstar (g a')) (fstar (g b'))) (fstar U')) := by
            linarith [dist_triangle (M (fstar (g a)) (fstar (g b)))
                                    (M (fstar (g a')) (fstar (g b')))
                                    (fstar U')]
        _ = 0 + (0 + 0) := by
            unfold D at hU_M hU'_M
            rw [hU_M, hM_eq, dist_comm, hU'_M]
        _ = 0 := by ring
    -- Combine: D(a⊕b, a'⊕b') ≤ 0 + 0 + 0 = 0, and D ≥ 0, so D = 0
    have h_nonneg : 0 ≤ D fstar (a * b) (a' * b') := dist_nonneg
    linarith

/-
Oracle Merge Operation: Given A3, we extract the merge function M.
-/
noncomputable def oracleMerge (hA3 : A3_global g fstar) : Y → Y → Y := hA3.choose

/-
Helper: The oracle merge respects the A3 properties.
-/
lemma oracleMerge_spec (g : Strings → Strings) (fstar : Strings → Y) (hA3 : A3_global g fstar) :
  (∀ u v : Strings, D fstar (g (g u * g v)) (oracleMerge hA3 (fstar (g u)) (fstar (g v))) = 0) ∧
  (∀ y₁ y₁' y₂ y₂' : Y, dist y₁ y₁' = 0 → dist y₂ y₂' = 0 →
    dist (oracleMerge hA3 y₁ y₂) (oracleMerge hA3 y₁' y₂') = 0) :=
  hA3.choose_spec

/-
Merge Associativity: For y₁, y₂, y₃ in the oracle range, (y₁ ⊙ y₂) ⊙ y₃ ≈ y₁ ⊙ (y₂ ⊙ y₃).
The proof uses string associativity and A2/A3.
-/
theorem merge_assoc (g : Strings → Strings) (fstar : Strings → Y)
  (hA1 : A1_global g fstar) (hA2 : A2_global g fstar) (hA3 : A3_global g fstar)
  (y₁ y₂ y₃ : Y)
  (hy₁ : InOracleRange g fstar y₁)
  (hy₂ : InOracleRange g fstar y₂)
  (hy₃ : InOracleRange g fstar y₃) :
  dist (oracleMerge hA3 (oracleMerge hA3 y₁ y₂) y₃)
       (oracleMerge hA3 y₁ (oracleMerge hA3 y₂ y₃)) = 0 := by
    -- Get witnesses: y₁ = f*(g(a)), y₂ = f*(g(b)), y₃ = f*(g(c))
    obtain ⟨a, ha⟩ := hy₁
    obtain ⟨b, hb⟩ := hy₂
    obtain ⟨c, hc⟩ := hy₃
    -- Get the merge function properties
    have ⟨hM1, hM2⟩ := oracleMerge_spec g fstar hA3
    -- LHS: (y₁ ⊙ y₂) ⊙ y₃
    -- RHS: y₁ ⊙ (y₂ ⊙ y₃)
    -- We'll show both are close to f*((a * b) * c) = f*(a * (b * c))
    -- Strategy: Use A2/A3 to connect merge to string concatenation
    -- First, y₁ ⊙ y₂ ≈ f*(g(g(a) * g(b)))
    have h12 : dist (oracleMerge hA3 y₁ y₂) (fstar (g (g a * g b))) = 0 := by
      rw [ha, hb]
      have := hM1 a b
      unfold D at this
      rw [dist_comm]
      exact this
    -- Then (y₁ ⊙ y₂) ⊙ y₃
    -- We need to relate this to f*((a*b)*c)
    -- Using A2: f*((a*b)*c) ≈ f*(g(g(a*b) * g(c)))
    -- And the merge respects equivalence
    -- This is getting complex; let's use a different approach
    -- Both sides relate to f*(a * b * c) via A2/A3, and (a*b)*c = a*(b*c) by monoid assoc
    have h_string_assoc : (a * b) * c = a * (b * c) := mul_assoc a b c
    -- LHS path: (y₁ ⊙ y₂) ⊙ y₃ → f*(g(g(g(a)*g(b)) * g(c))) → f*((a*b)*c)
    -- RHS path: y₁ ⊙ (y₂ ⊙ y₃) → f*(g(g(a) * g(g(b)*g(c)))) → f*(a*(b*c))
    -- Since (a*b)*c = a*(b*c), both paths lead to the same point
    -- Let's simplify by showing both are ≈ f*(a * b * c)
    set M := oracleMerge hA3
    -- Need to show M (M y₁ y₂) y₃ ≈ M y₁ (M y₂ y₃)
    -- We'll use triangle through f*(a * b * c)
    -- Step 1: M (M y₁ y₂) y₃ ≈ f*(g(g(g(a)*g(b)) * g(c)))
    have hLHS_step1 : dist (M (M y₁ y₂) y₃) (fstar (g (g (g a * g b) * g c))) = 0 := by
      have h12' : dist (M y₁ y₂) (fstar (g (g a * g b))) = 0 := h12
      -- M (M y₁ y₂) y₃ ≈ M (f*(g(g(a)*g(b)))) y₃ ≈ f*(g(g(g(a)*g(b)) * g(c)))
      have h_resp := hM2 (M y₁ y₂) (fstar (g (g a * g b))) y₃ y₃ h12' (dist_self _)
      calc dist (M (M y₁ y₂) y₃) (fstar (g (g (g a * g b) * g c)))
        ≤ dist (M (M y₁ y₂) y₃) (M (fstar (g (g a * g b))) (fstar (g c))) +
          dist (M (fstar (g (g a * g b))) (fstar (g c))) (fstar (g (g (g a * g b) * g c))) :=
            dist_triangle _ _ _
        _ = 0 + 0 := by
            rw [h_resp, hc]
            have := hM1 (g a * g b) c
            unfold D at this
            rw [dist_comm, this]
        _ = 0 := by ring
    -- Step 2: f*(g(g(g(a)*g(b)) * g(c))) ≈ f*((a*b)*c) via A2 applied twice
    have hLHS_step2 : dist (fstar (g (g (g a * g b) * g c))) (fstar ((a * b) * c)) = 0 := by
      -- First: g(g(a)*g(b)) ≈ a*b by A2
      have hAB : D fstar (a * b) (g (g a * g b)) = 0 := hA2 a b
      -- So f*(g(g(a)*g(b))) ≈ f*(a*b), hence by A1: f*(g(g(g(a)*g(b)))) ≈ f*(g(a*b)) ≈ f*(a*b)
      -- Then: g(g(a*b) * g(c)) ≈ (a*b)*c by A2
      -- We need: f*(g(g(g(a)*g(b)) * g(c))) ≈ f*((a*b)*c)
      -- By A2 on (a*b) and c: f*((a*b)*c) ≈ f*(g(g(a*b) * g(c)))
      have hABC : D fstar ((a*b) * c) (g (g (a*b) * g c)) = 0 := hA2 (a*b) c
      -- Need to show g(g(g(a)*g(b)) * g(c)) ≈ g(g(a*b) * g(c))
      -- By A1: g(g(a)*g(b)) ≈ a*b, and g(c) ≈ c
      -- Actually this is more subtle. Let's use concat_congruence indirectly
      -- g(g(a)*g(b)) and (a*b) have f* values that are 0-distant by symmetry of A2
      have hAB' : D fstar (g (g a * g b)) (a * b) = 0 := by rw [D_symm]; exact hA2 a b
      -- By A1: D(g(g(g(a)*g(b))), g(a*b)) involves... this is getting complex
      -- Simpler: use that f*(g(x)) ≈ f*(x) by A1 for any x
      -- f*(g(g(g(a)*g(b)) * g(c))) ≈ f*(g(g(a)*g(b)) * g(c)) by A1
      have step1 : D fstar (g (g (g a * g b) * g c)) ((g (g a * g b)) * g c) = 0 := by
        rw [D_symm]; exact hA2 (g (g a * g b)) (g c)
      -- f*((g(g(a)*g(b))) * g(c)) ≈ f*((a*b) * g(c)) by concat_congruence using hAB'
      have hgc : D fstar (g c) (g c) = 0 := dist_self _
      have step2 : D fstar ((g (g a * g b)) * g c) ((a * b) * g c) = 0 := by
        exact concat_congruence g fstar hA1 hA2 hA3 (g (g a * g b)) (a*b) (g c) (g c) hAB' hgc
      -- f*((a*b) * g(c)) ≈ f*((a*b) * c) by concat_congruence using A1 on c
      have hc' : D fstar (g c) c = 0 := hA1 c
      have hab_self : D fstar (a*b) (a*b) = 0 := dist_self _
      have step3 : D fstar ((a*b) * g c) ((a*b) * c) = 0 := by
        exact concat_congruence g fstar hA1 hA2 hA3 (a*b) (a*b) (g c) c hab_self hc'
      unfold D at step1 step2 step3 ⊢
      calc dist (fstar (g (g (g a * g b) * g c))) (fstar ((a * b) * c))
        ≤ dist (fstar (g (g (g a * g b) * g c))) (fstar ((g (g a * g b)) * g c)) +
          dist (fstar ((g (g a * g b)) * g c)) (fstar ((a * b) * c)) := dist_triangle _ _ _
        _ ≤ dist (fstar (g (g (g a * g b) * g c))) (fstar ((g (g a * g b)) * g c)) +
          (dist (fstar ((g (g a * g b)) * g c)) (fstar ((a * b) * g c)) +
           dist (fstar ((a * b) * g c)) (fstar ((a * b) * c))) := by
             linarith [dist_triangle (fstar ((g (g a * g b)) * g c))
                                     (fstar ((a * b) * g c))
                                     (fstar ((a * b) * c))]
        _ = 0 + (0 + 0) := by rw [step1, step2, step3]
        _ = 0 := by ring
    -- Similarly for RHS
    have hRHS_step1 : dist (M y₁ (M y₂ y₃)) (fstar (g (g a * g (g b * g c)))) = 0 := by
      have h23 : dist (M y₂ y₃) (fstar (g (g b * g c))) = 0 := by
        rw [hb, hc]
        have := hM1 b c
        unfold D at this
        rw [dist_comm]
        exact this
      have h_resp := hM2 y₁ y₁ (M y₂ y₃) (fstar (g (g b * g c))) (dist_self _) h23
      calc dist (M y₁ (M y₂ y₃)) (fstar (g (g a * g (g b * g c))))
        ≤ dist (M y₁ (M y₂ y₃)) (M (fstar (g a)) (fstar (g (g b * g c)))) +
          dist (M (fstar (g a)) (fstar (g (g b * g c)))) (fstar (g (g a * g (g b * g c)))) :=
            dist_triangle _ _ _
        _ = 0 + 0 := by
            rw [ha, h_resp]
            have := hM1 a (g b * g c)
            unfold D at this
            rw [dist_comm, this]
        _ = 0 := by ring
    have hRHS_step2 : dist (fstar (g (g a * g (g b * g c)))) (fstar (a * (b * c))) = 0 := by
      -- Similar to LHS_step2 but for the other association
      have hBC : D fstar (g (g b * g c)) (b * c) = 0 := by rw [D_symm]; exact hA2 b c
      have hga_self : D fstar (g a) (g a) = 0 := dist_self _
      have step1 : D fstar (g (g a * g (g b * g c))) (g a * g (g b * g c)) = 0 := by
        rw [D_symm]; exact hA2 (g a) (g (g b * g c))
      have step2 : D fstar (g a * g (g b * g c)) (g a * (b * c)) = 0 := by
        exact concat_congruence g fstar hA1 hA2 hA3 (g a) (g a) (g (g b * g c)) (b*c) hga_self hBC
      have ha' : D fstar (g a) a = 0 := hA1 a
      have hbc_self : D fstar (b*c) (b*c) = 0 := dist_self _
      have step3 : D fstar (g a * (b * c)) (a * (b * c)) = 0 := by
        exact concat_congruence g fstar hA1 hA2 hA3 (g a) a (b*c) (b*c) ha' hbc_self
      unfold D at step1 step2 step3 ⊢
      calc dist (fstar (g (g a * g (g b * g c)))) (fstar (a * (b * c)))
        ≤ dist (fstar (g (g a * g (g b * g c)))) (fstar (g a * g (g b * g c))) +
          dist (fstar (g a * g (g b * g c))) (fstar (a * (b * c))) := dist_triangle _ _ _
        _ ≤ dist (fstar (g (g a * g (g b * g c)))) (fstar (g a * g (g b * g c))) +
          (dist (fstar (g a * g (g b * g c))) (fstar (g a * (b * c))) +
           dist (fstar (g a * (b * c))) (fstar (a * (b * c)))) := by
             linarith [dist_triangle (fstar (g a * g (g b * g c)))
                                     (fstar (g a * (b * c)))
                                     (fstar (a * (b * c)))]
        _ = 0 + (0 + 0) := by rw [step1, step2, step3]
        _ = 0 := by ring
    -- Now combine: LHS ≈ f*((a*b)*c) = f*(a*(b*c)) ≈ RHS
    calc dist (M (M y₁ y₂) y₃) (M y₁ (M y₂ y₃))
      ≤ dist (M (M y₁ y₂) y₃) (fstar ((a * b) * c)) +
        dist (fstar ((a * b) * c)) (M y₁ (M y₂ y₃)) := dist_triangle _ _ _
      _ ≤ (dist (M (M y₁ y₂) y₃) (fstar (g (g (g a * g b) * g c))) +
           dist (fstar (g (g (g a * g b) * g c))) (fstar ((a * b) * c))) +
          dist (fstar ((a * b) * c)) (M y₁ (M y₂ y₃)) := by
            linarith [dist_triangle (M (M y₁ y₂) y₃)
                                    (fstar (g (g (g a * g b) * g c)))
                                    (fstar ((a * b) * c))]
      _ = (0 + 0) + dist (fstar ((a * b) * c)) (M y₁ (M y₂ y₃)) := by
            rw [hLHS_step1, hLHS_step2]
      _ = dist (fstar (a * (b * c))) (M y₁ (M y₂ y₃)) := by rw [h_string_assoc]; ring
      _ ≤ dist (fstar (a * (b * c))) (fstar (g (g a * g (g b * g c)))) +
          dist (fstar (g (g a * g (g b * g c)))) (M y₁ (M y₂ y₃)) := dist_triangle _ _ _
      _ = 0 + 0 := by rw [dist_comm, hRHS_step2, dist_comm, hRHS_step1]
      _ = 0 := by ring

/-
Merge Identity: f*(g(1)) is a left and right identity for ⊙ on the oracle range.
-/
theorem merge_identity (g : Strings → Strings) (fstar : Strings → Y)
  (hA1 : A1_global g fstar) (hA2 : A2_global g fstar) (hA3 : A3_global g fstar)
  (y : Y) (hy : InOracleRange g fstar y) :
  dist (oracleMerge hA3 (fstar (g 1)) y) y = 0 ∧
  dist (oracleMerge hA3 y (fstar (g 1))) y = 0 := by
    obtain ⟨a, ha⟩ := hy
    have ⟨hM1, hM2⟩ := oracleMerge_spec g fstar hA3
    set M := oracleMerge hA3
    constructor
    -- Left identity: M(f*(g(1)), y) ≈ y
    · -- M(f*(g(1)), f*(g(a))) ≈ f*(g(g(1) * g(a))) by A3
      have h1 : dist (M (fstar (g 1)) y) (fstar (g (g 1 * g a))) = 0 := by
        rw [ha]
        have := hM1 1 a
        unfold D at this
        rw [dist_comm]
        exact this
      -- f*(g(g(1) * g(a))) ≈ f*(1 * a) by A2 (symmetry) and then = f*(a)
      have h2 : dist (fstar (g (g 1 * g a))) (fstar a) = 0 := by
        have hA2' : D fstar (1 * a) (g (g 1 * g a)) = 0 := hA2 1 a
        unfold D at hA2'
        rw [one_mul] at hA2'
        rw [dist_comm]
        exact hA2'
      -- f*(a) = f*(g(a)) by A1 (symmetry)... wait, no. f*(g(a)) ≈ f*(a) by A1.
      -- We need y = f*(g(a)), so we need dist(f*(a), f*(g(a))) = 0
      have h3 : dist (fstar a) (fstar (g a)) = 0 := by
        have := hA1 a
        unfold D at this
        rw [dist_comm]
        exact this
      calc dist (M (fstar (g 1)) y) y
        = dist (M (fstar (g 1)) y) (fstar (g a)) := by rw [ha]
        _ ≤ dist (M (fstar (g 1)) y) (fstar (g (g 1 * g a))) +
            dist (fstar (g (g 1 * g a))) (fstar (g a)) := dist_triangle _ _ _
        _ ≤ dist (M (fstar (g 1)) y) (fstar (g (g 1 * g a))) +
            (dist (fstar (g (g 1 * g a))) (fstar a) + dist (fstar a) (fstar (g a))) := by
              linarith [dist_triangle (fstar (g (g 1 * g a))) (fstar a) (fstar (g a))]
        _ = 0 + (0 + 0) := by rw [h1, h2, h3]
        _ = 0 := by ring
    -- Right identity: M(y, f*(g(1))) ≈ y
    · have h1 : dist (M y (fstar (g 1))) (fstar (g (g a * g 1))) = 0 := by
        rw [ha]
        have := hM1 a 1
        unfold D at this
        rw [dist_comm]
        exact this
      have h2 : dist (fstar (g (g a * g 1))) (fstar a) = 0 := by
        have hA2' : D fstar (a * 1) (g (g a * g 1)) = 0 := hA2 a 1
        unfold D at hA2'
        rw [mul_one] at hA2'
        rw [dist_comm]
        exact hA2'
      have h3 : dist (fstar a) (fstar (g a)) = 0 := by
        have := hA1 a
        unfold D at this
        rw [dist_comm]
        exact this
      calc dist (M y (fstar (g 1))) y
        = dist (M y (fstar (g 1))) (fstar (g a)) := by rw [ha]
        _ ≤ dist (M y (fstar (g 1))) (fstar (g (g a * g 1))) +
            dist (fstar (g (g a * g 1))) (fstar (g a)) := dist_triangle _ _ _
        _ ≤ dist (M y (fstar (g 1))) (fstar (g (g a * g 1))) +
            (dist (fstar (g (g a * g 1))) (fstar a) + dist (fstar a) (fstar (g a))) := by
              linarith [dist_triangle (fstar (g (g a * g 1))) (fstar a) (fstar (g a))]
        _ = 0 + (0 + 0) := by rw [h1, h2, h3]
        _ = 0 := by ring

-- =============================================================================
-- Section 9: Score Transport (Measure-Theoretic)
-- =============================================================================

/-
This section formalizes the Score Transport lemma from Section 5 of the paper.
It establishes that if the oracle is preserved by summarization, then training
signals (supervision scores) are also preserved.

Key result: If σ(f*(X)) ⊆ σ(Z), then E[S*(X, a)] = E[S_Z(Z, a)] = E[Q̄(f*(X), a)]

This uses Mathlib's measure theory library for conditional expectations.
-/

section ScoreTransport

open MeasureTheory ProbabilityTheory Set Filter TopologicalSpace
open scoped ENNReal MeasureTheory ProbabilityTheory

-- Probability space with base sigma-algebra m₀
variable {Ω : Type*} {m₀ : MeasurableSpace Ω}
variable {μ : @Measure Ω m₀} [IsProbabilityMeasure μ]

-- Document space (needs measurable structure for measure theory)
variable {Strings' : Type*} [MeasurableSpace Strings'] [Monoid Strings']

-- Oracle space (with both metric and measurable structure)
variable {Y' : Type*} [PseudoMetricSpace Y'] [MeasurableSpace Y'] [BorelSpace Y']

-- Action space
variable {A : Type*}

/-
Conditional Factorization (CF): Supervision depends on document only through oracle value.
This axiom states that there exists a function Qbar : Y → A → ℝ such that
E[S*(X, a) | X] = Qbar(f*(X), a) almost surely.

The key insight is that the supervision score factors through the oracle function.
-/
def ConditionalFactorization'
    (Sstar : Strings' → A → ℝ) (fstar : Strings' → Y')
    (X : Ω → Strings') (μ : @Measure Ω m₀) (hX : @Measurable Ω Strings' m₀ _ X) : Prop :=
  ∃ Qbar : Y' → A → ℝ,
    (∀ a, Measurable (fun y => Qbar y a)) ∧
    ∀ a : A,
      μ[fun ω => Sstar (X ω) a | MeasurableSpace.comap X ‹_›]
        =ᵐ[μ] fun ω => Qbar (fstar (X ω)) a

/-
Summary-indexed score: S_Z(Z, a) := E[S*(X, a) | Z]
This is the conditional expectation of the supervision score given the summary Z.
-/
def SummaryScore' (Sstar : Strings' → A → ℝ) (X Z : Ω → Strings')
    (μ : @Measure Ω m₀) (a : A) : Ω → ℝ :=
  μ[fun ω => Sstar (X ω) a | MeasurableSpace.comap Z ‹_›]

/-
σ(f*(X)) ⊆ σ(Z): The sigma-algebra generated by f*(X) is contained in that generated by Z.
This means the oracle value is determined by the summary (oracle information is preserved).
-/
def OracleSigmaSubset' (fstar : Strings' → Y') (X Z : Ω → Strings') : Prop :=
  MeasurableSpace.comap (fstar ∘ X) ‹_› ≤ MeasurableSpace.comap Z ‹_›

/-
Blackwell/Doob-Dynkin Score Transport Lemma.
If σ(f*(X)) ⊆ σ(Z), then:
  E[S*(X, a)] = E[S_Z(Z, a)] = E[Q̄(f*(X), a)]

This theorem establishes that training on summaries is equivalent to training on
original documents when the oracle is preserved.

Part 1: E[S*] = E[E[S*|Z]] by the tower property of conditional expectation.
Part 2: E[S*] = E[Qbar(f*(X))] via the CF axiom.

Note: This requires SigmaFinite assumptions on the trimmed measures.
-/
theorem blackwell_transport'
    (Sstar : Strings' → A → ℝ) (fstar : Strings' → Y') (X Z : Ω → Strings')
    (hX : @Measurable Ω Strings' m₀ _ X) (hZ : @Measurable Ω Strings' m₀ _ Z)
    (hfstar : Measurable fstar)
    [hμZ : SigmaFinite (μ.trim hZ.comap_le)]
    [hμX : SigmaFinite (μ.trim hX.comap_le)]
    (hCF : ConditionalFactorization' Sstar fstar X μ hX)
    (hσ : OracleSigmaSubset' fstar X Z)
    (a : A) (hint : Integrable (fun ω => Sstar (X ω) a) μ) :
    -- Part 1: Tower property - E[S*] = E[E[S*|Z]]
    ∫ ω, Sstar (X ω) a ∂μ = ∫ ω, SummaryScore' Sstar X Z μ a ω ∂μ ∧
    -- Part 2: Factorization via CF - E[S*] = E[Qbar(f*(X))]
    ∫ ω, Sstar (X ω) a ∂μ = ∫ ω, hCF.choose (fstar (X ω)) a ∂μ := by
  -- Extract Qbar and its properties from CF
  have hQbar_meas := hCF.choose_spec.1
  have hQbar_eq := hCF.choose_spec.2
  constructor
  -- Part 1: E[S*] = E[E[S*|Z]] by tower property
  · unfold SummaryScore'
    exact (MeasureTheory.integral_condExp hZ.comap_le).symm
  -- Part 2: E[S*] = E[Qbar(f*(X))] via CF
  · rw [← MeasureTheory.integral_condExp hX.comap_le]
    exact integral_congr_ae (hQbar_eq a)

/-
When σ(f*(X)) ⊆ σ(Z) ⊆ σ(X), conditioning on Z recovers the oracle-factored form.
Qbar(f*(X), a) is σ(Z)-measurable (since σ(f*(X)) ⊆ σ(Z)), and the set integral
equality follows from σ(Z) ⊆ σ(X) (every σ(Z)-measurable set is σ(X)-measurable).
-/
lemma condexp_oracle_factored'
    (Sstar : Strings' → A → ℝ) (fstar : Strings' → Y') (X Z : Ω → Strings')
    (hX : @Measurable Ω Strings' m₀ _ X) (hZ : @Measurable Ω Strings' m₀ _ Z)
    (hfstar : Measurable fstar)
    [hμZ : SigmaFinite (μ.trim hZ.comap_le)]
    [hμX : SigmaFinite (μ.trim hX.comap_le)]
    (hσ : OracleSigmaSubset' fstar X Z)  -- σ(f*(X)) ⊆ σ(Z)
    (hσ_ZX : MeasurableSpace.comap Z ‹_› ≤ MeasurableSpace.comap X ‹_›)  -- σ(Z) ⊆ σ(X)
    (hCF : ConditionalFactorization' Sstar fstar X μ hX)
    (a : A) (hint : Integrable (fun ω => Sstar (X ω) a) μ) :
    SummaryScore' Sstar X Z μ a =ᵐ[μ] fun ω => hCF.choose (fstar (X ω)) a := by
  -- Extract Qbar and its properties from CF
  have hQbar_meas := hCF.choose_spec.1
  have hQbar_eq := hCF.choose_spec.2
  unfold SummaryScore'

  -- Step 1: Show Qbar(f*(X), a) is σ(Z)-measurable
  -- Since Qbar is measurable and fstar ∘ X is σ(f*(X))-measurable,
  -- and σ(f*(X)) ⊆ σ(Z), we get σ(Z)-measurability
  have hfX_meas : Measurable (fstar ∘ X) := hfstar.comp hX
  have h_QfX_meas_fX : StronglyMeasurable[MeasurableSpace.comap (fstar ∘ X) ‹_›]
      (fun ω => hCF.choose (fstar (X ω)) a) :=
    (hQbar_meas a).stronglyMeasurable.comp_measurable measurable_id
  have h_QfX_meas_Z : StronglyMeasurable[MeasurableSpace.comap Z ‹_›]
      (fun ω => hCF.choose (fstar (X ω)) a) := h_QfX_meas_fX.mono hσ

  -- Step 2: Show integrability (from CF and hint)
  have h_QfX_int : Integrable (fun ω => hCF.choose (fstar (X ω)) a) μ :=
    hint.congr (hQbar_eq a)

  -- Step 3: Apply uniqueness characterization
  refine (ae_eq_condExp_of_forall_setIntegral_eq hZ.comap_le hint ?_ ?_
    h_QfX_meas_Z.aestronglyMeasurable).symm

  -- Integrability condition: integrable on finite measure sets
  · intro s _ hs_fin
    exact h_QfX_int.integrableOn

  -- Set integral equality: for σ(Z)-measurable S, ∫_S Qbar dμ = ∫_S S* dμ
  · intro s hs_Z hs_fin
    -- Since σ(Z) ⊆ σ(X), s is σ(X)-measurable
    have hs_X : MeasurableSet[MeasurableSpace.comap X ‹_›] s := hσ_ZX s hs_Z
    -- By setIntegral_condExp, ∫_S E[S*|X] dμ = ∫_S S* dμ for σ(X)-measurable S
    have h_eq := MeasureTheory.setIntegral_condExp hX.comap_le hint hs_X
    rw [← h_eq]
    -- E[S*|X] = Qbar a.s., so their set integrals are equal
    exact setIntegral_congr_ae (hZ.comap_le s hs_Z)
      ((hQbar_eq a).mono (fun x hx _ => hx.symm))

end ScoreTransport

-- =============================================================================
-- Section 6: Direct Preference Optimization
-- =============================================================================

/-
This section formalizes the DPO (Direct Preference Optimization) results from Section 6.
Key results:
1. Exact DPO Equivalence: If distortion is zero, training on summaries is equivalent to
   training on original documents.
2. DPO Gap Bound: With Lipschitz conditions, the DPO loss gap is bounded by expected distortion.

The formalization uses generic oracle-indexed preferences (more general than BTL),
explicit argmin over policy space, and support-restricted positivity for log-ratios.
-/

section DPO

open MeasureTheory Set Filter TopologicalSpace Real
open scoped ENNReal MeasureTheory

-- Action space for policies
variable {A : Type*}

-- Document and oracle spaces (reusing from earlier sections)
variable {Strings : Type*} [Monoid Strings]
variable {Y : Type*} [PseudoMetricSpace Y]

/-
Definition: Policy
A policy π(a | x) maps documents and actions to probabilities.
-/
def Policy (Strings A : Type*) := Strings → A → ℝ

/-
Definition: Log-Ratio of Policies
log(π(a|x)/π_ref(a|x)) = log(π(a|x)) - log(π_ref(a|x))
-/
noncomputable def LogRatio {Strings A : Type*} (π π_ref : Policy Strings A)
    (x : Strings) (a : A) : ℝ :=
  Real.log (π x a) - Real.log (π_ref x a)

/-
Definition: DPO Logit
Λ(x; a_w, a_ℓ) = β · (log-ratio(a_w) - log-ratio(a_ℓ))
-/
noncomputable def DPOLogit {Strings A : Type*} (π π_ref : Policy Strings A) (β : ℝ)
    (x : Strings) (a_w a_ℓ : A) : ℝ :=
  β * (LogRatio π π_ref x a_w - LogRatio π π_ref x a_ℓ)

/-
Definition: Pointwise DPO Loss
L(x; a_w, a_ℓ) = -log σ(Λ(x; a_w, a_ℓ))
-/
noncomputable def DPOLossPointwise {Strings A : Type*} (π π_ref : Policy Strings A) (β : ℝ)
    (x : Strings) (a_w a_ℓ : A) : ℝ :=
  -Real.log (Real.sigmoid (DPOLogit π π_ref β x a_w a_ℓ))

/-
Definition: Pair Generator
A pair generator samples (a_w, a_ℓ) preference pairs conditioned on document x.
We use PMF for discrete distributions to match the style of the file.
-/
def PairGenerator (Strings A : Type*) := Strings → PMF (A × A)

/-
Definition: Oracle-Measurable Policy
A policy is oracle-measurable if it depends on x only through f*(x).
-/
def DPO.OracleMeasurable {Strings A Y : Type*} [PseudoMetricSpace Y]
    (π : Policy Strings A) (fstar : Strings → Y) : Prop :=
  ∀ x x' a, dist (fstar x) (fstar x') = 0 → π x a = π x' a

/-
Definition: Oracle-Indexed Pair Generator
Pair generation depends on document only through oracle value.
-/
def OracleIndexedPairGen {Strings A Y : Type*} [PseudoMetricSpace Y]
    (gen : PairGenerator Strings A) (fstar : Strings → Y) : Prop :=
  ∀ x x', dist (fstar x) (fstar x') = 0 → gen x = gen x'

/-
Definition: Positive on Support
Policy is positive on the support of the pair generator.
This ensures log-ratios are well-defined.
-/
def PositiveOnSupport {Strings A : Type*} (π : Policy Strings A)
    (gen : PairGenerator Strings A) : Prop :=
  ∀ x p, p ∈ (gen x).support → 0 < π x p.1 ∧ 0 < π x p.2

/-
Definition: Policy Argmin
The set of policies that minimize a loss functional.
-/
def PolicyArgmin {Strings A : Type*} (loss : Policy Strings A → ℝ) : Set (Policy Strings A) :=
  {π | ∀ π', loss π ≤ loss π'}

/-
Definition: Same Argmin
Two loss functions have the same argmin.
-/
def SameArgmin {Strings A : Type*} (loss₁ loss₂ : Policy Strings A → ℝ) : Prop :=
  PolicyArgmin loss₁ = PolicyArgmin loss₂

/-
Definition: Expected DPO Loss (using PMF expectation style)
E_{x,p}[L(x; a_w, a_ℓ)]
-/
noncomputable def ExpectedDPOLoss {Strings A : Type*} (π π_ref : Policy Strings A) (β : ℝ)
    (μ : PMF Strings) (gen : PairGenerator Strings A) : ℝ :=
  ∑' x, (μ x).toReal * ∑' p, (gen x p).toReal * DPOLossPointwise π π_ref β x p.1 p.2

/-
Definition: Policy-Lipschitz Log-Ratio
Log-ratio is Lipschitz in oracle space.
-/
def PolicyLipschitz {Strings A Y : Type*} [PseudoMetricSpace Y]
    (π π_ref : Policy Strings A) (fstar : Strings → Y) (L : ℝ≥0) : Prop :=
  ∀ a x x', |LogRatio π π_ref x a - LogRatio π π_ref x' a| ≤ L * dist (fstar x) (fstar x')

/-
Definition: Reward-Lipschitz
Reward function is Lipschitz in oracle space.
-/
def RewardLipschitz {A Y : Type*} [PseudoMetricSpace Y] (R : Y → A → ℝ) (L : ℝ≥0) : Prop :=
  ∀ a y y', |R y a - R y' a| ≤ L * dist y y'

/-
Helper lemma: Zero distance implies equal oracle values.
-/
lemma eq_of_dist_eq_zero' {Y : Type*} [PseudoMetricSpace Y] {y y' : Y}
    (h : dist y y' = 0) : y = y' := by
  exact eq_of_dist_eq_zero h

/-
Helper lemma: Oracle-measurable policies give equal values when oracle values are equal.
-/
lemma oracle_meas_eq {Strings A Y : Type*} [PseudoMetricSpace Y]
    {π : Policy Strings A} {fstar : Strings → Y}
    (h_meas : DPO.OracleMeasurable π fstar) {x x' : Strings}
    (h_dist : dist (fstar x) (fstar x') = 0) (a : A) :
    π x a = π x' a := h_meas x x' a h_dist

/-
Helper lemma: Log-ratio is equal when oracle values are equal and policies are oracle-measurable.
-/
lemma log_ratio_eq_of_oracle_eq {Strings A Y : Type*} [PseudoMetricSpace Y]
    {π π_ref : Policy Strings A} {fstar : Strings → Y}
    (h_meas_π : DPO.OracleMeasurable π fstar)
    (h_meas_ref : DPO.OracleMeasurable π_ref fstar)
    {x x' : Strings} (h_dist : dist (fstar x) (fstar x') = 0) (a : A) :
    LogRatio π π_ref x a = LogRatio π π_ref x' a := by
  unfold LogRatio
  rw [oracle_meas_eq h_meas_π h_dist a, oracle_meas_eq h_meas_ref h_dist a]

/-
Helper lemma: DPO logit is equal when oracle values are equal.
-/
lemma dpo_logit_eq_of_oracle_eq {Strings A Y : Type*} [PseudoMetricSpace Y]
    {π π_ref : Policy Strings A} {fstar : Strings → Y} {β : ℝ}
    (h_meas_π : DPO.OracleMeasurable π fstar)
    (h_meas_ref : DPO.OracleMeasurable π_ref fstar)
    {x x' : Strings} (h_dist : dist (fstar x) (fstar x') = 0)
    (a_w a_ℓ : A) :
    DPOLogit π π_ref β x a_w a_ℓ = DPOLogit π π_ref β x' a_w a_ℓ := by
  unfold DPOLogit
  rw [log_ratio_eq_of_oracle_eq h_meas_π h_meas_ref h_dist a_w,
      log_ratio_eq_of_oracle_eq h_meas_π h_meas_ref h_dist a_ℓ]

/-
Helper lemma: DPO loss is equal when oracle values are equal.
-/
lemma dpo_loss_eq_of_oracle_eq {Strings A Y : Type*} [PseudoMetricSpace Y]
    {π π_ref : Policy Strings A} {fstar : Strings → Y} {β : ℝ}
    (h_meas_π : DPO.OracleMeasurable π fstar)
    (h_meas_ref : DPO.OracleMeasurable π_ref fstar)
    {x x' : Strings} (h_dist : dist (fstar x) (fstar x') = 0)
    (a_w a_ℓ : A) :
    DPOLossPointwise π π_ref β x a_w a_ℓ = DPOLossPointwise π π_ref β x' a_w a_ℓ := by
  unfold DPOLossPointwise
  rw [dpo_logit_eq_of_oracle_eq h_meas_π h_meas_ref h_dist a_w a_ℓ]

/-
Theorem: Exact DPO Equivalence

If distortion is exactly zero (oracle values are preserved by summarization),
and policies and pair generators are oracle-measurable, then the DPO loss
on summaries equals the DPO loss on original documents for any oracle-measurable policy.

This implies that the argmin over oracle-measurable policies is the same.
-/

/-- Oracle-measurable policy argmin: minimizers among oracle-measurable policies -/
def OracleMeasurablePolicyArgmin {Strings A Y : Type*} [PseudoMetricSpace Y]
    (loss : Policy Strings A → ℝ) (fstar : Strings → Y) : Set (Policy Strings A) :=
  {π | DPO.OracleMeasurable π fstar ∧ ∀ π', DPO.OracleMeasurable π' fstar → loss π ≤ loss π'}

/-- Two loss functions have the same oracle-measurable argmin -/
def SameOracleMeasurableArgmin {Strings A Y : Type*} [PseudoMetricSpace Y]
    (loss₁ loss₂ : Policy Strings A → ℝ) (fstar : Strings → Y) : Prop :=
  OracleMeasurablePolicyArgmin loss₁ fstar = OracleMeasurablePolicyArgmin loss₂ fstar

theorem dpo_exact {Strings A Y : Type*} [Monoid Strings] [PseudoMetricSpace Y]
    (fstar : Strings → Y)
    (π_ref : Policy Strings A)
    (gen : PairGenerator Strings A)
    (μ_X μ_Z : PMF Strings)
    (β : ℝ)
    -- Zero distortion: summaries have same oracle value as originals
    (h_oracle_eq : ∀ z x, z ∈ (μ_Z).support → x ∈ (μ_X).support → dist (fstar z) (fstar x) = 0)
    -- Policies and generators are oracle-measurable
    (h_meas_ref : DPO.OracleMeasurable π_ref fstar)
    (h_pair : OracleIndexedPairGen gen fstar)
    -- The distributions μ_X and μ_Z are related by the summarization (same mass on equivalent oracle classes)
    (h_dist_eq : ∀ π, DPO.OracleMeasurable π fstar →
        ExpectedDPOLoss π π_ref β μ_X gen = ExpectedDPOLoss π π_ref β μ_Z gen) :
    SameOracleMeasurableArgmin
      (fun π => ExpectedDPOLoss π π_ref β μ_X gen)
      (fun π => ExpectedDPOLoss π π_ref β μ_Z gen)
      fstar := by
  unfold SameOracleMeasurableArgmin OracleMeasurablePolicyArgmin
  ext π
  constructor
  · intro ⟨h_meas_π, h_min⟩
    constructor
    · exact h_meas_π
    · intro π' h_meas_π'
      rw [← h_dist_eq π h_meas_π, ← h_dist_eq π' h_meas_π']
      exact h_min π' h_meas_π'
  · intro ⟨h_meas_π, h_min⟩
    constructor
    · exact h_meas_π
    · intro π' h_meas_π'
      rw [h_dist_eq π h_meas_π, h_dist_eq π' h_meas_π']
      exact h_min π' h_meas_π'

/-
Helper lemma: Sigmoid is 1-Lipschitz.
The derivative σ'(t) = σ(t)(1-σ(t)) ≤ 1/4 < 1.
-/
lemma sigmoid_lipschitz : LipschitzWith 1 Real.sigmoid :=
  lipschitzWith_of_nnnorm_deriv_le Real.differentiable_sigmoid <| fun x => by
    rw [Real.deriv_sigmoid]
    -- Need to show ‖sigmoid x * (1 - sigmoid x)‖₊ ≤ 1
    have h1 : 0 ≤ Real.sigmoid x := Real.sigmoid_nonneg x
    have h2 : Real.sigmoid x ≤ 1 := Real.sigmoid_le_one x
    have h3 : 0 ≤ 1 - Real.sigmoid x := by linarith
    have h_prod_nonneg : 0 ≤ Real.sigmoid x * (1 - Real.sigmoid x) := mul_nonneg h1 h3
    have h_bound : Real.sigmoid x * (1 - Real.sigmoid x) ≤ 1 := by
      -- Maximum of x(1-x) on [0,1] is 1/4 at x=1/2
      have h4 : Real.sigmoid x * (1 - Real.sigmoid x) ≤ 1/4 := by
        nlinarith [sq_nonneg (Real.sigmoid x - 1/2)]
      linarith
    rw [Real.nnnorm_of_nonneg h_prod_nonneg]
    exact h_bound

/-
Helper lemma: -log ∘ σ is 1-Lipschitz.
The derivative is -(1 - σ(t)) which has absolute value < 1.
-/
lemma neg_log_sigmoid_lipschitz : LipschitzWith 1 (fun t => -Real.log (Real.sigmoid t)) := by
  -- Use that -log(σ(t)) = log(1 + exp(-t)) which is a standard function
  -- Its derivative is -σ'(t)/σ(t) = -(1-σ(t))
  -- Since 0 < σ(t) < 1, we have 0 < 1 - σ(t) < 1
  have h_diff : Differentiable ℝ (fun t => -Real.log (Real.sigmoid t)) := by
    apply Differentiable.neg
    apply Differentiable.log Real.differentiable_sigmoid
    intro x
    exact ne_of_gt (Real.sigmoid_pos x)
  apply lipschitzWith_of_nnnorm_deriv_le h_diff
  intro x
  -- The derivative of -log(σ(x)) is -(σ'(x)/σ(x)) = -(σ(x)(1-σ(x))/σ(x)) = -(1-σ(x))
  have h_deriv : deriv (fun t => -Real.log (Real.sigmoid t)) x = -(1 - Real.sigmoid x) := by
    rw [deriv_neg]
    rw [deriv.log (Real.differentiable_sigmoid x) (ne_of_gt (Real.sigmoid_pos x))]
    rw [Real.deriv_sigmoid]
    field_simp [ne_of_gt (Real.sigmoid_pos x)]
  rw [h_deriv]
  have h1 : 0 < Real.sigmoid x := Real.sigmoid_pos x
  have h2 : Real.sigmoid x < 1 := Real.sigmoid_lt_one x
  have h3 : 0 < 1 - Real.sigmoid x := by linarith
  have h4 : 1 - Real.sigmoid x < 1 := by linarith
  rw [abs_neg, Real.nnnorm_of_nonneg (le_of_lt h3)]
  exact le_of_lt h4

/-
Helper lemma: DPO logit difference is bounded by Lipschitz constant on log-ratios.
|Λ(x) - Λ(x')| ≤ 2|β|L_π · d_Y(f*(x), f*(x'))
-/
lemma dpo_logit_lipschitz {Strings A Y : Type*} [PseudoMetricSpace Y]
    {π π_ref : Policy Strings A} {fstar : Strings → Y} {β : ℝ} {L_π : ℝ≥0}
    (h_lip : PolicyLipschitz π π_ref fstar L_π) (a_w a_ℓ : A) :
    ∀ x x', |DPOLogit π π_ref β x a_w a_ℓ - DPOLogit π π_ref β x' a_w a_ℓ| ≤
            2 * |β| * L_π * dist (fstar x) (fstar x') := by
  intro x x'
  unfold DPOLogit
  have h1 := h_lip a_w x x'
  have h2 := h_lip a_ℓ x x'
  calc |β * (LogRatio π π_ref x a_w - LogRatio π π_ref x a_ℓ) -
        β * (LogRatio π π_ref x' a_w - LogRatio π π_ref x' a_ℓ)|
      = |β * ((LogRatio π π_ref x a_w - LogRatio π π_ref x' a_w) -
               (LogRatio π π_ref x a_ℓ - LogRatio π π_ref x' a_ℓ))| := by ring_nf
    _ = |β| * |(LogRatio π π_ref x a_w - LogRatio π π_ref x' a_w) -
               (LogRatio π π_ref x a_ℓ - LogRatio π π_ref x' a_ℓ)| := abs_mul _ _
    _ ≤ |β| * (|LogRatio π π_ref x a_w - LogRatio π π_ref x' a_w| +
               |LogRatio π π_ref x a_ℓ - LogRatio π π_ref x' a_ℓ|) := by
        gcongr
        exact abs_sub_abs_le_abs_sub _ _
    _ ≤ |β| * (L_π * dist (fstar x) (fstar x') + L_π * dist (fstar x) (fstar x')) := by
        gcongr
    _ = 2 * |β| * L_π * dist (fstar x) (fstar x') := by ring

/-
Helper lemma: Pointwise DPO loss difference is bounded.
|L(x) - L(x')| ≤ 2|β|L_π · d_Y(f*(x), f*(x'))
-/
lemma dpo_loss_pointwise_lipschitz {Strings A Y : Type*} [PseudoMetricSpace Y]
    {π π_ref : Policy Strings A} {fstar : Strings → Y} {β : ℝ} {L_π : ℝ≥0}
    (h_lip : PolicyLipschitz π π_ref fstar L_π) (a_w a_ℓ : A) :
    ∀ x x', |DPOLossPointwise π π_ref β x a_w a_ℓ - DPOLossPointwise π π_ref β x' a_w a_ℓ| ≤
            2 * |β| * L_π * dist (fstar x) (fstar x') := by
  intro x x'
  unfold DPOLossPointwise
  have h_logit := dpo_logit_lipschitz h_lip a_w a_ℓ x x'
  -- -log(σ(Λ)) is 1-Lipschitz in Λ
  have h_comp : |(-Real.log (Real.sigmoid (DPOLogit π π_ref β x a_w a_ℓ))) -
                 (-Real.log (Real.sigmoid (DPOLogit π π_ref β x' a_w a_ℓ)))| ≤
                |DPOLogit π π_ref β x a_w a_ℓ - DPOLogit π π_ref β x' a_w a_ℓ| := by
    have := neg_log_sigmoid_lipschitz.dist_le_mul
      (DPOLogit π π_ref β x a_w a_ℓ) (DPOLogit π π_ref β x' a_w a_ℓ)
    simp only [NNReal.coe_one, one_mul, Real.dist_eq] at this
    exact this
  calc |(-Real.log (Real.sigmoid (DPOLogit π π_ref β x a_w a_ℓ))) -
        (-Real.log (Real.sigmoid (DPOLogit π π_ref β x' a_w a_ℓ)))|
    ≤ |DPOLogit π π_ref β x a_w a_ℓ - DPOLogit π π_ref β x' a_w a_ℓ| := h_comp
    _ ≤ 2 * |β| * L_π * dist (fstar x) (fstar x') := h_logit

/-
Theorem: DPO Gap Bound

With Lipschitz conditions on policies, the DPO loss gap is bounded by expected distortion.
-/
theorem dpo_gap {Strings A Y : Type*} [Monoid Strings] [PseudoMetricSpace Y]
    (fstar : Strings → Y)
    (π π_ref : Policy Strings A)
    (gen : PairGenerator Strings A)
    (μ_X μ_Z : PMF Strings)
    (β : ℝ) (L_π : ℝ≥0)
    (Δ_R : ℝ)
    (h_m_π : DPO.OracleMeasurable π fstar)
    (h_m_ref : DPO.OracleMeasurable π_ref fstar)
    (h_lip : PolicyLipschitz π π_ref fstar L_π)
    (h_Δ : Δ_R = ∑' z, ∑' x, (μ_Z z).toReal * (μ_X x).toReal * dist (fstar z) (fstar x)) :
    |ExpectedDPOLoss π π_ref β μ_X gen - ExpectedDPOLoss π π_ref β μ_Z gen| ≤
    2 * |β| * L_π * Δ_R := by
  -- Proof sketch:
  -- 1. |σ(Λ_X) - σ(Λ_Z)| ≤ |Λ_X - Λ_Z| (sigmoid is 1-Lipschitz)
  -- 2. |Λ_X - Λ_Z| ≤ 2βL_π · d_Y(f*(X), f*(Z)) (Lipschitz on log-ratios)
  -- 3. Take expectation
  sorry

end DPO

-- =============================================================================
-- Section 10: Counterexample - Stability is Substantive
-- =============================================================================

/-
This section formalizes the counterexample from Section 10 of the paper.
It constructs a "bad" summarizer g_bad that:
1. Satisfies L1 on all fresh inputs (b ≠ POS, NEG)
2. Fails L3 because g_bad(POS) = NEG, flipping the oracle value

This demonstrates that L3 (on-range idempotence) is a substantive requirement
that cannot be derived from L1 and L2 alone.
-/

section Counterexample

-- For the counterexample, we work with a specific oracle space (Real numbers)
-- and string type with distinguished elements POS and NEG.

variable {Strings' : Type*} [DecidableEq Strings'] [Monoid Strings']

-- Special tokens (axiomatized for the counterexample)
variable (POS NEG : Strings')
variable (fstar' : Strings' → ℝ)

-- Axioms about the tokens
variable (h_pos : fstar' POS = 1)
variable (h_neg : fstar' NEG = 0)
variable (h_distinct : POS ≠ NEG)
-- Binary oracle: fstar only takes values 0 or 1 (standard for classification tasks)
variable (h_binary : ∀ x, fstar' x = 0 ∨ fstar' x = 1)

/-
The "bad" summarizer:
- If input is POS or NEG, return NEG (this breaks idempotence on POS)
- Otherwise, return POS if oracle = 1, else NEG
-/
noncomputable def g_bad (x : Strings') : Strings' :=
  if x = POS ∨ x = NEG then NEG
  else if fstar' x = 1 then POS
  else NEG

-- Key property: g_bad maps POS to NEG, which breaks idempotence
lemma g_bad_on_POS : g_bad POS NEG fstar' POS = NEG := by
  simp only [g_bad, eq_self_iff_true, true_or, ite_true]

lemma g_bad_on_NEG : g_bad POS NEG fstar' NEG = NEG := by
  simp only [g_bad, eq_self_iff_true, or_true, ite_true]

lemma g_bad_on_fresh (b : Strings') (h_ne_pos : b ≠ POS) (h_ne_neg : b ≠ NEG) :
    g_bad POS NEG fstar' b = if fstar' b = 1 then POS else NEG := by
  simp only [g_bad, h_ne_pos, h_ne_neg, or_self, ite_false]

-- Distortion function for this example (using real distance)
def D_real (fstar'' : Strings' → ℝ) (z x : Strings') : ℝ :=
  |fstar'' z - fstar'' x|

-- Main theorem part 1: g_bad preserves oracle on "fresh" inputs
theorem g_bad_preserves_fresh (b : Strings')
    (h_ne_pos : b ≠ POS) (h_ne_neg : b ≠ NEG) :
    D_real fstar' (g_bad POS NEG fstar' b) b = 0 := by
  rw [g_bad_on_fresh POS NEG fstar' b h_ne_pos h_ne_neg]
  simp only [D_real]
  cases h_binary b with
  | inl h0 =>
    simp only [h0, ite_false, h_neg, sub_zero, abs_zero]
  | inr h1 =>
    simp only [h1, ite_true, h_pos, sub_self, abs_zero]

-- Main theorem part 2: g_bad breaks on POS (which is in range)
theorem g_bad_breaks_on_range :
    D_real fstar' (g_bad POS NEG fstar' POS) POS = 1 := by
  rw [g_bad_on_POS]
  simp only [D_real, h_neg, h_pos, zero_sub, abs_neg, abs_one]

-- POS is in the range of g_bad (witnessed by any b with fstar b = 1 and b ≠ POS, NEG)
lemma POS_in_range_g_bad (b : Strings') (h_ne_pos : b ≠ POS) (h_ne_neg : b ≠ NEG)
    (hb : fstar' b = 1) :
    g_bad POS NEG fstar' b = POS := by
  rw [g_bad_on_fresh POS NEG fstar' b h_ne_pos h_ne_neg]
  simp only [hb, ite_true]

-- Conclusion: L3 fails for g_bad because re-summarizing POS flips to NEG
theorem L3_fails_for_g_bad :
    D_real fstar' (g_bad POS NEG fstar' POS) POS > 0 := by
  rw [g_bad_breaks_on_range POS NEG fstar' h_pos h_neg]
  norm_num

/-
Combined statement matching the LaTeX (Section 10, Example 10.1):
1. For all b ≠ POS, NEG: distortion is 0 (L1 holds on fresh inputs)
2. For POS: distortion > 0 (L3 fails because POS is in range but g_bad(POS) = NEG)
-/
theorem stability_counterexample :
    (∀ b : Strings', b ≠ POS → b ≠ NEG → D_real fstar' (g_bad POS NEG fstar' b) b = 0) ∧
    D_real fstar' (g_bad POS NEG fstar' POS) POS > 0 :=
  ⟨g_bad_preserves_fresh POS NEG fstar' h_pos h_neg h_binary,
   L3_fails_for_g_bad POS NEG fstar' h_pos h_neg⟩

end Counterexample

-- =============================================================================
-- Section 9: Existence Results
-- =============================================================================

/-
This section formalizes the existence results from Section 9 of the paper.
It proves that oracle-preserving summarizers exist in two ways:
1. Canonical Representative: Using choice to pick fiber representatives
2. Compact Encoding: Given an encoding that inverts fstar
-/

section ExistenceResults

variable {Strings : Type*} [Monoid Strings]
variable {Y : Type*} [PseudoMetricSpace Y]

/-
Canonical Representative Construction.
Key idea: for each oracle value y in the image of fstar, pick a canonical string that maps to y.
We use Classical.choose to select a representative from each fiber.
-/

-- InImage predicate: y is in the image of fstar
def InImage (fstar : Strings → Y) (y : Y) : Prop := ∃ x, fstar x = y

-- Every fstar(x) is in the image
lemma fstar_in_image (fstar : Strings → Y) (x : Strings) : InImage fstar (fstar x) :=
  ⟨x, rfl⟩

-- Representative function: given y in image, pick a preimage
noncomputable def rep (fstar : Strings → Y) (y : Y) (hy : InImage fstar y) : Strings :=
  hy.choose

-- The representative maps to y
lemma fstar_rep_eq (fstar : Strings → Y) (y : Y) (hy : InImage fstar y) :
    fstar (rep fstar y hy) = y :=
  hy.choose_spec

-- Canonical summarizer: g_can(x) = rep(fstar(x))
noncomputable def g_can (fstar : Strings → Y) (x : Strings) : Strings :=
  rep fstar (fstar x) (fstar_in_image fstar x)

-- Key property: fstar(g_can(x)) = fstar(x)
lemma fstar_g_can_eq (fstar : Strings → Y) (x : Strings) :
    fstar (g_can fstar x) = fstar x :=
  fstar_rep_eq fstar (fstar x) (fstar_in_image fstar x)

-- Crucial lemma: g_can only depends on fstar(x), not on x
-- When fstar(z) = fstar(x), we have g_can(z) = g_can(x)
-- This uses proof irrelevance: InImage fstar (fstar z) = InImage fstar (fstar x)
-- when fstar z = fstar x, so Classical.choose gives the same result.
lemma g_can_eq_of_fstar_eq (fstar : Strings → Y) (x z : Strings) (h : fstar z = fstar x) :
    g_can fstar z = g_can fstar x := by
  unfold g_can rep
  -- InImage fstar (fstar z) and InImage fstar (fstar x) are the same Prop
  -- since fstar z = fstar x, so by proof irrelevance, choose gives same result
  congr 1
  exact h

/-
Proposition 9.1: Canonical Representative Theorem

There exists a summarizer g : Strings → Strings such that:
1. Oracle preservation: D(f*(g(x)), f*(x)) = 0 for all x
2. Idempotence on range: g(z) = z for all z in range(g)
-/
theorem canonical_rep_exists (fstar : Strings → Y) :
    ∃ g : Strings → Strings,
      (∀ x, D fstar (g x) x = 0) ∧
      (∀ z, (∃ x, g x = z) → g z = z) := by
  use g_can fstar
  constructor
  -- Part 1: Oracle preservation
  · intro x
    unfold D
    rw [fstar_g_can_eq]
    exact dist_self (fstar x)
  -- Part 2: Idempotence on range
  · intro z ⟨x, hx⟩
    -- z = g_can(x), so fstar(z) = fstar(x)
    have hz : fstar z = fstar x := by rw [← hx]; exact fstar_g_can_eq fstar x
    -- By g_can_eq_of_fstar_eq, g_can(z) = g_can(x) = z
    rw [g_can_eq_of_fstar_eq fstar x z hz, hx]

/-
Proposition 9.2: Compact Encoding

Given an encoding enc : Y → Strings that inverts fstar (i.e., fstar(enc(y)) = y),
we can construct an oracle-preserving summarizer g_enc(x) := enc(fstar(x)).
-/
theorem compact_encoding_exists (fstar : Strings → Y)
    (enc : Y → Strings)
    (h_inv : ∀ y, fstar (enc y) = y) :
    ∃ g : Strings → Strings,
      (∀ x, D fstar (g x) x = 0) ∧
      (∀ z, (∃ x, g x = z) → g z = z) := by
  -- Define g_enc(x) := enc(fstar(x))
  use fun x => enc (fstar x)
  constructor
  -- Part 1: Oracle preservation
  · intro x
    unfold D
    rw [h_inv]
    exact dist_self (fstar x)
  -- Part 2: Idempotence on range
  · intro z ⟨x, hx⟩
    -- z = enc(fstar(x))
    -- g_enc(z) = enc(fstar(z)) = enc(fstar(enc(fstar(x)))) = enc(fstar(x)) = z
    calc enc (fstar z)
      = enc (fstar (enc (fstar x))) := by rw [← hx]
      _ = enc (fstar x) := by rw [h_inv]
      _ = z := hx.symm

end ExistenceResults