/- 
FormalProofs/OPT/SerflingAudit.lean

Serfling-style (without-replacement) concentration tools for chunk/leaf audits.

This file currently provides the key *measure-theoretic building block* we need to
get Serfling/Azuma style bounds cleanly in Mathlib:

* a **conditional Hoeffding lemma** turning
  - boundedness `X ∈ Icc a b` and
  - conditional mean zero `𝔼[X | m] = 0`
  into
  - `HasCondSubgaussianMGF m X` (Azuma-ready).

This is the missing glue between:
* chunk/leaf sampling viewed as a filtration-adapted process, and
* Mathlib's `measure_sum_ge_le_of_HasCondSubgaussianMGF` (Azuma-Hoeffding).

This file also includes an explicit random-permutation/simple-random-sample
without-replacement model and a concrete Azuma tail theorem for the resulting
centered increment process.
-/

import Mathlib.Probability.Moments.SubGaussian
import Mathlib.Probability.Kernel.Condexp

set_option linter.mathlibStandardSet false

open scoped Real NNReal
open MeasureTheory ProbabilityTheory

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace OPT

/-!
## Conditional Hoeffding Lemma (Bounded + CondExp = 0 ⇒ Cond-SubGaussian)

Mathlib has:
* Hoeffding's lemma (`hasSubgaussianMGF_of_mem_Icc_of_integral_eq_zero`) for a *single*
  probability measure.
* Azuma-Hoeffding (`measure_sum_ge_le_of_HasCondSubgaussianMGF`) for martingale differences,
  but it expects `HasCondSubgaussianMGF`.

The lemma below is the bridge: it upgrades Hoeffding's lemma to the conditional setting
by applying it fiberwise to the conditional measures generated by `condExpKernel`.
-/

section ConditionalHoeffding

variable {Ω : Type*}
variable {m mΩ : MeasurableSpace Ω} {hm : m ≤ mΩ}
variable [StandardBorelSpace Ω]
variable {μ : Measure Ω} [IsFiniteMeasure μ]

/-- **Conditional Hoeffding lemma**.

If `X` is (a.e.) bounded in `[a,b]` and has conditional mean zero given `m`,
then `X` is conditionally sub-Gaussian with parameter `((b-a)/2)^2`, i.e.
`HasCondSubgaussianMGF m hm X ((‖b-a‖₊/2)^2) μ`.

This is the main tool needed to feed bounded martingale differences into Azuma. -/
lemma hasCondSubgaussianMGF_of_mem_Icc_of_condExp_eq_zero
    {X : Ω → ℝ} {a b : ℝ}
    (hX : Measurable X)
    (hb : ∀ᵐ ω ∂μ, X ω ∈ Set.Icc a b)
    (hcond : μ[X|m] =ᵐ[μ.trim hm] 0) :
    HasCondSubgaussianMGF m hm X ((‖b - a‖₊ / 2) ^ 2) μ := by
  have hX_ae : AEMeasurable X μ := hX.aemeasurable
  -- Unfolding `HasCondSubgaussianMGF` reduces this to a `Kernel.HasSubgaussianMGF` goal.
  -- We build it directly: integrability is global (since `condExpKernel ∘ trim = μ`),
  -- while the mgf bound is proved fiberwise by Hoeffding's lemma.
  refine (ProbabilityTheory.Kernel.HasSubgaussianMGF.mk ?_ ?_)
  · intro t
    -- Integrability under `(condExpKernel ∘ μ.trim hm)` is integrability under `μ`.
    simpa [HasCondSubgaussianMGF, condExpKernel_comp_trim (μ := μ) hm] using
      (ProbabilityTheory.integrable_exp_mul_of_mem_Icc (μ := μ) (X := X) (a := a) (b := b) (t := t)
        hX_ae hb)
  · -- mgf bound fiberwise (conditional measures)
    have hb_comp : ∀ᵐ ω ∂(condExpKernel μ m ∘ₘ μ.trim hm), X ω ∈ Set.Icc a b := by
      simpa [condExpKernel_comp_trim (μ := μ) hm] using hb
    have hb_fiber :
        ∀ᵐ ω' ∂(μ.trim hm), ∀ᵐ ω ∂condExpKernel μ m ω', X ω ∈ Set.Icc a b :=
      Measure.ae_ae_of_ae_comp hb_comp
    have hint : Integrable X μ := Integrable.of_mem_Icc a b hX_ae hb
    have hce :=
      condExp_ae_eq_trim_integral_condExpKernel (μ := μ) (m := m) hm hint
    have hzero_int :
        ∀ᵐ ω' ∂(μ.trim hm), (∫ ω, X ω ∂condExpKernel μ m ω') = 0 := by
      filter_upwards [hcond, hce] with ω' h0 hce'
      -- h0 : μ[X|m] ω' = 0, hce' : μ[X|m] ω' = integral
      simpa [hce'] using h0
    filter_upwards [hb_fiber, hzero_int] with ω' hbω' hInt0
    intro t
    -- Each conditional measure is a probability measure (Markov kernel).
    haveI : IsProbabilityMeasure (condExpKernel μ m ω') := by infer_instance
    have hX_ae' : AEMeasurable X (condExpKernel μ m ω') := hX.aemeasurable
    -- Apply Hoeffding lemma under the conditional measure.
    have hsub :
        HasSubgaussianMGF X ((‖b - a‖₊ / 2) ^ 2) (condExpKernel μ m ω') :=
      hasSubgaussianMGF_of_mem_Icc_of_integral_eq_zero (μ := condExpKernel μ m ω')
        (X := X) (a := a) (b := b) hX_ae' hbω' hInt0
    exact hsub.mgf_le t

end ConditionalHoeffding

/-!
## Azuma From Bounded Martingale Differences

Mathlib's Azuma-Hoeffding lemma is stated in terms of `HasCondSubgaussianMGF`.
Using the conditional Hoeffding lemma above, we can discharge that hypothesis
from the *more concrete* assumptions typically used in sampling arguments:

* each increment is bounded in an interval `Icc a b`,
* its conditional expectation given the previous σ-algebra is zero.
-/

section AzumaFromBounds

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} [StandardBorelSpace Ω]
variable {μ : Measure Ω} [IsZeroOrProbabilityMeasure μ]
variable {ℱ : Filtration ℕ mΩ}
variable {Y : ℕ → Ω → ℝ}

/-- Azuma-Hoeffding from bounded increments and conditional mean-zero.

This is a convenience wrapper around
`ProbabilityTheory.measure_sum_ge_le_of_HasCondSubgaussianMGF` using
`hasCondSubgaussianMGF_of_mem_Icc_of_condExp_eq_zero` to build the required
conditional sub-Gaussian hypotheses.

The result is stated for the one-sided tail `P(ε ≤ ∑ Y_i)`. -/
theorem azuma_hoeffding_of_mem_Icc_of_condExp_eq_zero
    (a b : ℕ → ℝ)
    (h_meas : ∀ i, Measurable (Y i))
    (hY0 : Y 0 = 0)
    (n : ℕ)
    (h_adapted : Adapted ℱ Y)
    (h_bound : ∀ i, i < n - 1 → ∀ᵐ ω ∂μ, Y (i + 1) ω ∈ Set.Icc (a (i + 1)) (b (i + 1)))
    (h_cond : ∀ i, i < n - 1 → μ[Y (i + 1)|ℱ i] =ᵐ[μ] 0)
    {ε : ℝ} (hε : 0 ≤ ε) :
    μ.real {ω | ε ≤ ∑ i ∈ Finset.range n, Y i ω}
      ≤ Real.exp
        (-ε ^ 2 /
          (2 * ∑ i ∈ Finset.range n, (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) := by
  classical
  -- Define the variance proxy sequence `cY`.
  let cY : ℕ → ℝ≥0 := fun i => if i = 0 then 0 else (‖b i - a i‖₊ / 2) ^ 2

  -- Base case: Y 0 = 0 is sub-Gaussian with parameter 0, hence also with parameter cY 0.
  have h0 : HasSubgaussianMGF (Y 0) (cY 0) μ := by
    simp [cY, hY0]

  -- Conditional sub-Gaussianity for each increment from boundedness + conditional mean zero.
  have h_subG :
      ∀ i < n - 1, HasCondSubgaussianMGF (ℱ i) (ℱ.le i) (Y (i + 1)) (cY (i + 1)) μ := by
    intro i hi
    -- Convert the conditional mean-zero hypothesis from `μ`-a.e. to `μ.trim`-a.e.
    have hcond_trim :
        μ[Y (i + 1)|ℱ i] =ᵐ[μ.trim (ℱ.le i)] 0 := by
      have hsm : StronglyMeasurable[ℱ i] (μ[Y (i + 1)|ℱ i]) :=
        stronglyMeasurable_condExp (μ := μ) (m := ℱ i) (f := Y (i + 1))
      have hsm0 : StronglyMeasurable[ℱ i] (fun _ : Ω => (0 : ℝ)) := stronglyMeasurable_const
      -- `ae_eq_trim_iff` gives equivalence since both sides are strongly measurable.
      exact (hsm.ae_eq_trim_iff (μ := μ) (hm := ℱ.le i) hsm0).mpr (h_cond i hi)
    -- Apply conditional Hoeffding with the interval bounds.
    refine hasCondSubgaussianMGF_of_mem_Icc_of_condExp_eq_zero
      (m := ℱ i) (mΩ := mΩ) (hm := ℱ.le i) (μ := μ) (X := Y (i + 1))
      (a := a (i + 1)) (b := b (i + 1)) (h_meas (i + 1)) (h_bound i hi) hcond_trim

  -- Apply Mathlib Azuma-Hoeffding.
  have h_azuma :=
    ProbabilityTheory.measure_sum_ge_le_of_HasCondSubgaussianMGF
      (μ := μ) (ℱ := ℱ) (Y := Y) (cY := cY) h_adapted h0 n h_subG hε
  -- Unfold `cY`.
  -- Also rewrite the bound back into the explicit `Finset.range` sum form.
  simpa [cY] using h_azuma

/-!
### Two-sided Tail (Absolute Value)

The one-sided Azuma bound controls `P(ε ≤ ∑ Yᵢ)`. For audit-style statements we often want the
two-sided deviation `P(|∑ Yᵢ| ≥ ε)`, which follows by applying the one-sided bound to both
`Y` and `-Y` and using a union bound.
-/

theorem azuma_hoeffding_abs_of_mem_Icc_of_condExp_eq_zero
    (a b : ℕ → ℝ)
    (h_meas : ∀ i, Measurable (Y i))
    (hY0 : Y 0 = 0)
    (n : ℕ)
    (h_adapted : Adapted ℱ Y)
    (h_bound : ∀ i, i < n - 1 → ∀ᵐ ω ∂μ, Y (i + 1) ω ∈ Set.Icc (a (i + 1)) (b (i + 1)))
    (h_cond : ∀ i, i < n - 1 → μ[Y (i + 1)|ℱ i] =ᵐ[μ] 0)
    {ε : ℝ} (hε : 0 ≤ ε) :
    μ.real {ω | ε ≤ |∑ i ∈ Finset.range n, Y i ω|}
      ≤ 2 * Real.exp
        (-ε ^ 2 /
          (2 * ∑ i ∈ Finset.range n, (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) := by
  classical
  -- Abbreviate the partial sum.
  let S : Ω → ℝ := fun ω => ∑ i ∈ Finset.range n, Y i ω

  -- `ε ≤ |S|` iff `ε ≤ S` or `ε ≤ -S`.
  have hset₁ :
      {ω | ε ≤ |S ω|} =
        {ω | ε ≤ S ω} ∪ {ω | ε ≤ -S ω} := by
    ext ω
    simp [S, le_abs] -- `le_abs : ε ≤ |x| ↔ ε ≤ x ∨ ε ≤ -x`

  -- Rewrite `-S` as the sum of `-Y`.
  have hset₂ :
      {ω | ε ≤ -S ω} = {ω | ε ≤ ∑ i ∈ Finset.range n, (-Y i) ω} := by
    ext ω
    simp [S, Finset.sum_neg_distrib]

  -- One-sided bound for `Y`.
  have h_pos :
      μ.real {ω | ε ≤ S ω}
        ≤ Real.exp
          (-ε ^ 2 /
            (2 * ∑ i ∈ Finset.range n,
              (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) :=
    (azuma_hoeffding_of_mem_Icc_of_condExp_eq_zero
      (a := a) (b := b) (h_meas := h_meas) (hY0 := hY0) (n := n)
      (h_adapted := h_adapted) (h_bound := h_bound) (h_cond := h_cond) (hε := hε))

  -- One-sided bound for `-Y`.
  have h_meas_neg : ∀ i, Measurable (-Y i) := fun i => (h_meas i).neg
  have hY0_neg : (-Y 0) = 0 := by simp [hY0]
  have h_adapted_neg : Adapted ℱ (-Y) := fun i => (h_adapted i).neg
  have h_bound_neg :
      ∀ i, i < n - 1 → ∀ᵐ ω ∂μ, (-Y (i + 1)) ω ∈ Set.Icc (-b (i + 1)) (-a (i + 1)) := by
    intro i hi
    filter_upwards [h_bound i hi] with ω hω
    rcases hω with ⟨hlo, hhi⟩
    constructor
    · -- `Y ≤ b` implies `-b ≤ -Y`
      exact neg_le_neg hhi
    · -- `a ≤ Y` implies `-Y ≤ -a`
      exact neg_le_neg hlo
  have h_cond_neg : ∀ i, i < n - 1 → μ[(-Y (i + 1))|ℱ i] =ᵐ[μ] 0 := by
    intro i hi
    -- `condExp` is linear.
    filter_upwards [MeasureTheory.condExp_neg (μ := μ) (f := Y (i + 1)) (m := ℱ i),
      h_cond i hi] with ω hneg hzero
    -- hneg : μ[-Y|ℱ i] ω = - μ[Y|ℱ i] ω
    -- hzero : μ[Y|ℱ i] ω = 0
    simp [hneg, hzero]
  have h_neg :
      μ.real {ω | ε ≤ ∑ i ∈ Finset.range n, (-Y i) ω}
        ≤ Real.exp
          (-ε ^ 2 /
            (2 * ∑ i ∈ Finset.range n,
              (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) := by
    -- Apply the one-sided bound and simplify the parameter.
    have h' :=
      (azuma_hoeffding_of_mem_Icc_of_condExp_eq_zero
        (a := fun i => -b i) (b := fun i => -a i) (h_meas := h_meas_neg) (hY0 := hY0_neg)
        (n := n) (h_adapted := h_adapted_neg) (h_bound := h_bound_neg) (h_cond := h_cond_neg)
        (hε := hε))
    -- `‖(-a)-(-b)‖₊ = ‖b-a‖₊`.
    simpa [sub_eq_add_neg, add_comm, add_left_comm, add_assoc] using h'

  -- Union bound + factor out `2 * exp(...)`.
  have hunion :
      μ.real ({ω | ε ≤ S ω} ∪ {ω | ε ≤ ∑ i ∈ Finset.range n, (-Y i) ω})
        ≤ Real.exp
            (-ε ^ 2 /
              (2 * ∑ i ∈ Finset.range n,
                (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) +
          Real.exp
            (-ε ^ 2 /
              (2 * ∑ i ∈ Finset.range n,
                (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) := by
    have := MeasureTheory.measureReal_union_le (μ := μ)
      {ω | ε ≤ S ω} {ω | ε ≤ ∑ i ∈ Finset.range n, (-Y i) ω}
    exact this.trans (by gcongr)

  have hunion' :
      μ.real {ω | ε ≤ |S ω|}
        ≤ Real.exp
            (-ε ^ 2 /
              (2 * ∑ i ∈ Finset.range n,
                (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) +
          Real.exp
            (-ε ^ 2 /
              (2 * ∑ i ∈ Finset.range n,
                (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) := by
    simpa [hset₁, hset₂, S] using hunion

  -- Factor out `2 * exp(...)`.
  calc
    μ.real {ω | ε ≤ |S ω|}
        ≤ Real.exp
            (-ε ^ 2 /
              (2 * ∑ i ∈ Finset.range n,
                (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) +
          Real.exp
            (-ε ^ 2 /
              (2 * ∑ i ∈ Finset.range n,
                (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) := hunion'
    _ = 2 * Real.exp
          (-ε ^ 2 /
            (2 * ∑ i ∈ Finset.range n,
              (if i = 0 then (0 : ℝ≥0) else (‖b i - a i‖₊ / 2) ^ 2))) := by
          ring

end AzumaFromBounds

/-!
## Explicit Random-Permutation Without-Replacement Instantiation

This section encodes a concrete WOR design by exposing a random permutation
`perm : Ω → Equiv.Perm (Fin N)` and taking the first `m` positions as draws.
We discharge:

1. no-replacement (`draw` is injective for every `ω`), and
2. bounded increment hypotheses for the centered sampled values.

The conditional-mean-zero hypothesis is supplied at theorem use-site (as a
martingale-difference condition relative to a chosen filtration).
-/

section RandomPermutationInstantiation

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} [StandardBorelSpace Ω]

/-- Concrete finite-population WOR design via a random permutation. -/
structure RandomPermutationWOR (Ω : Type*) where
  N : ℕ
  m : ℕ
  hN_pos : 0 < N
  hm_le : m ≤ N
  perm : Ω → Equiv.Perm (Fin N)
  leaf_value : Fin N → ℝ
  lower : ℝ
  upper : ℝ
  h_leaf_value_bounds : ∀ u : Fin N, leaf_value u ∈ Set.Icc lower upper

namespace RandomPermutationWOR

variable (model : RandomPermutationWOR Ω)

/-- Draw the `i`-th sampled leaf by taking the `i`-th position under the random permutation. -/
def draw (i : Fin model.m) (ω : Ω) : Fin model.N :=
  model.perm ω (Fin.castLE model.hm_le i)

/-- No-replacement is immediate from permutation injectivity. -/
theorem draw_injective (ω : Ω) :
    Function.Injective (fun i : Fin model.m => model.draw i ω) := by
  intro i j hij
  have hcast : Fin.castLE model.hm_le i = Fin.castLE model.hm_le j := by
    exact (model.perm ω).injective (by simpa [RandomPermutationWOR.draw] using hij)
  exact Fin.ext (by simpa using congrArg Fin.val hcast)

/-- Almost-everywhere no-replacement witness for any ambient measure. -/
theorem ae_draw_no_replacement (μ : Measure Ω) :
    ∀ᵐ ω ∂μ, Function.Injective (fun i : Fin model.m => model.draw i ω) := by
  exact Filter.Eventually.of_forall (fun ω => model.draw_injective ω)

/-- Sampled leaf value at position `i`. -/
def sampledValue (i : Fin model.m) (ω : Ω) : ℝ :=
  model.leaf_value (model.draw i ω)

/-- Sampled leaf values inherit the finite-population bounds. -/
theorem sampledValue_mem_Icc (i : Fin model.m) (ω : Ω) :
    model.sampledValue i ω ∈ Set.Icc model.lower model.upper := by
  exact model.h_leaf_value_bounds (model.draw i ω)

/-- Centered sampled value `X - center`. -/
def centeredValue (center : ℝ) (i : Fin model.m) (ω : Ω) : ℝ :=
  model.sampledValue i ω - center

/-- Centered sampled values satisfy translated interval bounds. -/
theorem centeredValue_mem_Icc (center : ℝ) (i : Fin model.m) (ω : Ω) :
    model.centeredValue center i ω ∈ Set.Icc (model.lower - center) (model.upper - center) := by
  rcases model.sampledValue_mem_Icc i ω with ⟨hlo, hhi⟩
  constructor
  · exact sub_le_sub_right hlo center
  · exact sub_le_sub_right hhi center

/-- Canonical increment process:
`0` at step `0`, then centered sampled values for steps `1..m`. -/
def increments (center : ℝ) : ℕ → Ω → ℝ
  | 0 => 0
  | i + 1 => if hi : i < model.m then model.centeredValue center ⟨i, hi⟩ else 0

/-- Lower-step envelope used with `increments`. -/
def lowerStep (center : ℝ) : ℕ → ℝ
  | 0 => 0
  | _ + 1 => model.lower - center

/-- Upper-step envelope used with `increments`. -/
def upperStep (center : ℝ) : ℕ → ℝ
  | 0 => 0
  | _ + 1 => model.upper - center

/-- Step-0 normalization. -/
theorem increments_zero (center : ℝ) :
    model.increments center 0 = 0 := by
  simp [RandomPermutationWOR.increments]

/-- Measurability transfer from sampled values to increments. -/
theorem increments_meas
    (center : ℝ)
    (h_sampled_meas : ∀ i : Fin model.m, Measurable (fun ω => model.sampledValue i ω)) :
    ∀ i : ℕ, Measurable (model.increments center i) := by
  intro i
  cases i with
  | zero =>
      have hzero : model.increments center 0 = (fun _ : Ω => (0 : ℝ)) := by
        funext ω
        simp [RandomPermutationWOR.increments]
      rw [hzero]
      exact measurable_const
  | succ n =>
      by_cases h : n < model.m
      · simpa [RandomPermutationWOR.increments, h, RandomPermutationWOR.centeredValue] using
          (h_sampled_meas ⟨n, h⟩).sub measurable_const
      · have hzero : model.increments center (n + 1) = (fun _ : Ω => (0 : ℝ)) := by
          funext ω
          simp [RandomPermutationWOR.increments, h]
        rw [hzero]
        exact measurable_const

/-- Boundedness of the canonical increments (first-principles discharge). -/
theorem increment_bound
    {μ : Measure Ω}
    (center : ℝ) :
    ∀ i : ℕ, i < model.m →
      ∀ᵐ ω ∂μ,
        model.increments center (i + 1) ω ∈
          Set.Icc (model.lowerStep center (i + 1)) (model.upperStep center (i + 1)) := by
  intro i hi
  refine Filter.Eventually.of_forall ?_
  intro ω
  have hmem := model.centeredValue_mem_Icc center ⟨i, hi⟩ ω
  simpa [RandomPermutationWOR.increments, RandomPermutationWOR.lowerStep,
    RandomPermutationWOR.upperStep, hi] using hmem

end RandomPermutationWOR

variable {μ : Measure Ω} [IsZeroOrProbabilityMeasure μ]
variable {ℱ : Filtration ℕ mΩ}

/-- Azuma tail bound specialized to the explicit random-permutation WOR model.

This theorem uses the canonical centered increments from
`RandomPermutationWOR.increments`. The no-replacement and boundedness pieces are
derived in `RandomPermutationWOR`; users provide adaptation + conditional
mean-zero for their chosen filtration. -/
theorem azuma_hoeffding_abs_of_random_permutation
    (model : RandomPermutationWOR Ω)
    (center : ℝ)
    (h_sampled_meas :
      ∀ i : Fin model.m, Measurable (fun ω => model.sampledValue i ω))
    (h_adapted : Adapted ℱ (model.increments center))
    (h_cond : ∀ i : ℕ, i < model.m → μ[model.increments center (i + 1)|ℱ i] =ᵐ[μ] 0)
    {ε : ℝ} (hε : 0 ≤ ε) :
    μ.real {ω | ε ≤ |∑ i ∈ Finset.range (model.m + 1), model.increments center i ω|}
      ≤ 2 * Real.exp
        (-ε ^ 2 /
          (2 * ∑ i ∈ Finset.range (model.m + 1),
            (if i = 0 then (0 : ℝ≥0)
             else (‖model.upperStep center i - model.lowerStep center i‖₊ / 2) ^ 2))) := by
  have h :=
    azuma_hoeffding_abs_of_mem_Icc_of_condExp_eq_zero
      (μ := μ) (ℱ := ℱ) (Y := model.increments center)
      (a := model.lowerStep center) (b := model.upperStep center)
      (h_meas := model.increments_meas center h_sampled_meas)
      (hY0 := model.increments_zero center)
      (n := model.m + 1)
      (h_adapted := h_adapted)
      (h_bound := by
        intro i hi
        have hi' : i < model.m := by
          simpa [Nat.add_sub_cancel] using hi
        exact model.increment_bound (μ := μ) center i hi')
      (h_cond := by
        intro i hi
        have hi' : i < model.m := by
          simpa [Nat.add_sub_cancel] using hi
        exact h_cond i hi')
      (hε := hε)
  simpa using h

end RandomPermutationInstantiation

end OPT
