#!/usr/bin/env python3
"""Render the manifesto f/g ladder per-cell table as booktabs TeX.

Writes ``paper/ctreepo/assets/benoit/tables/manifesto_fg_ladder.tex`` from
the canonical per-row CSVs. Applies the inherited-cell collapse rule so
the output matches the structure App. H Table~\\ref{tab:manifesto-fg-ladder}
describes.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import _ladder_io as ladder_io  # noqa: E402
import benoit_references as refs  # noqa: E402


LANE_BANNERS = {
    "benoit_init": (
        r"\textit{Benoit-init lane: $g^0 = g^{\mathrm{Benoit}}$, "
        r"$f^1$ = scorer-only optimized prompt}"
    ),
    "raw_init": (
        r"\textit{Raw-init lane: $g^0$ = own-Gemma baseline summary, "
        r"$f^0$ = untuned scorer}"
    ),
}
LANE_DISPLAY = {"benoit_init": "Benoit", "raw_init": "Raw"}
LANE_ORDER = ("benoit_init", "raw_init")

LANE_ANCHOR_STAGE = {"benoit_init": "f1g0", "raw_init": "f0g0"}


def _fmt_num(value: float | None, *, precision: int = 3) -> str:
    if value is None:
        return "---"
    return f"{value:.{precision}f}"


def _format_stage_label(cell: ladder_io.LadderCell, *, mark_anchor: bool) -> str:
    ab = cell.stage_ab
    if ab is not None:
        a, b = ab
        tex = f"$f^{{{a}}} g^{{{b}}}$"
    else:
        label = cell.stage_label.strip() or cell.stage_name
        tex = f"${label}$"
    if mark_anchor:
        tex += " (anchor)"
    return tex


def _write_rows_for_lane(
    lines: list[str],
    lane: str,
    cells: list[ladder_io.LadderCell],
    *,
    best_ext_by_lane: dict[str, float | None],
    best_gap_by_lane: dict[str, float | None],
) -> None:
    banner = LANE_BANNERS.get(lane)
    if banner:
        lines.append(rf"\multicolumn{{7}}{{l}}{{{banner}}} \\")
    display = LANE_DISPLAY.get(lane, lane)

    best_ext = best_ext_by_lane.get(lane)
    best_gap = best_gap_by_lane.get(lane)

    anchor_stage = LANE_ANCHOR_STAGE.get(lane)
    anchor_leaf = min((c.leaf_size_tokens for c in cells), default=None)

    for cell in cells:
        is_anchor = (
            anchor_stage is not None
            and cell.stage_name == anchor_stage
            and cell.leaf_size_tokens == anchor_leaf
        )
        stage_tex = _format_stage_label(cell, mark_anchor=is_anchor)

        ext_r = cell.external_expert_pearson
        ext_mae = cell.external_expert_mae_1_7
        int_r = cell.internal_f_pearson if not is_anchor else None
        gap = cell.f_star_gap if not is_anchor else None

        ext_str = _fmt_num(ext_r)
        if ext_r is not None and best_ext is not None and abs(ext_r - best_ext) < 1e-6:
            ext_str = rf"$\mathbf{{{ext_str}}}$"
        else:
            ext_str = f"${ext_str}$" if ext_r is not None else ext_str

        gap_str = _fmt_num(gap)
        if gap is not None and best_gap is not None and abs(gap - best_gap) < 1e-6:
            gap_str = rf"$\mathbf{{{gap_str}}}$"
        else:
            gap_str = f"${gap_str}$" if gap is not None else gap_str

        ext_mae_str = f"${_fmt_num(ext_mae)}$" if ext_mae is not None else "---"
        int_r_str = f"${_fmt_num(int_r)}$" if int_r is not None else "---"

        lines.append(
            f"{display} & {cell.leaf_size_tokens} & {stage_tex} & "
            f"{ext_str} & {ext_mae_str} & {int_r_str} & {gap_str} \\\\"
        )


def _build_table(cells_by_lane: dict[str, list[ladder_io.LadderCell]]) -> str:
    best_ext_by_lane: dict[str, float | None] = {}
    best_gap_by_lane: dict[str, float | None] = {}
    for lane, cells in cells_by_lane.items():
        ext_vals = [c.external_expert_pearson for c in cells
                    if c.external_expert_pearson is not None and c.trained != "none"]
        gap_vals = [c.f_star_gap for c in cells
                    if c.f_star_gap is not None and c.trained != "none"]
        best_ext_by_lane[lane] = max(ext_vals) if ext_vals else None
        best_gap_by_lane[lane] = min(gap_vals) if gap_vals else None

    lines: list[str] = []
    lines.append(
        "% Auto-generated by paper/ctreepo/scripts/render_ladder_table.py."
    )
    lines.append(
        "% Collapses inherited (unchanged) ladder stages into the first"
    )
    lines.append(
        "% stage at which each distinct evaluation appeared."
    )
    lines.append(r"\begin{tabular}{lrrrrrr}")
    lines.append(r"\toprule")
    lines.append(
        r"Lane & Leaf (tok) & Stage & Ext.\ $r$ & Ext.\ MAE & "
        r"Int.\ $r$ & Int.-Ext.\ gap \\"
    )
    lines.append(r"\midrule")

    for i, lane in enumerate(LANE_ORDER):
        cells = cells_by_lane.get(lane)
        if not cells:
            continue
        if i > 0:
            lines.append(r"\midrule")
        _write_rows_for_lane(
            lines,
            lane,
            cells,
            best_ext_by_lane=best_ext_by_lane,
            best_gap_by_lane=best_gap_by_lane,
        )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--benoit-csv",
        action="append",
        default=[],
        help="Per-row CSV for the Benoit-init lane. May be repeated.",
    )
    parser.add_argument(
        "--raw-csv",
        action="append",
        default=[],
        help="Per-row CSV for the raw-init lane. May be repeated.",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Destination .tex path (e.g. paper/ctreepo/assets/benoit/tables/manifesto_fg_ladder.tex)",
    )
    parser.add_argument(
        "--skip-headline-check",
        action="store_true",
        help="Skip the HEADLINE_CELL drift assertion.",
    )
    return parser.parse_args(argv)


def _sorted_cells_for_table(cells: list[ladder_io.LadderCell]) -> list[ladder_io.LadderCell]:
    deduped = ladder_io.dedupe(cells)
    collapsed = ladder_io.collapse_inherited(deduped)
    return sorted(
        collapsed,
        key=lambda c: (c.leaf_size_tokens, c.stage_key),
    )


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if not args.benoit_csv and not args.raw_csv:
        raise SystemExit("Provide --benoit-csv and/or --raw-csv.")

    cells_by_lane: dict[str, list[ladder_io.LadderCell]] = {}
    if args.benoit_csv:
        benoit_cells = ladder_io.load_cells(args.benoit_csv, lane=refs.BENOIT_INIT_LANE)
        cells_by_lane[refs.BENOIT_INIT_LANE] = _sorted_cells_for_table(benoit_cells)
    if args.raw_csv:
        raw_cells = ladder_io.load_cells(args.raw_csv, lane=refs.RAW_INIT_LANE)
        cells_by_lane[refs.RAW_INIT_LANE] = _sorted_cells_for_table(raw_cells)

    if not args.skip_headline_check and refs.RAW_INIT_LANE in cells_by_lane:
        ladder_io.assert_headline(
            cells_by_lane[refs.RAW_INIT_LANE],
            expected=refs.HEADLINE_CELL,
        )

    tex = _build_table(cells_by_lane)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(tex, encoding="utf-8")
    total = sum(len(v) for v in cells_by_lane.values())
    print(f"wrote {args.output} ({total} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
