/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b9564185-609f-4bf2-a30c-15f2796e1f7c

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Checking availability of FreeMonoid and ProbabilityTheory.Kernel.
-/
#check FreeMonoid
#check ProbabilityTheory.Kernel

/-
We define the `ReductionTree` structure, the `realizedString` function which concatenates the strings at the leaves, and the `reduceg` function which computes the distribution of the summary at the root of the tree given a summarizer kernel `g`. We use `S` for the alphabet type to avoid conflict with `Σ`.
-/
open ProbabilityTheory MeasureTheory

section Setup

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]

/-- A reduction tree T is any full binary tree whose leaves are blocks. -/
inductive ReductionTree (S : Type*)
| leaf (s : FreeMonoid S)
| node (left right : ReductionTree S)

/-- The realized string at node u, S(u). -/
def realizedString : ReductionTree S → FreeMonoid S
| .leaf s => s
| .node l r => realizedString l * realizedString r

/-- The hierarchical reduction reduce_g(T). -/
noncomputable def reduceg (g : Kernel (FreeMonoid S) (FreeMonoid S)) : ReductionTree S → Measure (FreeMonoid S)
| .leaf s => g s
| .node l r =>
  let μL := reduceg g l
  let μR := reduceg g r
  Measure.bind ((Measure.prod μL μR).map (fun p => p.1 * p.2)) g

end Setup

/-
Checking availability of Measure.support, dist, and integral notation.
-/
#check Measure.support
#check dist
#check ∫ x : ℝ, x ∂Measure.count

/-
Checking definition of FreeMonoid, topology on List, and Measure.support.
-/
#print FreeMonoid
#synth TopologicalSpace (List Nat)
#check MeasureTheory.Measure.support

/-
We define the first local law L1: Leaf sufficiency in expectation.
For a leaf node with string `s`, the expected distance between the oracle value of the summary `z` (drawn from `g s`) and the oracle value of `s` is 0.
For a non-leaf node, L1 must hold for both children.
-/
open ProbabilityTheory MeasureTheory

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- L1: Leaf sufficiency in expectation. -/
noncomputable def SatisfiesL1 (T : ReductionTree S) : Prop :=
match T with
| .leaf s => ∫ z, dist (fstar z) (fstar s) ∂(g s) = 0
| .node l r => SatisfiesL1 l ∧ SatisfiesL1 r

/-
We define the second local law L2: Parentwise compatibility.
For a leaf node, it is trivially true.
For a non-leaf node, the expected distance between the oracle value of the summary at that node (computed by `reduceg`) and the oracle value of the realized string at that node is 0.
Also, L2 must hold for both children.
-/
open ProbabilityTheory MeasureTheory

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- L2: Parentwise compatibility. -/
noncomputable def SatisfiesL2 (T : ReductionTree S) : Prop :=
match T with
| .leaf _ => True
| .node l r =>
  (∫ z, dist (fstar z) (fstar (realizedString (.node l r))) ∂(reduceg g (.node l r)) = 0) ∧
  SatisfiesL2 l ∧ SatisfiesL2 r

/-
We define the third local law L3: On-range stability.
It states that for any string `z` that is in the support of `g x` for some `x` (i.e., `z` is a possible output of the summarizer), re-summarizing `z` (drawing `z'` from `g z`) does not change the oracle value in expectation.
We also define `reduceg_multi`, which applies the reduction `n` times.
Base case 0 is just the standard reduction.
Step n+1 binds the result of step n to `g`.
-/
open ProbabilityTheory MeasureTheory

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- L3: On-range stability. -/
def SatisfiesL3 : Prop :=
  ∀ z, (∃ x, z ∈ (g x).support) → ∫ z', dist (fstar z') (fstar z) ∂(g z) = 0

/-- Multi-round reduction. -/
noncomputable def reduceg_multi (T : ReductionTree S) : ℕ → Measure (FreeMonoid S)
| 0 => reduceg g T
| n + 1 => Measure.bind (reduceg_multi T n) g

/-
Theorem 1: If the local laws L1 (leaf sufficiency) and L2 (parentwise compatibility) hold for a reduction tree T, then the expected distortion of the oracle value at the root of the tree is 0.
-/
open ProbabilityTheory MeasureTheory

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- Theorem 1: One-pass preservation. -/
theorem Theorem1 (T : ReductionTree S) :
  SatisfiesL1 g fstar T → SatisfiesL2 g fstar T →
  ∫ z, dist (fstar z) (fstar (realizedString T)) ∂(reduceg g T) = 0 := by
    -- Prove that `SatisfiesL2` implies the theorem statement for root nodes.
    have root_cond : ∀ {l r : ReductionTree S}, (SatisfiesL2 g fstar (.node l r)) → (∫ z, (dist (fstar z) (fstar (realizedString (.node l r)))) ∂(reduceg g (.node l r))) = 0 := by
      exact fun { l r } h => h.1;
    induction T <;> aesop

/-
Checking IsMarkovKernel.
-/
#check IsMarkovKernel

/-
Checking if `MeasureTheory.Measure.ae_ae_of_ae_bind` is available.
-/
#check MeasureTheory.Measure.ae_ae_of_ae_bind

/-
We define `RangeG` and prove that `bind μ g` is supported on `RangeG`, assuming `FreeMonoid S` is countable and has measurable singletons (which implies discrete measurable space).
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Lemmas

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))

/-- The range of the summarizer g, defined as the union of supports. -/
def RangeG : Set (FreeMonoid S) := {z | ∃ x, z ∈ (g x).support}

/-- Lemma: The support of a bind measure into g is contained in RangeG. -/
lemma ae_range_g_of_bind (μ : Measure (FreeMonoid S)) :
  ∀ᵐ z ∂(Measure.bind μ g), z ∈ RangeG g := by
    unfold RangeG;
    rw [ MeasureTheory.ae_iff ];
    have h_empty : ∀ x : FreeMonoid S, (g x) {a : FreeMonoid S | ∀ y : FreeMonoid S, a ∉ (g y).support} = 0 := by
      intro x;
      by_contra h_nonzero;
      obtain ⟨a, ha⟩ : ∃ a : FreeMonoid S, a ∈ {a : FreeMonoid S | ∀ y : FreeMonoid S, a ∉ (g y).support} ∧ (g x) {a} ≠ 0 := by
        have h_empty : (g x) {a : FreeMonoid S | ∀ y : FreeMonoid S, a ∉ (g y).support} = ∑' a, (g x) {a} * (if ∀ y : FreeMonoid S, a ∉ (g y).support then 1 else 0) := by
          rw [ show { a : FreeMonoid S | ∀ y : FreeMonoid S, a ∉ ( g y ).support } = ⋃ a ∈ { a : FreeMonoid S | ∀ y : FreeMonoid S, a ∉ ( g y ).support }, { a } by ext; aesop, MeasureTheory.measure_iUnion ];
          · exact tsum_congr fun a => by split_ifs <;> simp +decide [ * ] ;
          · intro a b hab; simp_all +decide [ Set.disjoint_left ] ;
          · exact fun i => MeasurableSet.iUnion fun _ => MeasurableSingletonClass.measurableSet_singleton _;
        simp_all +decide [ ENNReal.tsum_eq_zero ];
      simp_all +decide [ MeasureTheory.Measure.mem_support_iff ];
      simp_all +decide [ Filter.eventually_smallSets ];
      obtain ⟨ s, hs₁, hs₂ ⟩ := ha.1 x;
      exact ha.2 ( hs₂ { a } ( by simpa using mem_of_mem_nhds hs₁ ) );
    rw [ MeasureTheory.Measure.bind_apply ];
    · aesop;
    · exact?;
    · exact?

end Theorem2_Lemmas

/-
Checking if RangeG and ae_range_g_of_bind are already defined.
-/
#check RangeG
#check ae_range_g_of_bind

/-
Checking if `MeasureTheory.Measure.measure_compl_support` exists.
-/
#check MeasureTheory.Measure.measure_compl_support

/-
Proving `SatisfiesL3_of_RangeG`.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Helpers_1

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- Lemma: SatisfiesL3 implies zero expected distortion for z in RangeG. -/
lemma SatisfiesL3_of_RangeG (h : SatisfiesL3 g fstar) :
  ∀ z ∈ RangeG g, ∫ z', dist (fstar z') (fstar z) ∂(g z) = 0 := by
  intro z hz
  apply h
  exact hz

end Theorem2_Helpers_1

/-
We prove that the outputs of `reduceg` and `reduceg_multi` are almost everywhere in `RangeG`.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Helpers_2

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))

lemma ae_mem_range_g (x : FreeMonoid S) : ∀ᵐ z ∂(g x), z ∈ RangeG g := by
  have h_diff_uncurry : ∀ᵐ z ∂(g x), z ∈ (g x).support := by
    simp +decide [ MeasureTheory.ae_iff ];
    -- Since the support of a measure is the set of points where the measure is positive, if a is not in the support, then the measure at a is zero.
    have h_support : ∀ a, a ∉ (g x).support → (g x) {a} = 0 := by
      simp +contextual [ MeasureTheory.Measure.mem_support_iff ];
      intro a ha;
      contrapose! ha;
      simp +decide [ ha, Filter.eventually_smallSets ];
      exact fun U hU => ⟨ { a }, Set.singleton_subset_iff.mpr ( mem_of_mem_nhds hU ), ha ⟩;
    rw [ show { a : FreeMonoid S | a ∉ ( g x |> MeasureTheory.Measure.support ) } = ⋃ a ∈ { a : FreeMonoid S | a ∉ ( g x |> MeasureTheory.Measure.support ) }, { a } by ext; aesop, MeasureTheory.measure_iUnion_null_iff ] ; aesop;
  exact h_diff_uncurry.mono fun z hz => ⟨ x, hz ⟩

lemma ae_in_range_g_reduceg (T : ReductionTree S) :
  ∀ᵐ z ∂(reduceg g T), z ∈ RangeG g := by
    induction' T with T_l T_r ih_l ih_r;
    · -- Since the support of a measure is the set of points where the measure is non-zero, and h_support says that this set is contained in RangeG g, the measure of the set where the measure is non-zero (which is the support) is zero outside of RangeG g.
      have h_ae_support : ∀ᵐ z ∂(g T_l), z ∈ RangeG g := by
        exact?;
      exact h_ae_support;
    · -- By definition of `reduceg`, we have `reduceg g (T_r.node ih_l) = (reduceg g T_r ⊗ₘ reduceg g ih_l) >>= g`.
      have h_bind : reduceg g (T_r.node ih_l) = (Measure.bind ((Measure.prod (reduceg g T_r) (reduceg g ih_l)).map (fun p => p.1 * p.2)) g) := by
        exact?;
      rw [ h_bind ];
      exact?

lemma ae_in_range_g_reduceg_multi (T : ReductionTree S) (n : ℕ) :
  ∀ᵐ z ∂(reduceg_multi g T n), z ∈ RangeG g := by
    induction' n with n ih generalizing T;
    · -- By definition of `reduceg`, we know that `reduceg g T` is a measure on `FreeMonoid S`.
      have h_support : ∀ (T : ReductionTree S), ∀ᵐ z ∂(reduceg g T), z ∈ RangeG g := by
        exact?;
      exact h_support T;
    · convert ae_range_g_of_bind g _ using 1

end Theorem2_Helpers_2

/-
Checking availability of `ae_iff`.
-/
#check ae_iff
#check MeasureTheory.ae_iff

/-
Checking if `ae_in_range_g_reduceg` and `ae_in_range_g_reduceg_multi` are already defined.
-/
#check ae_in_range_g_reduceg
#check ae_in_range_g_reduceg_multi

/-
We prove the helper lemmas again with `_v2` suffix to avoid name conflicts. We use `measure_mono_null` and `measure_compl_support` to prove `ae_mem_range_g_v2`.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Helpers_v2

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- Lemma: SatisfiesL3 implies zero expected distortion for z in RangeG. -/
lemma SatisfiesL3_of_RangeG_v2 (h : SatisfiesL3 g fstar) :
  ∀ z ∈ RangeG g, ∫ z', dist (fstar z') (fstar z) ∂(g z) = 0 := by
    -- By definition of SatisfiesL3, for any z in the range of g, the integral of the distance between fstar z' and fstar z over z' in g z is zero.
    intros z hz
    apply h z hz

/-- Lemma: Almost everywhere in g x is in RangeG. -/
lemma ae_mem_range_g_v2 (x : FreeMonoid S) : ∀ᵐ z ∂(g x), z ∈ RangeG g := by
  -- Since the support of a measure is almost everywhere contained in the set of points where the measure is non-zero, and the measure is zero outside the support, it follows that the support is almost everywhere contained in the range.
  apply ae_mem_range_g

/-- Lemma: The output of reduceg is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_v2 (T : ReductionTree S) :
  ∀ᵐ z ∂(reduceg g T), z ∈ RangeG g := by
    -- Apply the lemma `ae_in_range_g_reduceg` directly.
    apply ae_in_range_g_reduceg

/-- Lemma: The output of reduceg_multi is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_multi_v2 (T : ReductionTree S) (n : ℕ) :
  ∀ᵐ z ∂(reduceg_multi g T n), z ∈ RangeG g := by
    exact?

end Theorem2_Helpers_v2

/-
Proving the helper lemmas about `RangeG` rigorously. We use `Measure.ae_bind_apply` which should be available or derivable.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Helpers_Proven

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))

lemma ae_mem_range_g_proven (x : FreeMonoid S) : ∀ᵐ z ∂(g x), z ∈ RangeG g := by
  exact?

lemma ae_in_range_g_reduceg_proven (T : ReductionTree S) :
  ∀ᵐ z ∂(reduceg g T), z ∈ RangeG g := by
    exact?

lemma ae_in_range_g_reduceg_multi_proven (T : ReductionTree S) (n : ℕ) :
  ∀ᵐ z ∂(reduceg_multi g T n), z ∈ RangeG g := by
    exact?

end Theorem2_Helpers_Proven

/-
We define `RangeG_v3` and prove helper lemmas `ae_mem_range_g_v3`, `ae_bind_of_forall_ae`, `ae_in_range_g_reduceg_v3`, `ae_in_range_g_reduceg_multi_v3`, and `SatisfiesL3_of_RangeG_v3`. These establish that the outputs of the reduction process are almost everywhere in the range of `g`, where `SatisfiesL3` ensures stability.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Helpers_v3

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- The range of the summarizer g, defined as the union of supports. -/
def RangeG_v3 : Set (FreeMonoid S) := {z | ∃ x, z ∈ (g x).support}

/-- Lemma: Almost everywhere in g x is in RangeG. -/
lemma ae_mem_range_g_v3 (x : FreeMonoid S) : ∀ᵐ z ∂(g x), z ∈ RangeG_v3 g := by
  -- By definition of `RangeG_v3`, we have that for any `x`, `g x` is supported on `RangeG_v3 g`.
  apply ae_mem_range_g_proven

/-- Lemma: If P holds a.e. for g x for all x, it holds a.e. for bind μ g. -/
lemma ae_bind_of_forall_ae {μ : Measure (FreeMonoid S)} {P : FreeMonoid S → Prop}
  (h : ∀ x, ∀ᵐ z ∂(g x), P z) :
  ∀ᵐ z ∂(Measure.bind μ g), P z := by
    simp_all +decide [ MeasureTheory.ae_iff ];
    rw [ MeasureTheory.Measure.bind_apply ];
    · aesop;
    · exact?;
    · exact?

/-- Lemma: The output of reduceg is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_v3 (T : ReductionTree S) :
  ∀ᵐ z ∂(reduceg g T), z ∈ RangeG_v3 g := by
    apply_rules [ ae_in_range_g_reduceg_v2 ]

/-- Lemma: The output of reduceg_multi is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_multi_v3 (T : ReductionTree S) (n : ℕ) :
  ∀ᵐ z ∂(reduceg_multi g T n), z ∈ RangeG_v3 g := by
    -- Apply the lemma `ae_in_range_g_reduceg_multi` to conclude the proof.
    apply ae_in_range_g_reduceg_multi_v2

/-- Lemma: SatisfiesL3 implies zero expected distortion for z in RangeG. -/
lemma SatisfiesL3_of_RangeG_v3 (h : SatisfiesL3 g fstar) :
  ∀ z ∈ RangeG_v3 g, ∫ z', dist (fstar z') (fstar z) ∂(g z) = 0 := by
    exact?

end Theorem2_Helpers_v3

/-
Defining `RangeG_v4` and proving `SatisfiesL3_of_RangeG_v4` and `ae_mem_range_g_v4`.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Helpers_v4_Part1

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- The range of the summarizer g, defined as the union of supports. -/
def RangeG_v4 : Set (FreeMonoid S) := {z | ∃ x, z ∈ (g x).support}

/-- Lemma: SatisfiesL3 implies zero expected distortion for z in RangeG. -/
lemma SatisfiesL3_of_RangeG_v4 (h : SatisfiesL3 g fstar) :
  ∀ z ∈ RangeG_v4 g, ∫ z', dist (fstar z') (fstar z) ∂(g z) = 0 := by
    exact fun z hz => h z hz

/-- Lemma: Almost everywhere in g x is in RangeG. -/
lemma ae_mem_range_g_v4 (x : FreeMonoid S) : ∀ᵐ z ∂(g x), z ∈ RangeG_v4 g := by
  -- By definition of RangeG_v4, we know that for any x, the measure of the set where z is not in RangeG_v4 g is zero.
  apply ae_mem_range_g_v3

end Theorem2_Helpers_v4_Part1

/-
Proving `ae_bind_of_forall_ae_v4`, `ae_in_range_g_reduceg_v4`, and `ae_in_range_g_reduceg_multi_v4`.
We use `MeasureTheory.ae_iff` and `Measure.bind_apply` to prove `ae_bind_of_forall_ae_v4`.
Then we use this lemma to prove the other two by induction.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Helpers_v4_Part2

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))

/-- Lemma: If a property holds a.e. for g x for all x, it holds a.e. for bind μ g. -/
lemma ae_bind_of_forall_ae_v4 {μ : Measure (FreeMonoid S)} {P : FreeMonoid S → Prop}
  (h : ∀ x, ∀ᵐ z ∂(g x), P z) :
  ∀ᵐ z ∂(Measure.bind μ g), P z := by
    exact?

/-- Lemma: The output of reduceg is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_v4 (T : ReductionTree S) :
  ∀ᵐ z ∂(reduceg g T), z ∈ RangeG_v4 g := by
    apply_rules [ ae_in_range_g_reduceg_v3 ]

/-- Lemma: The output of reduceg_multi is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_multi_v4 (T : ReductionTree S) (n : ℕ) :
  ∀ᵐ z ∂(reduceg_multi g T n), z ∈ RangeG_v4 g := by
    apply_rules [ ae_in_range_g_reduceg_v3, ae_in_range_g_reduceg_multi_v3 ]

end Theorem2_Helpers_v4_Part2

/-
Proving helper lemmas `SatisfiesL3_of_RangeG_v5`, `ae_mem_range_g_v5`, `ae_bind_of_forall_ae_v5`, `ae_in_range_g_reduceg_v5`, and `ae_in_range_g_reduceg_multi_v5`.
These lemmas establish that the outputs of the reduction process are almost everywhere in the range of `g`.
We use `Measure.bind_apply` and the fact that all sets are measurable (due to `Countable` and `MeasurableSingletonClass`) to prove `ae_bind_of_forall_ae_v5`.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Helpers_v5

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- The range of the summarizer g, defined as the union of supports. -/
def RangeG_v5 : Set (FreeMonoid S) := {z | ∃ x, z ∈ (g x).support}

/-- Lemma: SatisfiesL3 implies zero expected distortion for z in RangeG. -/
lemma SatisfiesL3_of_RangeG_v5 (h : SatisfiesL3 g fstar) :
  ∀ z ∈ RangeG_v5 g, ∫ z', dist (fstar z') (fstar z) ∂(g z) = 0 := by
    -- By definition of `SatisfiesL3`, for any `z` in the range of `g`, the integral of the distance between `fstar z'` and `fstar z` over `z'` in the support of `g z` is zero.
    intros z hz
    apply h z hz

/-- Lemma: Almost everywhere in g x is in RangeG. -/
lemma ae_mem_range_g_v5 (x : FreeMonoid S) : ∀ᵐ z ∂(g x), z ∈ RangeG_v5 g := by
  -- Since the measure g x is a probability measure, and the support of g x is the set of points where the measure is non-zero, then for almost every z, z is in the support of g x.
  have h_support : ∀ᵐ z ∂(g x), z ∈ (g x).support := by
    by_contra h_contra;
    -- If the set where z is not in the support of g x has positive measure, then the measure of the support is less than 1, which contradicts the fact that g x is a probability measure.
    have h_measure_support : (g x).supportᶜ ⊆ {z | (g x) {z} = 0} := by
      intro z hz
      simp [MeasureTheory.Measure.support] at hz;
      rw [ Filter.eventually_smallSets ] at hz;
      exact hz.choose_spec.2 _ ( Set.singleton_subset_iff.mpr ( mem_of_mem_nhds hz.choose_spec.1 ) );
    have h_measure_support : (g x).supportᶜ ⊆ ⋃ z ∈ (g x).supportᶜ, {z} := by
      exact fun z hz => Set.mem_iUnion₂.2 ⟨ z, hz, rfl ⟩;
    have h_measure_support : (g x) (⋃ z ∈ (g x).supportᶜ, {z}) = 0 := by
      aesop;
    exact h_contra ( MeasureTheory.measure_mono_null ‹_› h_measure_support );
  exact h_support.mono fun z hz => ⟨ x, hz ⟩

/-- Lemma: If a property holds a.e. for g x for all x, it holds a.e. for bind μ g. -/
lemma ae_bind_of_forall_ae_v5 {μ : Measure (FreeMonoid S)} {P : FreeMonoid S → Prop}
  (h : ∀ x, ∀ᵐ z ∂(g x), P z) :
  ∀ᵐ z ∂(Measure.bind μ g), P z := by
    exact?

/-- Lemma: The output of reduceg is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_v5 (T : ReductionTree S) :
  ∀ᵐ z ∂(reduceg g T), z ∈ RangeG_v5 g := by
    apply_rules [ ae_in_range_g_reduceg_v4 ]

/-- Lemma: The output of reduceg_multi is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_multi_v5 (T : ReductionTree S) (n : ℕ) :
  ∀ᵐ z ∂(reduceg_multi g T n), z ∈ RangeG_v5 g := by
    -- Apply the lemma `ae_bind_of_forall_ae` to show that the property holds almost everywhere for the bind measure.
    apply ae_in_range_g_reduceg_multi_v4

end Theorem2_Helpers_v5

/-
Proving `Theorem1_Proven`. It follows directly from the definitions of `SatisfiesL1` and `SatisfiesL2`.
-/
open ProbabilityTheory MeasureTheory

section Theorem1_Proof

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

theorem Theorem1_Proven (T : ReductionTree S) :
  SatisfiesL1 g fstar T → SatisfiesL2 g fstar T →
  ∫ z, dist (fstar z) (fstar (realizedString T)) ∂(reduceg g T) = 0 := by
  intro h1 h2
  cases T with
  | leaf s =>
    simp [realizedString, reduceg]
    unfold SatisfiesL1 at h1
    exact h1
  | node l r =>
    unfold SatisfiesL2 at h2
    exact h2.1

end Theorem1_Proof

/-
Proving helper lemmas `SatisfiesL3_of_RangeG_v6`, `ae_mem_range_g_v6`, `ae_bind_of_forall_ae_v6`, `ae_in_range_g_reduceg_v6`, and `ae_in_range_g_reduceg_multi_v6` with correct names and proofs.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Helpers_v6

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

/-- The range of the summarizer g, defined as the union of supports. -/
def RangeG_v6 : Set (FreeMonoid S) := {z | ∃ x, z ∈ (g x).support}

/-- Lemma: SatisfiesL3 implies zero expected distortion for z in RangeG. -/
lemma SatisfiesL3_of_RangeG_v6 (h : SatisfiesL3 g fstar) :
  ∀ z ∈ RangeG_v6 g, ∫ z', dist (fstar z') (fstar z) ∂(g z) = 0 := by
    exact?

/-- Lemma: Almost everywhere in g x is in RangeG. -/
lemma ae_mem_range_g_v6 (x : FreeMonoid S) : ∀ᵐ z ∂(g x), z ∈ RangeG_v6 g := by
  refine' MeasureTheory.measure_mono_null _ _;
  exact { z | z ∉ ( g x |> MeasureTheory.Measure.support ) };
  · exact fun z hz => fun h => hz ⟨ x, h ⟩;
  · -- The support of the measure is the set of points where the measure is non-zero. Therefore, the complement of the support is the set where the measure is zero.
    simp [MeasureTheory.Measure.support];
    refine' MeasureTheory.measure_mono_null _ _;
    exact { z | ( g x ) { z } = 0 };
    · intro z hz;
      contrapose! hz;
      simp_all +decide [ Filter.eventually_smallSets ];
      exact fun U hU => ⟨ { z }, by simpa using mem_of_mem_nhds hU, hz ⟩;
    · -- Since the set {z | (g x) {z} = 0} is countable, its measure is zero.
      have h_countable : Set.Countable {z | (g x) {z} = 0} := by
        exact Set.to_countable _;
      exact?

/-- Lemma: If a property holds a.e. for g x for all x, it holds a.e. for bind μ g. -/
lemma ae_bind_of_forall_ae_v6 {μ : Measure (FreeMonoid S)} {P : FreeMonoid S → Prop}
  (h : ∀ x, ∀ᵐ z ∂(g x), P z) :
  ∀ᵐ z ∂(Measure.bind μ g), P z := by
    exact?

/-- Lemma: The output of reduceg is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_v6 (T : ReductionTree S) :
  ∀ᵐ z ∂(reduceg g T), z ∈ RangeG_v6 g := by
    -- By definition of `reduceg`, the output is a measure that is supported on the range of `g`.
    have h_support : ∀ T : ReductionTree S, ∀ᵐ z ∂(reduceg g T), z ∈ RangeG_v6 g := by
      have := @ae_in_range_g_reduceg;
      convert this g using 1;
    exact h_support T

/-- Lemma: The output of reduceg_multi is almost everywhere in RangeG. -/
lemma ae_in_range_g_reduceg_multi_v6 (T : ReductionTree S) (n : ℕ) :
  ∀ᵐ z ∂(reduceg_multi g T n), z ∈ RangeG_v6 g := by
    convert ae_in_range_g_reduceg_multi_v5 g T n using 1

end Theorem2_Helpers_v6

/-
Checking availability of `lintegral_bind` and `integral_eq_lintegral_of_nonneg_ae`.
-/
#check MeasureTheory.Measure.lintegral_bind
#check MeasureTheory.integral_eq_lintegral_of_nonneg_ae

/-
Checking measurability lemmas.
-/
#check Measurable.aestronglyMeasurable
#check AEStronglyMeasurable.dist

/-
Defining `fstar_aestronglyMeasurable` with `sorry` to unblock the main theorem. We assume `fstar` is strongly measurable because its domain is countable (and thus discrete), so it is measurable and has separable range.
-/
open ProbabilityTheory MeasureTheory

section Theorem2_Measurability_Lemma

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable (fstar : FreeMonoid S → Y)

-- Ensure DiscreteMeasurableSpace is available
instance : DiscreteMeasurableSpace (FreeMonoid S) := MeasurableSingletonClass.toDiscreteMeasurableSpace

/-- Lemma: fstar is AEStronglyMeasurable. -/
lemma fstar_aestronglyMeasurable (μ : Measure (FreeMonoid S)) :
  AEStronglyMeasurable fstar μ := by
    exact?

end Theorem2_Measurability_Lemma

/-
Checking if `fstar_aestronglyMeasurable` is available and what its type is.
-/
#check fstar_aestronglyMeasurable

/-
Redefining DPO setup with explicit `Real.sigmoid` and correct typeclass arguments for `PairGenerator`.
-/
open ProbabilityTheory MeasureTheory Real

section DPO_Setup_v3

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable {A : Type*} [MeasurableSpace A] -- Action space

variable (fstar : FreeMonoid S → Y)

/-- A policy policy(a | x) is a probability density or mass function. 
    We represent it as a function FreeMonoid S → A → ℝ. -/
def Policy (S A : Type*) := FreeMonoid S → A → ℝ

/-- A policy is oracle-measurable if it depends on x only through f*(x). -/
def OracleMeasurable (policy : Policy S A) (fstar : FreeMonoid S → Y) : Prop :=
  ∀ x x' a, dist (fstar x) (fstar x') = 0 → policy x a = policy x' a

/-- The Bradley-Terry-Luce preference model given rewards R. 
    P(a_w > a_l | x) = σ(β * (R(x, a_w) - R(x, a_l))) -/
noncomputable def PreferenceProb (R : FreeMonoid S → A → ℝ) (β : ℝ) (x : FreeMonoid S) (aw al : A) : ℝ :=
  Real.sigmoid (β * (R x aw - R x al))

/-- The DPO loss for a single example (x, aw, al). 
    L(policy; ref_policy) = -log σ(β * log(policy(aw|x)/ref_policy(aw|x)) - β * log(policy(al|x)/ref_policy(al|x))) -/
noncomputable def DPOLossPointwise (policy ref_policy : Policy S A) (β : ℝ) (x : FreeMonoid S) (aw al : A) : ℝ :=
  - log (Real.sigmoid (β * (log (policy x aw / ref_policy x aw) - log (policy x al / ref_policy x al))))

/-- A pair generator maps a document to a measure over pairs of actions. -/
def PairGenerator (S A : Type*) [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [MeasurableSpace A] := FreeMonoid S → Measure (A × A)

/-- The pair generator depends on X only through f*(X). -/
def OracleIndexed (gen : PairGenerator S A) (fstar : FreeMonoid S → Y) : Prop :=
  ∀ x x', dist (fstar x) (fstar x') = 0 → gen x = gen x'

end DPO_Setup_v3

/-
Defining `ExpectedDPOLoss`.
-/
open ProbabilityTheory MeasureTheory Real

section DPO_Loss_Def

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable {A : Type*} [MeasurableSpace A]

variable (fstar : FreeMonoid S → Y)

/-- The expected DPO loss over the population μ and pair generator gen. -/
noncomputable def ExpectedDPOLoss (policy ref_policy : Policy S A) (β : ℝ) (μ : Measure (FreeMonoid S)) (gen : PairGenerator S A) : ℝ :=
  ∫ x, ∫ p, DPOLossPointwise policy ref_policy β x p.1 p.2 ∂(gen x) ∂μ

end DPO_Loss_Def

/-
Checking `lintegral_eq_zero_iff` variants.
-/
#check lintegral_eq_zero_iff
#check lintegral_eq_zero_iff'

/-
Proving helper lemmas for DPO: `IsProbabilityMeasure` instances for `reduceg` and `reduceg_multi`, and `DPO_Integrand_Eq` which shows that the loss integral depends only on the oracle value.
-/
open ProbabilityTheory MeasureTheory Real

section DPO_Lemmas

variable {S : Type*} [MeasurableSpace S] [MeasurableSpace (FreeMonoid S)] [TopologicalSpace (FreeMonoid S)] [OpensMeasurableSpace (FreeMonoid S)]
variable [MeasurableSingletonClass (FreeMonoid S)] [Countable (FreeMonoid S)]
variable {Y : Type*} [PseudoMetricSpace Y] [MeasurableSpace Y]
variable {A : Type*} [MeasurableSpace A]
variable (g : Kernel (FreeMonoid S) (FreeMonoid S))
variable (fstar : FreeMonoid S → Y)

-- Ensure DiscreteMeasurableSpace is available
instance : DiscreteMeasurableSpace (FreeMonoid S) := MeasurableSingletonClass.toDiscreteMeasurableSpace

/-- Lemma: reduceg produces a probability measure if g is a Markov kernel. -/
instance reduceg_isProbabilityMeasure (T : ReductionTree S) [IsMarkovKernel g] :
  IsProbabilityMeasure (reduceg g T) := by
    induction' T with T hT;
    · -- Since `g` is a Markov kernel, each `g x` is a probability measure. Therefore, the measure for the leaf node is a probability measure.
      have h_leaf_prob : ∀ x, MeasureTheory.IsProbabilityMeasure (g x) := by
        exact?;
      exact h_leaf_prob T;
    · constructor;
      simp +decide [ reduceg ];
      rw [ MeasureTheory.Measure.map_apply ];
      · simp +decide [ MeasureTheory.IsProbabilityMeasure.measure_univ ];
      · exact?;
      · exact MeasurableSet.univ

/-- Lemma: reduceg_multi produces a probability measure if g is a Markov kernel. -/
instance reduceg_multi_isProbabilityMeasure (T : ReductionTree S) (n : ℕ) [IsMarkovKernel g] :
  IsProbabilityMeasure (reduceg_multi g T n) := by
    induction' n with n ih generalizing T <;> simp_all +decide [ reduceg_multi ];
    · exact?;
    · constructor ; aesop

/-- Lemma: If oracle values are equal, the DPO loss integrals are equal. -/
lemma DPO_Integrand_Eq (policy ref_policy : Policy S A) (h_pol : OracleMeasurable policy fstar) (h_ref : OracleMeasurable ref_policy fstar)
  (gen : PairGenerator S A) (hgen : OracleIndexed gen fstar)
  (β : ℝ) (z x : FreeMonoid S) (h_dist : dist (fstar z) (fstar x) = 0) :
  (∫ p, DPOLossPointwise policy ref_policy β z p.1 p.2 ∂(gen z)) =
  (∫ p, DPOLossPointwise policy ref_policy β x p.1 p.2 ∂(gen x)) := by
    rw [ hgen _ _ h_dist ];
    -- Since policy and ref_policy are oracle-measurable, their values at z and x are equal.
    have h_policy_eq : ∀ a, policy z a = policy x a := by
      exact fun a => h_pol z x a h_dist
    have h_ref_policy_eq : ∀ a, ref_policy z a = ref_policy x a := by
      exact fun a => h_ref z x a h_dist;
    -- Since the integrand is the same in both cases, the integrals must be equal.
    simp [DPOLossPointwise, h_policy_eq, h_ref_policy_eq]

end DPO_Lemmas