/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 63fd80bb-f3fc-48a8-b303-0763c849e171

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of Summarizer, Eg (Expectation), and D (Distortion).
-/
def Summarizer (α : Type*) := α → PMF α

noncomputable def Eg {α : Type*} (g : Summarizer α) (f : α → ℝ) (x : α) : ℝ :=
  ∑' z, (g x z).toReal * f z

variable {Y : Type*} [PseudoMetricSpace Y]

def D {α : Type*} (fstar : α → Y) (z x : α) : ℝ :=
  dist (fstar z) (fstar x)

/-
Definitions of BinTree, Realized String (S), Hierarchical Reduction (reduce), Multi-Round Reduction (ZR), and Tree Accessors.
-/
inductive BinTree (α : Type*) : Type _
| leaf : α → BinTree α
| node : BinTree α → BinTree α → BinTree α

variable {Strings : Type*} [Monoid Strings]

def S : BinTree Strings → Strings
| BinTree.leaf b => b
| BinTree.node T_L T_R => S T_L * S T_R

variable (g : Summarizer Strings)

def reduce : BinTree Strings → PMF Strings
| BinTree.leaf b => g b
| BinTree.node T_L T_R => (reduce T_L).bind (fun s_L => (reduce T_R).bind (fun s_R => g (s_L * s_R)))

def ZR (x : Strings) (R : ℕ) (T : BinTree Strings) : PMF Strings :=
  match R with
  | 0 => PMF.pure x -- Should not happen based on 1-indexing in paper, but need base case
  | 1 => reduce g T
  | n + 1 => (ZR x n T).bind g

def root {α : Type*} (T : BinTree α) : BinTree α := T

def leaves {α : Type*} : BinTree α → List α
| BinTree.leaf b => [b]
| BinTree.node T_L T_R => leaves T_L ++ leaves T_R

def internal_nodes {α : Type*} : BinTree α → List (BinTree α × BinTree α)
| BinTree.leaf _ => []
| BinTree.node T_L T_R => (T_L, T_R) :: (internal_nodes T_L ++ internal_nodes T_R)

/-
Definitions of Egu (Tree Expectation), subtrees, and Local Laws L1, L2, L3.
-/
variable {Strings : Type*} [Monoid Strings]
variable {Y : Type*} [PseudoMetricSpace Y]

def Egu (g : Summarizer Strings) (T : BinTree Strings) (f : Strings → ℝ) : ℝ :=
  ∑' z, (reduce g T z).toReal * f z

def subtrees {α : Type*} : BinTree α → List (BinTree α)
| BinTree.leaf b => [BinTree.leaf b]
| BinTree.node T_L T_R => BinTree.node T_L T_R :: (subtrees T_L ++ subtrees T_R)

def L1 (g : Summarizer Strings) (T : BinTree Strings) (fstar : Strings → Y) : Prop :=
  ∀ b, b ∈ leaves T → Eg g (fun z => D fstar z b) b = 0

def L2 (g : Summarizer Strings) (T : BinTree Strings) (fstar : Strings → Y) : Prop :=
  ∀ p, p ∈ internal_nodes T →
    let (T_L, T_R) := p
    Egu g (BinTree.node T_L T_R) (fun z => D fstar z (S (BinTree.node T_L T_R))) = 0

def InRange (g : Summarizer Strings) (z : Strings) : Prop := ∃ x, z ∈ (g x).support

def L3 (g : Summarizer Strings) (fstar : Strings → Y) : Prop :=
  ∀ Z, InRange g Z → Eg g (fun z => D fstar z Z) Z = 0

/-
Nodewise Preservation: If L1 and L2 hold for T, then for any subtree u of T, the expected distortion is 0.
-/
theorem nodewise_preservation (g : Summarizer Strings) (T : BinTree Strings) (u : BinTree Strings) (fstar : Strings → Y)
  (h_sub : u ∈ subtrees T) (h1 : L1 g T fstar) (h2 : L2 g T fstar) :
  Egu g u (fun z => D fstar z (S u)) = 0 := by
    revert h_sub h1 h2;
    rintro hu h1 h2;
    induction' T with T_L T_R hT_L hT_R generalizing u;
    · cases hu;
      · convert h1 T_L ?_;
        exact?;
      · contradiction;
    · -- Since $u$ is in the subtrees of $T_R.node hT_L$, it must be either in the subtrees of $T_R$ or in the subtrees of $hT_L$.
      by_cases hu_T_R : u ∈ subtrees T_R;
      · apply hT_R u hu_T_R;
        · intro b hb;
          apply h1 b;
          exact List.mem_append_left _ hb;
        · intro p hp;
          apply h2;
          exact List.mem_cons_of_mem _ ( List.mem_append_left _ hp );
      · by_cases hu_hT_L : u ∈ subtrees hT_L;
        · rename_i ih;
          apply ih u hu_hT_L;
          · intro b hb;
            exact h1 b ( by
              exact List.mem_append_right _ hb );
          · intro p hp;
            apply h2;
            -- Since $p$ is in the internal nodes of $hT_L$, it must be in the internal nodes of $T_R.node hT_L$ as well.
            simp [internal_nodes] at hp ⊢;
            exact Or.inr <| Or.inr hp;
        · cases hu;
          · exact h2 ( T_R, hT_L ) ( by simp +decide [ internal_nodes ] );
          · cases List.mem_append.mp ‹_› <;> tauto

/-
One-Pass Preservation: If L1 and L2 hold, then the expected distortion of the reduction of the root is 0.
-/
theorem one_pass (g : Summarizer Strings) (T : BinTree Strings) (x : Strings) (fstar : Strings → Y)
  (hp : S T = x) (h1 : L1 g T fstar) (h2 : L2 g T fstar) :
  Egu g (root T) (fun z => D fstar z x) = 0 := by
    have h_root : root T ∈ subtrees T := by
      cases T <;> tauto;
    have := nodewise_preservation g T ( root T ) fstar h_root h1 h2; aesop;

/-
Schedule Invariance: If two trees have the same leaves, and L1/L2 hold for both, then their expected distortions are equal (both 0).
-/
theorem schedule_invariance (g : Summarizer Strings) (T T' : BinTree Strings) (fstar : Strings → Y)
  (h_l : leaves T = leaves T') (h1 : L1 g T fstar) (h2 : L2 g T fstar) (h1' : L1 g T' fstar) (h2' : L2 g T' fstar) :
  Egu g (root T) (fun z => D fstar z (S T)) = Egu g (root T') (fun z => D fstar z (S T')) := by
    -- By definition of expected distortion, we know that if the leaves of two trees are the same, then their expected distortions are equal.
    have h_eq_dist : Egu g (root T) (fun z => D fstar z (S T)) = 0 ∧ Egu g (root T') (fun z => D fstar z (S T')) = 0 := by
      exact ⟨ one_pass g T ( S T ) fstar rfl h1 h2, one_pass g T' ( S T' ) fstar rfl h1' h2' ⟩;
    rw [ h_eq_dist.1, h_eq_dist.2 ]

/-
Fold-of-Folds Invariance: If L1, L2, and L3 hold, then the expected distortion is 0.
-/
theorem fold_of_folds (g : Summarizer Strings) (T_comp : BinTree Strings) (x : Strings) (fstar : Strings → Y)
  (hp : S T_comp = x) (h1 : L1 g T_comp fstar) (h2 : L2 g T_comp fstar) (h3 : L3 g fstar) :
  Egu g (root T_comp) (fun z => D fstar z x) = 0 := by
    exact?

/-
Any string in the support of reduce g T is in the range of g.
-/
theorem reduce_support_in_range (g : Summarizer Strings) (T : BinTree Strings) :
  ∀ z ∈ (reduce g T).support, InRange g z := by
    intro z hz;
    induction' T with T_L T_R ih_L ih_R;
    · exact ⟨ T_L, hz ⟩;
    · unfold reduce at hz;
      contrapose! hz; simp_all +decide [ PMF.support ] ;
      intro x hx y hy; unfold InRange at hz; aesop;

/-
For R >= 1, any string in the support of ZR is in the range of g.
-/
theorem ZR_support_in_range (g : Summarizer Strings) (x : Strings) (R : ℕ) (T : BinTree Strings) (hR : R ≥ 1) :
  ∀ z ∈ (ZR g x R T).support, InRange g z := by
    induction' hR with R hR ih generalizing x T;
    · exact?;
    · intro z hz;
      -- By definition of bind, there exists some y in (ZR g x R T).support such that z is in the support of g y.
      obtain ⟨y, hy⟩ : ∃ y ∈ (ZR g x R T).support, z ∈ (g y).support := by
        have h_bind : (ZR g x (Nat.succ R) T) = (ZR g x R T).bind g := by
          cases R <;> tauto;
        contrapose! hz; aesop;
      exact ⟨ y, hy.2 ⟩

/-
Definition of Expectation over a PMF.
-/
def Exp {α : Type*} (p : PMF α) (f : α → ℝ) : ℝ := ∑' z, (p z).toReal * f z

/-
Helper lemma: The expected distortion added by one more round of summarization is 0, because the input to the new round is in the range of g (by previous rounds) and L3 ensures idempotence on the range.
-/
lemma multi_round_step (g : Summarizer Strings) (x : Strings) (R : ℕ) (T : BinTree Strings) (fstar : Strings → Y)
  (h3 : L3 g fstar) (h_supp : ∀ z ∈ (ZR g x R T).support, InRange g z) :
  Exp (ZR g x R T) (fun z => Eg g (fun w => D fstar w z) z) = 0 := by
    unfold Exp;
    convert tsum_zero with z;
    by_cases hz : z ∈ ( ZR g x R T ).support <;> aesop

/-
Definition of ExpENN (Expectation in ENNReal) and Law of Iterated Expectation for ExpENN.
-/
def ExpENN {α : Type*} (p : PMF α) (f : α → ENNReal) : ENNReal := ∑' z, p z * f z

lemma ExpENN_bind {α : Type*} (p : PMF α) (g : α → PMF α) (f : α → ENNReal) :
  ExpENN (p.bind g) f = ExpENN p (fun x => ExpENN (g x) f) := by
    unfold ExpENN;
    simp +decide [ PMF.bind_apply, mul_assoc, mul_comm, mul_left_comm, ← ENNReal.tsum_mul_left ];
    rw [ ← ENNReal.tsum_comm ]

/-
Relating Exp (Real) and ExpENN (ENNReal) for non-negative functions.
-/
lemma Exp_eq_ExpENN_toReal {α : Type*} (p : PMF α) (f : α → ℝ) (hf : ∀ x, 0 ≤ f x) :
  Exp p f = (ExpENN p (fun x => ENNReal.ofReal (f x))).toReal := by
    unfold Exp ExpENN;
    rw [ ENNReal.tsum_toReal_eq ];
    · rw [ tsum_congr ] ; intros ; rw [ ENNReal.toReal_mul ] ; aesop;
    · exact fun x => ENNReal.mul_ne_top ( p.apply_ne_top x ) ( ENNReal.ofReal_ne_top )

/-
If a summable series of non-negative real numbers sums to 0, then each term is 0.
-/
lemma tsum_eq_zero_of_nonneg {α : Type*} (f : α → ℝ) (hf : ∀ x, 0 ≤ f x) (h_summable : Summable f) (h_sum : ∑' x, f x = 0) :
  ∀ x, f x = 0 := by
    contrapose! h_sum;
    exact ne_of_gt ( lt_of_lt_of_le ( lt_of_le_of_ne ( hf _ ) ( Ne.symm h_sum.choose_spec ) ) ( Summable.le_tsum h_summable _ fun x _ => hf x ) )

/-
If L3 holds and the expected distortion is summable, then distortion is 0 on the support.
-/
lemma L3_implies_dist_zero_on_support (g : Summarizer Strings) (fstar : Strings → Y) (h3 : L3 g fstar) (Z : Strings) (hZ : InRange g Z)
  (h_summable : Summable (fun z => (g Z z).toReal * D fstar z Z)) :
  ∀ z ∈ (g Z).support, D fstar z Z = 0 := by
    -- By definition of $L3$, we know that $\sum_{z} (g Z z).toReal * D fstar z Z = 0$.
    have h_sum_zero : ∑' z, (g Z z).toReal * D fstar z Z = 0 := by
      exact?;
    intro z hz; contrapose! h_sum_zero; simp_all +decide [ dist_eq_zero ] ;
    refine' ne_of_gt ( lt_of_lt_of_le _ ( Summable.le_tsum _ z _ ) );
    · exact mul_pos ( ENNReal.toReal_pos hz ( by
        exact? ) ) ( lt_of_le_of_ne ( dist_nonneg ) ( Ne.symm h_sum_zero ) );
    · exact h_summable;
    · exact fun _ _ => mul_nonneg ( ENNReal.toReal_nonneg ) ( dist_nonneg )

/-
If L3 holds, then each term in the expected distortion sum is zero.
-/
lemma L3_implies_term_zero (g : Summarizer Strings) (fstar : Strings → Y) (h3 : L3 g fstar) (Z : Strings) (hZ : InRange g Z)
  (h_summable : Summable (fun z => (g Z z).toReal * D fstar z Z)) :
  ∀ z, (g Z z).toReal * D fstar z Z = 0 := by
    -- Since (g Z z).toReal is zero when z is not in the support of g Z, the product is zero.
    intros z
    by_cases hz : z ∈ (g Z).support
    · exact (by
      have h_dist_zero : D fstar z Z = 0 := by
        apply L3_implies_dist_zero_on_support g fstar h3 Z hZ h_summable z hz;
      rw [ h_dist_zero, MulZeroClass.mul_zero ])
    · exact (by
      aesop)

/-
If L3 holds and expected distortion is summable, then ExpENN of distortion is 0.
-/
lemma L3_implies_ExpENN_zero (g : Summarizer Strings) (fstar : Strings → Y) (h3 : L3 g fstar) (Z : Strings) (hZ : InRange g Z)
  (h_summable : Summable (fun z => (g Z z).toReal * D fstar z Z)) :
  ExpENN (g Z) (fun z => ENNReal.ofReal (D fstar z Z)) = 0 := by
    -- Since each term in the sum is zero, the sum itself is zero.
    have h_zero_terms : ∀ z, (g Z z) * ENNReal.ofReal (D fstar z Z) = 0 := by
      by_contra h_nonzero;
      -- By definition of L3, we know that for any Z in the range of g, the expected distortion is zero.
      have h_exp_zero : ∀ z ∈ (g Z).support, D fstar z Z = 0 := by
        exact?;
      aesop;
    exact ENNReal.tsum_eq_zero.mpr fun _ => h_zero_terms _