#!/usr/bin/env python3
"""Plot IPW stress-ladder results from run_ipw_stress_ladder.py outputs."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Dict, List, Sequence

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Plot IPW stress-ladder summary curves.")
    p.add_argument(
        "--input-csv",
        type=str,
        default="outputs/ipw_stress_ladder/summary_rows.csv",
        help="Summary CSV generated by run_ipw_stress_ladder.py.",
    )
    p.add_argument(
        "--output-figure",
        type=str,
        default="outputs/ipw_stress_ladder/stress_ladder.png",
        help="Output figure path.",
    )
    p.add_argument(
        "--output-json",
        type=str,
        default="outputs/ipw_stress_ladder/stress_ladder_plot_report.json",
        help="Output JSON report path.",
    )
    p.add_argument(
        "--target-coverage",
        type=float,
        default=0.90,
        help="Nominal target coverage (1-delta).",
    )
    p.add_argument(
        "--metric",
        choices=["violation", "preference"],
        default="violation",
        help="Which endpoint to plot.",
    )
    return p.parse_args()


def _load_rows(path: Path) -> List[Dict[str, str]]:
    rows: List[Dict[str, str]] = []
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(dict(row))
    return rows


def _to_float(row: Dict[str, str], key: str) -> float:
    return float(row[key])


def _to_int(row: Dict[str, str], key: str) -> int:
    return int(float(row[key]))


def _group_by_case(rows: Sequence[Dict[str, str]]) -> Dict[str, List[Dict[str, str]]]:
    out: Dict[str, List[Dict[str, str]]] = {}
    for row in rows:
        out.setdefault(str(row["case"]), []).append(row)
    for k in list(out.keys()):
        out[k] = sorted(out[k], key=lambda r: _to_int(r, "n_docs"))
    return out


def _display_case(case: str) -> str:
    mapping = {
        "control_balanced_bernoulli": "Control (Balanced, Bernoulli)",
        "stress_adversarial_bernoulli": "Stress (Adversarial, Bernoulli)",
        "stress_adversarial_wor": "Stress (Adversarial, WOR)",
        "hard_control_additive_balanced": "Hard Control (Additive, Balanced)",
        "hard_topk_spike_adversarial": "Hard Stress (Top-k Spike, Adversarial)",
        "hard_hybrid_boundary_adversarial": "Hard Stress (Boundary Hybrid, Adversarial WOR)",
        "hard_quorum_backloaded_severe": "Hard Stress (Quorum, Backloaded Severe WOR)",
    }
    return mapping.get(case, case.replace("_", " "))


def main() -> int:
    args = parse_args()
    in_csv = Path(args.input_csv)
    rows = _load_rows(in_csv)
    if len(rows) == 0:
        raise ValueError(f"no rows in: {in_csv}")

    metric = str(args.metric)
    cov_key = f"{metric}_coverage_mean"
    cov_std_key = f"{metric}_coverage_std"
    naive_cov_key = f"naive_{metric}_coverage_mean"
    naive_cov_std_key = f"naive_{metric}_coverage_std"
    width_key = f"{metric}_mean_width_mean"
    width_std_key = f"{metric}_mean_width_std"
    naive_width_key = f"naive_{metric}_mean_width_mean"
    naive_width_std_key = f"naive_{metric}_mean_width_std"
    bias_key = f"ipw_{metric}_bias_mean"
    bias_std_key = f"ipw_{metric}_bias_std"
    naive_bias_key = f"naive_{metric}_bias_mean"
    naive_bias_std_key = f"naive_{metric}_bias_std"

    by_case = _group_by_case(rows)
    case_order = sorted(by_case.keys())
    colors = {
        "control_balanced_bernoulli": "#1f77b4",
        "stress_adversarial_bernoulli": "#d62728",
        "stress_adversarial_wor": "#2ca02c",
        "hard_control_additive_balanced": "#9467bd",
        "hard_topk_spike_adversarial": "#ff7f0e",
        "hard_hybrid_boundary_adversarial": "#8c564b",
        "hard_quorum_backloaded_severe": "#e377c2",
    }

    fig, axes = plt.subplots(2, 2, figsize=(13, 8.5), constrained_layout=True)
    ax_cov = axes[0, 0]
    ax_bias = axes[0, 1]
    ax_width = axes[1, 0]
    ax_neff = axes[1, 1]

    for case in case_order:
        grp = by_case[case]
        color = colors.get(case, "#444444")
        label = _display_case(case)
        xs = [_to_int(r, "n_docs") for r in grp]

        ipw_cov = [_to_float(r, cov_key) for r in grp]
        ipw_cov_std = [_to_float(r, cov_std_key) for r in grp]
        naive_cov = [_to_float(r, naive_cov_key) for r in grp]
        naive_cov_std = [_to_float(r, naive_cov_std_key) for r in grp]

        ipw_bias = [_to_float(r, bias_key) for r in grp]
        ipw_bias_std = [_to_float(r, bias_std_key) for r in grp]
        naive_bias = [_to_float(r, naive_bias_key) for r in grp]
        naive_bias_std = [_to_float(r, naive_bias_std_key) for r in grp]

        ipw_width = [_to_float(r, width_key) for r in grp]
        ipw_width_std = [_to_float(r, width_std_key) for r in grp]
        naive_width = [_to_float(r, naive_width_key) for r in grp]
        naive_width_std = [_to_float(r, naive_width_std_key) for r in grp]

        neff = [_to_float(r, "mean_effective_sample_size_mean") for r in grp]
        neff_std = [_to_float(r, "mean_effective_sample_size_std") for r in grp]

        ax_cov.errorbar(
            xs,
            ipw_cov,
            yerr=ipw_cov_std,
            marker="o",
            linestyle="-",
            linewidth=2.0,
            color=color,
            capsize=2,
            label=f"{label} | IPW",
        )
        ax_cov.errorbar(
            xs,
            naive_cov,
            yerr=naive_cov_std,
            marker="o",
            linestyle="--",
            linewidth=1.8,
            color=color,
            capsize=2,
            alpha=0.9,
            label=f"{label} | Naive",
        )

        ax_bias.errorbar(
            xs,
            ipw_bias,
            yerr=ipw_bias_std,
            marker="s",
            linestyle="-",
            linewidth=2.0,
            color=color,
            capsize=2,
            label=f"{label} | IPW",
        )
        ax_bias.errorbar(
            xs,
            naive_bias,
            yerr=naive_bias_std,
            marker="s",
            linestyle="--",
            linewidth=1.8,
            color=color,
            capsize=2,
            alpha=0.9,
            label=f"{label} | Naive",
        )

        ax_width.errorbar(
            xs,
            ipw_width,
            yerr=ipw_width_std,
            marker="^",
            linestyle="-",
            linewidth=2.0,
            color=color,
            capsize=2,
            label=f"{label} | IPW",
        )
        ax_width.errorbar(
            xs,
            naive_width,
            yerr=naive_width_std,
            marker="^",
            linestyle="--",
            linewidth=1.8,
            color=color,
            capsize=2,
            alpha=0.9,
            label=f"{label} | Naive",
        )

        ax_neff.errorbar(
            xs,
            neff,
            yerr=neff_std,
            marker="d",
            linestyle="-",
            linewidth=2.0,
            color=color,
            capsize=2,
            label=label,
        )

    ax_cov.axhline(float(args.target_coverage), color="#222222", linestyle=":", linewidth=1.2, label="Target")
    ax_cov.set_ylim(0.0, 1.03)
    ax_cov.set_xscale("log")
    ax_cov.set_title(f"{metric.capitalize()} Coverage")
    ax_cov.set_xlabel("n_docs")
    ax_cov.set_ylabel("Coverage")
    ax_cov.grid(alpha=0.25)

    ax_bias.axhline(0.0, color="#222222", linestyle=":", linewidth=1.2)
    ax_bias.set_xscale("log")
    ax_bias.set_title(f"{metric.capitalize()} Bias")
    ax_bias.set_xlabel("n_docs")
    ax_bias.set_ylabel("Signed bias")
    ax_bias.grid(alpha=0.25)

    ax_width.set_xscale("log")
    ax_width.set_title(f"{metric.capitalize()} CI Width")
    ax_width.set_xlabel("n_docs")
    ax_width.set_ylabel("Mean interval width")
    ax_width.grid(alpha=0.25)

    ax_neff.set_xscale("log")
    ax_neff.set_title("Effective Sample Size (n_eff)")
    ax_neff.set_xlabel("n_docs")
    ax_neff.set_ylabel("Mean n_eff")
    ax_neff.grid(alpha=0.25)

    # De-duplicate legend entries.
    handles: List[object] = []
    labels: List[str] = []
    for ax in (ax_cov, ax_bias, ax_width, ax_neff):
        h, l = ax.get_legend_handles_labels()
        handles.extend(h)
        labels.extend(l)
    dedup: Dict[str, object] = {}
    for h, l in zip(handles, labels):
        if l not in dedup:
            dedup[l] = h
    fig.legend(dedup.values(), dedup.keys(), loc="upper center", ncol=3, fontsize=8, frameon=False)

    fig.suptitle(
        f"IPW Stress Ladder ({metric}) | target coverage={float(args.target_coverage):.2f}",
        fontsize=12,
    )

    out_fig = Path(args.output_figure)
    out_fig.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_fig, dpi=220)
    plt.close(fig)

    # Compute a compact textual summary for fast inspection.
    summary_rows: List[Dict[str, float | int | str]] = []
    for case in case_order:
        grp = by_case[case]
        if len(grp) == 0:
            continue
        first = grp[0]
        last = grp[-1]
        summary_rows.append(
            {
                "case": case,
                "display_name": _display_case(case),
                "sampling_design": str(first["sampling_design"]),
                "n_docs_min": _to_int(first, "n_docs"),
                "n_docs_max": _to_int(last, "n_docs"),
                "ipw_coverage_min_docs": _to_float(first, cov_key),
                "ipw_coverage_max_docs": _to_float(last, cov_key),
                "naive_coverage_min_docs": _to_float(first, naive_cov_key),
                "naive_coverage_max_docs": _to_float(last, naive_cov_key),
                "ipw_bias_max_docs": _to_float(last, bias_key),
                "naive_bias_max_docs": _to_float(last, naive_bias_key),
                "ipw_width_max_docs": _to_float(last, width_key),
                "naive_width_max_docs": _to_float(last, naive_width_key),
                "mean_neff_max_docs": _to_float(last, "mean_effective_sample_size_mean"),
            }
        )

    report = {
        "input_csv": str(in_csv),
        "output_figure": str(out_fig),
        "metric": metric,
        "target_coverage": float(args.target_coverage),
        "n_rows": len(rows),
        "n_cases": len(case_order),
        "cases": case_order,
        "summary_rows": summary_rows,
    }
    out_json = Path(args.output_json)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")

    print(json.dumps({"output_figure": str(out_fig), "output_json": str(out_json)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
