#!/usr/bin/env bash
# Round 5: data-scaling sweep.
#
# Question: how much of the count_mae gap between flexible learners
# (jax_fno + count_only @ leaf=128 ≈ 0.87) and the architectural ceiling
# (regime_transition_sum @ leaf=128 ≈ 0.005) is sample complexity?
#
# Variable: train_docs ∈ {1024, 10240, 102400}.
# Constants: same Markov hazard panel DGP (paper_hazard_panel_v1_t128),
# n_iter=4000, batch=128, seed=0.
#
# Cells (30 total):
#   * jax_fno + count_only + fully_learned : 2 enc × 2 leaves × 3 sizes = 12
#   * jax_fno + sketch + analytic          : 2 enc × 2 leaves × 3 sizes = 12
#   * regime_transition_sum + sketch       : 1 enc × 2 leaves × 3 sizes =  6
#
# The 1024 and 10240 cells reuse the existing 10240-doc bundle (with
# --train-docs subsampling for 1024). The 102400 cells use a fresh
# bundle generated by:
#   ./venv/bin/python scripts/prepare_markov_hazard_panel_data.py \
#       --panel-ids paper_hazard_panel_v1_t128 \
#       --train-docs 102400 --seed 0 \
#       --bundle-root outputs/_bundles/markov_hazard_panels_train102400 \
#       --skip-prepared-cache
set -euo pipefail
source venv/bin/activate

STAMP="${STAMP:-$(date -u +%Y%m%d_%H%M%S)}"
OUT_ROOT="${OUT_ROOT:-outputs/markov_fno_round5_data_scaling_${STAMP}}"
BUNDLE_BASE="${BUNDLE_BASE:-outputs/_bundles/markov_hazard_panels/paper_hazard_panel_v1_t128/seed_0/base_bundle.json}"
BUNDLE_102400="${BUNDLE_102400:-outputs/_bundles/markov_hazard_panels_train102400/paper_hazard_panel_v1_t128/seed_0/base_bundle.json}"
GPUS="${GPUS:-0,2,3}"
N_ITER="${N_ITER:-4000}"

# Sanity: BUNDLE_102400 must exist before launching the full sweep.
if [ ! -f "$BUNDLE_102400" ]; then
  echo "ERROR: 102400-doc bundle not found at: $BUNDLE_102400"
  echo "Generate it first:"
  echo "  ./venv/bin/python scripts/prepare_markov_hazard_panel_data.py \\"
  echo "    --panel-ids paper_hazard_panel_v1_t128 --train-docs 102400 --seed 0 \\"
  echo "    --bundle-root outputs/_bundles/markov_hazard_panels_train102400 \\"
  echo "    --skip-prepared-cache"
  exit 1
fi
if [ ! -f "$BUNDLE_BASE" ]; then
  echo "ERROR: base bundle not found at: $BUNDLE_BASE"
  exit 1
fi

IFS=',' read -r -a GPU_LIST <<<"$GPUS"
N_GPUS="${#GPU_LIST[@]}"
mkdir -p "$OUT_ROOT/lanes"

# Cell spec format:
# label|family|encoding|leaf|arch|c2|count_only|train_docs
CELLS=()

# Family A: jax_fno + count_only + fully_learned
for train_docs in 102400 10240 1024; do
  for encoding in regime_one_hot one_hot_token_ids; do
    for leaf in 64 128; do
      label="jax_fno_count_only__${encoding}__leaf${leaf}__train${train_docs}"
      CELLS+=("${label}|jax_fno|$encoding|$leaf|fully_learned|theta|1|$train_docs")
    done
  done
done

# Family B: jax_fno + sketch + analytic
for train_docs in 102400 10240 1024; do
  for encoding in regime_one_hot one_hot_token_ids; do
    for leaf in 64 128; do
      label="jax_fno_sketch__${encoding}__leaf${leaf}__train${train_docs}"
      CELLS+=("${label}|jax_fno|$encoding|$leaf|analytic|theta|0|$train_docs")
    done
  done
done

# Family C: regime_transition_sum + sketch + analytic (regime_one_hot only)
for train_docs in 102400 10240 1024; do
  for leaf in 64 128; do
    label="regime_transition_sum__regime_one_hot__leaf${leaf}__train${train_docs}"
    CELLS+=("${label}|regime_transition_sum|regime_one_hot|$leaf|analytic|theta|0|$train_docs")
  done
done

echo "Total cells: ${#CELLS[@]}"
echo "GPUs: ${GPUS} (N=${N_GPUS})"
echo "Output: $OUT_ROOT"

run_cell() {
  local label="$1" fam="$2" enc="$3" leaf="$4" arch="$5" c2="$6"
  local count_only="$7" train_docs="$8" gpu="$9"
  local out="$OUT_ROOT/$label"
  if [ -f "$out/summary.json" ]; then echo "[gpu$gpu] skip $label"; return 0; fi

  # Bundle selection: 102400 cells use the new bundle, 1024 + 10240 cells
  # reuse the existing 10240-doc bundle (subsampling via --train-docs).
  local bundle_path
  if [ "$train_docs" -ge 102400 ]; then
    bundle_path="$BUNDLE_102400"
  else
    bundle_path="$BUNDLE_BASE"
  fi

  # FNO modes: matches Round 3/4 schedule. leaf 64 → 32, leaf 128 → 32.
  local n_modes
  if [ "$leaf" -le 16 ]; then n_modes=8
  elif [ "$leaf" -le 32 ]; then n_modes=16
  else n_modes=32
  fi

  local count_args=()
  local idemp_w=1.0
  if [ "$count_only" = "1" ]; then
    count_args+=(--local-law-count-only --local-law-rep-dim 0)
    idemp_w=0.0
  fi

  # FNO args only emitted for FNO families; regime_transition_sum
  # ignores them but accepts them harmlessly.
  local fno_args=()
  if [ "$fam" = "jax_fno" ]; then
    fno_args+=(
      --local-law-summary-fno-n-modes "$n_modes"
      --local-law-summary-fno-n-layers 3
      --local-law-summary-fno-pooling-mode sum
    )
  fi

  echo "[gpu$gpu] start $label (train=$train_docs)"
  CUDA_VISIBLE_DEVICES="$gpu" \
  XLA_PYTHON_CLIENT_PREALLOCATE=false \
  XLA_PYTHON_CLIENT_MEM_FRACTION=0.30 \
  ./venv/bin/ctreepo sim run contextual-sbijax \
    --data-source markov \
    --load-data-bundle "$bundle_path" \
    --sbijax-trainer learned_local_laws \
    --sbijax-method nasss \
    --sbijax-package-theta markov_exact_sketch \
    --sbijax-input-encoding "$enc" \
    --local-law-summary-family "$fam" \
    --law-architecture "$arch" \
    --c2-merge-target "$c2" \
    --learned-merge-hidden-dim 128 \
    --learned-decoder-hidden-dim 128 \
    --train-docs "$train_docs" --val-docs 256 --test-docs 256 \
    --fragment-len "$leaf" \
    --context-samples-per-doc 1 \
    --response-signature-contexts 16 --response-signature-slices 8 \
    --embedding-dim 64 --state-dim 25 --hidden-dim 128 \
    --learning-rate 0.0003 --lr-schedule cosine \
    --n-iter "$N_ITER" --batch-size 128 \
    --local-law-weight 1.0 --local-law-leaf-weight 1.0 --local-law-merge-weight 1.0 \
    --local-law-idempotence-weight "$idemp_w" \
    --local-law-contextual-weight 1.0 --local-law-package-weight 0.0 \
    --seed 0 \
    --output-root "$out" \
    "${fno_args[@]}" "${count_args[@]}" >"$OUT_ROOT/lanes/${label}.log" 2>&1
  echo "[gpu$gpu] done $label"
}

declare -A LANE_PIDS
for ((i=0; i<N_GPUS; i++)); do
  gpu="${GPU_LIST[$i]}"
  (
    for ((j=i; j<${#CELLS[@]}; j+=N_GPUS)); do
      cell_spec="${CELLS[$j]}"
      IFS='|' read -r label fam enc leaf arch c2 co td <<<"$cell_spec"
      run_cell "$label" "$fam" "$enc" "$leaf" "$arch" "$c2" "$co" "$td" "$gpu"
    done
  ) >"$OUT_ROOT/lanes/lane_gpu${gpu}.log" 2>&1 &
  LANE_PIDS[$gpu]=$!
done

for pid in "${LANE_PIDS[@]}"; do wait "$pid" || true; done

# Aggregate to CSV: one row per cell, all Round 4 schema columns + n_train_docs.
./venv/bin/python - <<PY
import json, csv, os
root = "$OUT_ROOT"
rows = []
for cell in sorted(os.listdir(root)):
    sj = os.path.join(root, cell, "summary.json")
    if not os.path.exists(sj):
        continue
    try:
        d = json.load(open(sj))
    except Exception as exc:
        print(f"  skip {sj}: {exc}")
        continue
    test = d.get("diagnostics", {}).get("test", {})
    prov = d.get("provenance", {})
    rows.append({
        "cell": cell,
        "family": prov.get("local_law_summary_family"),
        "input_encoding": d.get("input_encoding"),
        "fragment_len": prov.get("fragment_len"),
        "law_arch": prov.get("law_architecture"),
        "count_only": prov.get("local_law_count_only"),
        "n_train_docs": prov.get("n_train_docs") or prov.get("train_docs"),
        "supervision_mode": test.get("supervision_mode"),
        "theta_count_raw_mae": test.get("theta_count_raw_mae"),
        "theta_first_regime_accuracy": test.get("theta_first_regime_accuracy"),
        "theta_last_regime_accuracy": test.get("theta_last_regime_accuracy"),
        "eps_leaf": test.get("eps_leaf"),
        "eps_merge": test.get("eps_merge"),
        "leaf_count_jsd": test.get("sufficiency_leaf_rep_count_jsd_loss"),
        "leaf_count_proxy": test.get("sufficiency_leaf_rep_count_proxy"),
        "merge_count_jsd": test.get("sufficiency_merge_rep_count_jsd_loss"),
        "merge_count_proxy": test.get("sufficiency_merge_rep_count_proxy"),
    })

if rows:
    fields = list(rows[0].keys())
    csv_path = os.path.join(root, "data_scaling_summary.csv")
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {csv_path} ({len(rows)} rows)")
PY

echo ">>> Round 5 data-scaling sweep complete: $OUT_ROOT"
