import FormalProofs.Econometrics.Core

/-!
# FormalProofs/Econometrics/Assumptions.lean

Assumption bundles for potential outcomes and IPW identification.
Assumptions are expressed as structures so they remain explicit parameters,
not global axioms.
-/

set_option linter.mathlibStandardSet false

open scoped Classical
open scoped MeasureTheory
open MeasureTheory

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace Econometrics

/-!
## Sigma-algebra Helpers
-/

/-- Sigma-algebra generated by covariates X. -/
def sigmaX {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α] (X : Ω → α) :
    MeasurableSpace Ω :=
  MeasurableSpace.comap X ‹_›

/-- Sigma-algebra generated by treatment D. -/
def sigmaD {Ω : Type*} [MeasurableSpace Ω] (D : Ω → Treatment) : MeasurableSpace Ω :=
  MeasurableSpace.comap D inferInstance

/-- Joint sigma-algebra generated by (X, D). -/
def sigmaXD {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    (X : Ω → α) (D : Ω → Treatment) : MeasurableSpace Ω :=
  sigmaX X ⊔ sigmaD D

/-!
## Core Assumptions
-/

/-- Consistency (SUTVA): observed outcome equals the potential outcome under realized treatment.

Formally:
  Y = D * Y1 + (1 - D) * Y0
-/
structure Consistency {Ω : Type*} (D : Ω → Treatment)
    (po : PotentialOutcomes Ω) (Y : Ω → ℝ) : Prop where
  obs_eq : Y = observedOutcome D po

/-- Integrability of potential outcomes (needed for conditional expectations). -/
structure IntegrablePotentialOutcomes {Ω : Type*} [MeasurableSpace Ω]
    (mu : Measure Ω) (po : PotentialOutcomes Ω) : Prop where
  y0_integrable : Integrable po.y0 mu
  y1_integrable : Integrable po.y1 mu

/-- Unconfoundedness (selection on observables).

We express this as conditional mean independence:
  E[Y0 | X, D] = E[Y0 | X]
  E[Y1 | X, D] = E[Y1 | X]

This is the minimal condition required for IPW identification.
-/
structure Unconfoundedness {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    (mu : Measure Ω) (X : Ω → α) (D : Ω → Treatment) (po : PotentialOutcomes Ω) : Prop where
  integrable : IntegrablePotentialOutcomes mu po
  y0_condexp_eq :
    mu[po.y0 | sigmaXD X D] =ᵐ[mu] mu[po.y0 | sigmaX X]
  y1_condexp_eq :
    mu[po.y1 | sigmaXD X D] =ᵐ[mu] mu[po.y1 | sigmaX X]

/-- Positivity (overlap) for a propensity score expressed as a random variable. -/
def PositivityRV {Ω : Type*} [MeasurableSpace Ω]
    (mu : Measure Ω) (e : Ω → ℝ) : Prop :=
  ∀ᵐ ω ∂mu, 0 < e ω ∧ e ω < 1

/-- Positivity (overlap) for a propensity score expressed as a function of X. -/
def Positivity {Ω α : Type*} [MeasurableSpace Ω] [MeasurableSpace α]
    (mu : Measure Ω) (X : Ω → α) (e : α → ℝ) : Prop :=
  ∀ᵐ ω ∂mu, 0 < e (X ω) ∧ e (X ω) < 1

end Econometrics
