import FormalProbability.Semiparametric
import FormalProbability.Econometrics.GMM
import FormalProbability.Econometrics.ConditionalMoments

/-!
# FormalProofs/Econometrics/Overidentification

Paper-facing re-exports for "Overidentification in Regular Models".

The generic proofs live in `FormalProbability`. This file exposes a curated API with docstrings that
record the corresponding numbered claims from the paper.
-/

set_option linter.mathlibStandardSet false

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace Econometrics
namespace OveridentificationRegularModels

open Semiparametric

/-- Paper Definition 2.1: differentiable-in-quadratic-mean paths. -/
abbrev DQMPath (Ω : Type*) [MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
    [MeasureTheory.IsFiniteMeasure μ] :=
  Semiparametric.DQMPath Ω μ

/-- Concrete score space `L²₀(P)` generated by the mean-zero restriction. -/
abbrev CenteredScoreSpace (Ω : Type*) [MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
    [MeasureTheory.IsFiniteMeasure μ] :=
  Semiparametric.CenteredScoreSpace Ω μ

/-- Dominated-model square-root density notation. -/
abbrev squareRootDensity (Ω : Type*) [MeasurableSpace Ω]
    (ν μ : MeasureTheory.Measure Ω) :=
  Semiparametric.squareRootDensity ν μ

/-- Canonical local alternative scaling `h / √n`. -/
abbrev localAlternativeScale := Semiparametric.localAlternativeScale

/-- Base `n`-sample product law under the reference measure. -/
abbrev baseSampleMeasure (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ] (n : ℕ) :=
  Semiparametric.baseSampleMeasure μ n

/-- Product experiment induced by a concrete DQM path. -/
abbrev sampleMeasure (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ]
    (p : Semiparametric.DQMPath Ω μ) (n : ℕ) (t : ℝ) :=
  Semiparametric.sampleMeasure (μ := μ) p n t

/-- Coordinatewise sample log-likelihood ratio. -/
abbrev sampleLogLikelihoodRatio (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ]
    (p : Semiparametric.DQMPath Ω μ) (n : ℕ) (t : ℝ) :=
  Semiparametric.sampleLogLikelihoodRatio (μ := μ) p n t

/-- Normalized sample score sum attached to a DQM path. -/
abbrev normalizedScoreSum (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ]
    (p : Semiparametric.DQMPath Ω μ) (n : ℕ) :=
  Semiparametric.normalizedScoreSum (μ := μ) p n

/-- Witness that the coordinatewise sample log-likelihood ratio agrees with the true product
log-likelihood ratio. -/
abbrev ProductLogLikelihoodRatioWitness (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ]
    (p : Semiparametric.DQMPath Ω μ) (n : ℕ) (t : ℝ) :=
  Semiparametric.ProductLogLikelihoodRatioWitness (μ := μ) p n t

/-- Witness-backed quadratic product-LAN expansion. -/
abbrev ProductLANWitness (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ]
    (p : Semiparametric.DQMPath Ω μ) (h : ℝ) :=
  Semiparametric.ProductLANWitness (μ := μ) p h

/-- Exponentially tilted concrete local-alternative constructor. -/
abbrev ExponentialTiltPath (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ] :=
  Semiparametric.ExponentialTiltPath Ω μ

/-- Coordinatewise sample log-likelihood ratio for an exponential tilt. -/
abbrev exponentialTiltSampleLogLikelihoodRatio (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ]
    (tilt : Semiparametric.ExponentialTiltPath Ω μ) (n : ℕ) (t : ℝ) :=
  Semiparametric.exponentialTiltSampleLogLikelihoodRatio (μ := μ) tilt n t

/-- Finite probe families for finite-dimensional local-alternative statistics. -/
abbrev FiniteProbeFamily (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ] (d : ℕ) :=
  Semiparametric.FiniteProbeFamily (Ω := Ω) (μ := μ) d

/-- Bundled finite-dimensional CLT interface. -/
abbrev FiniteProbeCLT (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    {d : ℕ} (seq : ℕ → Ω → EuclideanSpace ℝ (Fin d))
    (limit : Ω → EuclideanSpace ℝ (Fin d)) : Prop :=
  ProbabilityTheory.FiniteProbeCLT (Ω := Ω) (μ := μ) seq limit

/-- Cramér-Wold witness interface for finite-dimensional CLTs. -/
abbrev CramerWoldWitness (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    {d : ℕ} (seq : ℕ → Ω → EuclideanSpace ℝ (Fin d))
    (limit : Ω → EuclideanSpace ℝ (Fin d)) : Prop :=
  ProbabilityTheory.CramerWoldWitness (Ω := Ω) (μ := μ) seq limit

/-- Witness-backed finite-probe third-lemma conclusion. -/
abbrev FiniteProbeThirdLemmaWitness (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure μ]
    [MeasureTheory.IsFiniteMeasure μ]
    {d : ℕ} (probes : Semiparametric.FiniteProbeFamily (Ω := Ω) (μ := μ) d)
    (g : Semiparametric.CenteredScoreSpace Ω μ) :=
  Semiparametric.FiniteProbeThirdLemmaWitness (μ := μ) probes g

/-- Concrete path-generated tangent space in centered `L²₀(P)`. -/
abbrev pathwiseTangentSpace (Ω : Type*) [MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
    [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ)) :=
  Semiparametric.dqmTangentSpace (μ := μ) paths

/-- First-order expansion along a local-alternative sequence. -/
abbrev HasFirstOrderLocalExperimentExpansion (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsFiniteMeasure μ]
    (p : Semiparametric.DQMPath Ω μ) (τ : ℕ → ℝ) : Prop :=
  Semiparametric.HasFirstOrderLocalExperimentExpansion (μ := μ) p τ

/-- Absolute-continuity contiguity of a local-alternative sequence to the base model. -/
abbrev LocallyContiguous (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsFiniteMeasure μ]
    (p : Semiparametric.DQMPath Ω μ) (τ : ℕ → ℝ) : Prop :=
  Semiparametric.LocallyContiguous (μ := μ) p τ

/-- Concrete Gaussian-shift experiment attached to a dominated DQM family. -/
abbrev ConcreteGaussianShiftExperiment (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ)) :=
  Semiparametric.ConcreteGaussianShiftExperiment (μ := μ) paths

/-- Concrete local just identification from DQM paths. -/
abbrev IsPathwiseLocallyJustIdentified (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ)) : Prop :=
  Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) paths

/-- Concrete local overidentification from DQM paths. -/
abbrev IsPathwiseLocallyOveridentified (Ω : Type*) [MeasurableSpace Ω]
    (μ : MeasureTheory.Measure Ω) [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ)) : Prop :=
  Semiparametric.IsPathwiseLocallyOveridentified (μ := μ) paths

/-- Paper Definition 2.2: local just identification. -/
abbrev IsLocallyJustIdentified {H : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (T : Semiparametric.TangentSpace H) : Prop :=
  Semiparametric.IsLocallyJustIdentified T

/-- Paper Definition 2.2: local overidentification. -/
abbrev IsLocallyOveridentified {H : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (T : Semiparametric.TangentSpace H) : Prop :=
  Semiparametric.IsLocallyOveridentified T

/-- Concrete DQM path scores belong to the tangent space they generate. -/
theorem dqmPathScore_mem_pathwiseTangentSpace
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω} [MeasureTheory.IsFiniteMeasure μ]
    {paths : Set (Semiparametric.DQMPath Ω μ)} {p : Semiparametric.DQMPath Ω μ}
    (hp : p ∈ paths) :
    p.scoreDirection ∈ Semiparametric.dqmTangentSpace (μ := μ) paths :=
  Semiparametric.DQMPath.scoreDirection_mem_dqmTangentSpace (μ := μ) hp

/-- Dominated-path log-likelihood ratios vanish at the base point. -/
theorem localLogLikelihoodRatio_vanishesAtBase
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ] (p : Semiparametric.DQMPath Ω μ) :
    Semiparametric.localLogLikelihoodRatio p 0 =ᵐ[μ] 0 :=
  p.localLogLikelihoodRatio_atZero_ae_eq_zero

/-- Path-generated tangent spaces are monotone in the underlying path family. -/
theorem pathwiseTangentSpace_mono
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {paths₁ paths₂ : Set (Semiparametric.DQMPath Ω μ)} (h : paths₁ ⊆ paths₂) :
    Semiparametric.dqmTangentSpace (μ := μ) paths₁ ≤
      Semiparametric.dqmTangentSpace (μ := μ) paths₂ :=
  Semiparametric.dqmTangentSpace_mono (μ := μ) h

/-- Unions of path families generate the closed supremum of the individual tangent spaces. -/
theorem pathwiseTangentSpace_union_eq_closedSup
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    (paths₁ paths₂ : Set (Semiparametric.DQMPath Ω μ)) :
    Semiparametric.dqmTangentSpace (μ := μ) (paths₁ ∪ paths₂) =
      ((Submodule.span ℝ (Semiparametric.dqmScoreSet (μ := μ) paths₁)) ⊔
        (Submodule.span ℝ (Semiparametric.dqmScoreSet (μ := μ) paths₂))).topologicalClosure :=
  Semiparametric.dqmTangentSpace_union_eq (μ := μ) paths₁ paths₂

/-- Concrete pathwise local just identification is exactly the statement that the generated DQM
tangent space is all of `L²₀(P)`. -/
theorem pathwiseLocalJustIdentification_iff_generatedTangent_eq_top
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ)) :
    Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) paths ↔
      Semiparametric.dqmTangentSpace (μ := μ) paths = ⊤ :=
  Semiparametric.isPathwiseLocallyJustIdentified_iff_dqmTangentSpace_eq_top (μ := μ) paths

/-- Generated score directions are dense exactly when the concrete pathwise tangent space fills the
entire centered score space. -/
theorem pathwiseGeneratedScores_dense_iff_tangent_eq_top
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ)) :
    Semiparametric.dqmTangentSpace (μ := μ) paths = ⊤ ↔
      Dense ((Submodule.span ℝ (Semiparametric.dqmScoreSet (μ := μ) paths) :
        Set (Semiparametric.CenteredScoreSpace Ω μ))) :=
  Semiparametric.dqmTangentSpace_eq_top_iff_dense_generatedScores (μ := μ) paths

/-- DQM first-order expansions along admissible local sequences are inherited from the underlying
quadratic-mean differentiability statement. -/
theorem dqmFirstOrderLocalExperimentExpansion_of_tendsto
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ] (p : Semiparametric.DQMPath Ω μ) {τ : ℕ → ℝ}
    (hτ : Filter.Tendsto τ Filter.atTop (nhdsWithin (0 : ℝ) ({0}ᶜ))) :
    Semiparametric.HasFirstOrderLocalExperimentExpansion (μ := μ) p τ :=
  p.hasFirstOrderLocalExperimentExpansion_of_tendsto (μ := μ) hτ

/-- Dominated DQM paths are locally contiguous to the base model along any local-alternative
sequence. -/
theorem dqmLocalAlternatives_contiguous
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ] (p : Semiparametric.DQMPath Ω μ) (τ : ℕ → ℝ) :
    Semiparametric.LocallyContiguous (μ := μ) p τ :=
  p.locallyContiguous (μ := μ) τ

/-- Coordinatewise sample log-likelihood ratios vanish at the base point under the base product
law. -/
theorem sampleLogLikelihoodRatio_vanishesAtBase
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ] [MeasureTheory.IsFiniteMeasure μ]
    (p : Semiparametric.DQMPath Ω μ) (n : ℕ) :
    Semiparametric.sampleLogLikelihoodRatio (μ := μ) p n 0 =ᵐ[Semiparametric.baseSampleMeasure μ n] 0 :=
  Semiparametric.sampleLogLikelihoodRatio_atZero_ae_eq_zero (μ := μ) p n

/-- Witness-backed product log-likelihood identity. -/
theorem sampleLogLikelihoodRatio_ae_eq_true_of_witness
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ] [MeasureTheory.IsFiniteMeasure μ]
    {p : Semiparametric.DQMPath Ω μ} {n : ℕ} {t : ℝ}
    (w : Semiparametric.ProductLogLikelihoodRatioWitness (μ := μ) p n t) :
    Semiparametric.sampleLogLikelihoodRatio (μ := μ) p n t =ᵐ[Semiparametric.baseSampleMeasure μ n]
      w.trueLogLikelihoodRatio :=
  Semiparametric.sampleLogLikelihoodRatio_ae_eq_true (μ := μ) w

/-- Witness-backed quadratic product-LAN expansion. -/
theorem productLAN_ae_eq_quadratic_plus_remainder
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ] [MeasureTheory.IsFiniteMeasure μ]
    {p : Semiparametric.DQMPath Ω μ} {h : ℝ}
    (w : Semiparametric.ProductLANWitness (μ := μ) p h) (n : ℕ) :
    Semiparametric.sampleLogLikelihoodRatio (μ := μ) p n (Semiparametric.localAlternativeScale h n)
      =ᵐ[Semiparametric.baseSampleMeasure μ n]
      fun x =>
        Semiparametric.quadraticLANApproximation (μ := μ) p h n x + w.remainder n x :=
  w.sampleLogLikelihoodRatio_ae_eq_quadratic_plus_remainder n

/-- Dimension-one scalar CLTs upgrade to one-dimensional finite-probe CLTs. -/
theorem scalarCLT_to_finiteProbe_dim1
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ]
    {seq : ℕ → Ω → ℝ} {limit : Ω → ℝ}
    (h : MeasureTheory.TendstoInDistribution seq Filter.atTop limit μ) :
    ProbabilityTheory.FiniteProbeCLT (Ω := Ω) (μ := μ)
      (fun n ω => ProbabilityTheory.scalarToEuclidean1 (seq n ω))
      (fun ω => ProbabilityTheory.scalarToEuclidean1 (limit ω)) :=
  ProbabilityTheory.finiteProbeCLT_of_scalar h

/-- Dimension-one finite-probe CLTs are equivalent to the corresponding scalar convergence
statement. -/
theorem finiteProbeCLT_dim1_iff_scalar
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ]
    {seq : ℕ → Ω → ℝ} {limit : Ω → ℝ} :
    ProbabilityTheory.FiniteProbeCLT (Ω := Ω) (μ := μ)
      (fun n ω => ProbabilityTheory.scalarToEuclidean1 (seq n ω))
      (fun ω => ProbabilityTheory.scalarToEuclidean1 (limit ω)) ↔
      MeasureTheory.TendstoInDistribution seq Filter.atTop limit μ :=
  ProbabilityTheory.finiteProbeCLT_dim1_iff_scalar

/-- Finite-probe drift vanishes for directions orthogonal to the probe span. -/
theorem finiteProbeDrift_eq_zero_of_orthogonal
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ] [MeasureTheory.IsFiniteMeasure μ]
    {d : ℕ} (probes : Semiparametric.FiniteProbeFamily (Ω := Ω) (μ := μ) d)
    {g : Semiparametric.CenteredScoreSpace Ω μ}
    (hg : g ∈ (Semiparametric.finiteProbeSpan (μ := μ) probes)ᗮ) :
    Semiparametric.finiteProbeDrift (μ := μ) probes g = 0 :=
  Semiparametric.finiteProbeDrift_eq_zero_of_mem_orthogonal (μ := μ) probes hg

/-- Witness-backed third-lemma shifted means are exactly the finite-probe drift vector. -/
theorem thirdLemma_shiftedMean_eq_finiteProbeDrift
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ] [MeasureTheory.IsFiniteMeasure μ]
    {d : ℕ} {probes : Semiparametric.FiniteProbeFamily (Ω := Ω) (μ := μ) d}
    {g : Semiparametric.CenteredScoreSpace Ω μ}
    (w : Semiparametric.FiniteProbeThirdLemmaWitness (μ := μ) probes g) :
    w.shiftedMean = Semiparametric.finiteProbeDrift (μ := μ) probes g :=
  w.shiftedMean_eq_finiteProbeDrift

/-- Exact one-sample log-likelihood formula for exponential tilts. -/
theorem exponentialTilt_localLogLikelihoodRatio_eq
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ] [MeasureTheory.IsFiniteMeasure μ]
    (tilt : Semiparametric.ExponentialTiltPath Ω μ) (t : ℝ) :
    MeasureTheory.llr (tilt.path t) μ =ᵐ[μ]
      fun ω =>
        t * tilt.score.toFun ω -
          Real.log (∫ z, Real.exp (t * tilt.score.toFun z) ∂μ) :=
  tilt.localLogLikelihoodRatio_ae_eq (μ := μ) t

/-- Exact finite-sample log-likelihood formula for exponential tilts under the base product law. -/
theorem exponentialTilt_sampleLogLikelihoodRatio_eq
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ] [MeasureTheory.IsFiniteMeasure μ]
    (tilt : Semiparametric.ExponentialTiltPath Ω μ) (n : ℕ) (t : ℝ) :
    Semiparametric.exponentialTiltSampleLogLikelihoodRatio (μ := μ) tilt n t
      =ᵐ[Semiparametric.baseSampleMeasure μ n]
      fun x =>
        t * (∑ i, tilt.score.toFun (x i)) -
          (n : ℝ) * Real.log (∫ z, Real.exp (t * tilt.score.toFun z) ∂μ) :=
  tilt.sampleLogLikelihoodRatio_ae_eq (μ := μ) n t

/-- Exact local-alternative expansion for exponential-tilt sample log-likelihood ratios. -/
theorem exponentialTilt_localAlternativeExpansion
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsProbabilityMeasure μ] [MeasureTheory.IsFiniteMeasure μ]
    (tilt : Semiparametric.ExponentialTiltPath Ω μ) (n : ℕ) (h : ℝ) :
    Semiparametric.exponentialTiltSampleLogLikelihoodRatio (μ := μ) tilt n
        (Semiparametric.localAlternativeScale h n)
      =ᵐ[Semiparametric.baseSampleMeasure μ n]
      fun x =>
        h * Semiparametric.normalizedConcreteScoreSum (μ := μ) tilt.score n x -
          (n : ℝ) *
            Real.log
              (∫ z, Real.exp ((Semiparametric.localAlternativeScale h n) * tilt.score.toFun z) ∂μ) :=
  tilt.sampleLogLikelihoodRatio_localAlternative_ae_eq (μ := μ) n h

/-- Concrete DQM families induce the abstract Gaussian-shift geometry on their tangent space. -/
abbrev dominatedDqmFamily_gaussianShiftExperiment
    (Ω : Type*) [MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
    [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ)) :=
  Semiparametric.dominatedDqmFamily_inducesGaussianShiftExperiment (μ := μ) paths

/-- Orthogonal directions have zero Gaussian-shift coordinates against any basis of the concrete
DQM tangent space. -/
theorem dqmGaussianShift_orthogonalCoordinates_eq_zero
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ))
    {ι : Type*} (basis : Semiparametric.GaussianShiftBasis ι
      (Semiparametric.dqmTangentSpace (μ := μ) paths))
    {g : Semiparametric.CenteredScoreSpace Ω μ}
    (hg : g ∈ (Semiparametric.dqmTangentSpace (μ := μ) paths)ᗮ) :
    (fun i => inner ℝ (((basis i : Semiparametric.dqmTangentSpace (μ := μ) paths) :
      Semiparametric.CenteredScoreSpace Ω μ)) g) = 0 :=
  Semiparametric.dqmTangentSpace_orthogonalCoordinates_eq_zero (μ := μ) paths basis hg

/-- Concrete coordinate decomposition for dominated DQM tangent spaces. -/
theorem dqmGaussianShift_coordinateDecomposition
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ))
    [((Semiparametric.dqmTangentSpace (μ := μ) paths)).HasOrthogonalProjection]
    (g : Semiparametric.CenteredScoreSpace Ω μ) :
    (Semiparametric.dqmTangentSpace (μ := μ) paths).starProjection g +
        (Semiparametric.dqmTangentSpace (μ := μ) paths)ᗮ.starProjection g =
      g :=
  Semiparametric.dqmTangentSpace_coordinateDecomposition (μ := μ) paths g

/-- Concrete scalarized convolution decomposition for dominated DQM tangent spaces. -/
theorem dqmGaussianShift_scalarizedConvolution
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ))
    [((Semiparametric.dqmTangentSpace (μ := μ) paths)).HasOrthogonalProjection]
    (ψ : Semiparametric.CenteredScoreSpace Ω μ) :
    ψ = (Semiparametric.dqmTangentSpace (μ := μ) paths).starProjection ψ +
      (Semiparametric.dqmTangentSpace (μ := μ) paths)ᗮ.starProjection ψ :=
  Semiparametric.dqmTangentSpace_scalarizedConvolution (μ := μ) paths ψ

/-- Paper Lemma 2.1(i): local just identification is equivalent to a trivial orthogonal
complement. -/
theorem localJustIdentification_iff_trivialOrthogonalComplement
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (T : Semiparametric.TangentSpace H) [T.HasOrthogonalProjection] :
    Semiparametric.IsLocallyJustIdentified T ↔ Tᗮ = ⊥ :=
  Semiparametric.isLocallyJustIdentified_iff_orthogonalComplement_eq_bot (T := T)

/-- Paper Lemma 2.1(ii): local overidentification is equivalent to a nontrivial orthogonal
complement. -/
theorem localOveridentification_iff_nontrivialOrthogonalComplement
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (T : Semiparametric.TangentSpace H) [T.HasOrthogonalProjection] :
    Semiparametric.IsLocallyOveridentified T ↔ Tᗮ ≠ ⊥ :=
  Semiparametric.isLocallyOveridentified_iff_orthogonalComplement_ne_bot (T := T)

/-- Paper Lemma 2.1(ii): local overidentification is equivalent to the existence of a nonzero
orthogonal score direction. -/
theorem localOveridentification_iff_exists_nonzeroOrthogonalScore
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (T : Semiparametric.TangentSpace H) [T.HasOrthogonalProjection] :
    Semiparametric.IsLocallyOveridentified T ↔ ∃ h ∈ Tᗮ, h ≠ (0 : H) :=
  Semiparametric.isLocallyOveridentified_iff_exists_nonzero_orthogonal (T := T)

/-- Concrete pathwise local just identification is equivalent to a trivial orthogonal complement
in centered `L²₀(P)`. -/
theorem pathwiseLocalJustIdentification_iff_trivialOrthogonalComplement
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω} [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ))
    [((Semiparametric.dqmTangentSpace (μ := μ) paths)).HasOrthogonalProjection] :
    Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) paths ↔
      (Semiparametric.dqmTangentSpace (μ := μ) paths)ᗮ = ⊥ :=
  Semiparametric.isPathwiseLocallyJustIdentified_iff_orthogonalComplement_eq_bot
    (μ := μ) paths

/-- Concrete pathwise local overidentification is equivalent to a nonzero orthogonal score
direction in centered `L²₀(P)`. -/
theorem pathwiseLocalOveridentification_iff_exists_nonzeroOrthogonalScore
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω} [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ))
    [((Semiparametric.dqmTangentSpace (μ := μ) paths)).HasOrthogonalProjection] :
    Semiparametric.IsPathwiseLocallyOveridentified (μ := μ) paths ↔
      ∃ h ∈ (Semiparametric.dqmTangentSpace (μ := μ) paths)ᗮ,
        h ≠ (0 : Semiparametric.CenteredScoreSpace Ω μ) :=
  Semiparametric.isPathwiseLocallyOveridentified_iff_exists_nonzero_orthogonal
    (μ := μ) paths

/-- Paper Theorem 3.1(i): regular estimators are first-order equivalent under local just
identification. -/
theorem regularEstimators_firstOrderEquivalent
    {H ι : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    {T : Semiparametric.TangentSpace H} {κ : Semiparametric.EfficientInfluenceSystem T ι}
    {ψ φ : ι → H} [T.HasOrthogonalProjection]
    (hJust : Semiparametric.IsLocallyJustIdentified T)
    (hψ : Semiparametric.RegularInfluenceOperator T κ ψ)
    (hφ : Semiparametric.RegularInfluenceOperator T κ φ) :
    ψ = φ :=
  Semiparametric.regularInfluenceOperator_eq_of_locallyJustIdentified hJust hψ hφ

/-- Concrete DQM-path local just identification implies first-order equivalence of regular
influence operators on the centered score space. -/
theorem pathwiseRegularEstimators_firstOrderEquivalent
    {Ω ι : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {paths : Set (Semiparametric.DQMPath Ω μ)}
    {κ : Semiparametric.EfficientInfluenceSystem (Semiparametric.dqmTangentSpace (μ := μ) paths) ι}
    {ψ φ : ι → Semiparametric.CenteredScoreSpace Ω μ}
    [((Semiparametric.dqmTangentSpace (μ := μ) paths)).HasOrthogonalProjection]
    (hJust : Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) paths)
    (hψ : Semiparametric.RegularInfluenceOperator (Semiparametric.dqmTangentSpace (μ := μ) paths) κ ψ)
    (hφ : Semiparametric.RegularInfluenceOperator (Semiparametric.dqmTangentSpace (μ := μ) paths) κ φ) :
    ψ = φ :=
  Semiparametric.regularInfluenceOperator_eq_of_pathwiseLocallyJustIdentified
    (μ := μ) hJust hψ hφ

/-- Paper Lemma 3.3(ii): differences of regular linear estimators live in the orthogonal
complement. -/
theorem regularEstimatorDifference_isOrthogonal
    {H ι : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    {T : Semiparametric.TangentSpace H} {κ : Semiparametric.EfficientInfluenceSystem T ι}
    {ψ φ : ι → H} [T.HasOrthogonalProjection]
    (hψ : Semiparametric.RegularInfluenceOperator T κ ψ)
    (hφ : Semiparametric.RegularInfluenceOperator T κ φ) (i : ι) :
    ψ i - φ i ∈ Tᗮ :=
  Semiparametric.regularInfluenceDifference_mem_orthogonal hψ hφ i

/-- Paper Theorem 3.1(ii): local overidentification permits distinct regular influence
representations. -/
theorem distinctRegularEstimators_exist_underOveridentification
    {H ι : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [Inhabited ι] [DecidableEq ι]
    {T : Semiparametric.TangentSpace H} {κ : Semiparametric.EfficientInfluenceSystem T ι}
    {ψ : ι → H} [T.HasOrthogonalProjection]
    (hOver : Semiparametric.IsLocallyOveridentified T)
    (hψ : Semiparametric.RegularInfluenceOperator T κ ψ) :
    ∃ ψ' : ι → H, Semiparametric.RegularInfluenceOperator T κ ψ' ∧ ψ' ≠ ψ :=
  Semiparametric.exists_distinct_regularInfluenceOperator_of_locallyOveridentified hOver hψ

/-- Paper Lemma 3.2: unrestricted variance decomposes into efficient and orthogonal pieces. -/
theorem varianceDecomposition
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (T : Semiparametric.TangentSpace H) [T.HasOrthogonalProjection] (x : H) :
    Semiparametric.FullVarianceBound x =
      Semiparametric.EfficientVarianceBound T x +
        Semiparametric.FullVarianceBound (Tᗮ.starProjection x) :=
  Semiparametric.fullVariance_eq_efficientVariance_add_orthogonalVariance T x

/-- Paper Theorem 3.2 / Theorem E.1 bridge: equality of full and efficient variance on a dense set
characterizes local just identification. -/
theorem varianceEquality_onDenseSet_iff_localJustIdentification
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (T : Semiparametric.TangentSpace H) [T.HasOrthogonalProjection]
    {D : Set H} (hDense : Dense D) :
    (∀ x ∈ D, Semiparametric.EfficientVarianceBound T x = Semiparametric.FullVarianceBound x) ↔
      Semiparametric.IsLocallyJustIdentified T :=
  Semiparametric.efficientVariance_eq_fullVariance_iff_locallyJustIdentified_of_dense T hDense

/-- Paper Lemma 3.4: maintained-model score decompositions. -/
theorem maintainedModelScoreDecomposition
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (T M : Semiparametric.TangentSpace H) [T.HasOrthogonalProjection] [M.HasOrthogonalProjection]
    (hTleM : T ≤ M) :
    T ⊔ (Tᗮ ⊓ M) = M :=
  Semiparametric.maintainedModelDecomposition (T := T) (M := M) hTleM

/-- Paper Lemma 3.4: the full score decomposes into tangent, orthogonal, and maintained-model
components. -/
theorem fullScoreDecomposition
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (T M : Semiparametric.TangentSpace H) [T.HasOrthogonalProjection] [M.HasOrthogonalProjection]
    (hTleM : T ≤ M) :
    T ⊔ (Tᗮ ⊓ M) ⊔ Mᗮ = ⊤ :=
  Semiparametric.fullScoreDecomposition (T := T) (M := M) hTleM

/-- Paper Equation (25) and incremental-Sargan expansion. -/
theorem incrementalSarganOrthogonalCharacterization
    {H ι : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    {T M : Semiparametric.TangentSpace H} {κ : Semiparametric.EfficientInfluenceSystem T ι}
    {ψ φ : ι → H} [T.HasOrthogonalProjection] [M.HasOrthogonalProjection]
    (hTleM : T ≤ M)
    (hψ : Semiparametric.EfficientInfluenceOperator T κ ψ)
    (hφ : Semiparametric.RegularInfluenceOperator T κ φ)
    (hφM : ∀ i, φ i ∈ M) (i : ι) :
    ψ i - φ i ∈ Tᗮ ⊓ M :=
  Semiparametric.regularDifference_mem_incrementalSargan hTleM hψ hφ hφM i

/-- Paper Theorem B.1: Gaussian-shift coordinates split into tangent and orthogonal drift
components. -/
theorem gaussianShift_coordinateDecomposition
    {H ι : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    {T : Semiparametric.TangentSpace H} [T.HasOrthogonalProjection]
    (g : H) :
    T.starProjection g + Tᗮ.starProjection g = g :=
  Semiparametric.gaussianShiftCoordinateDecomposition T g

/-- Paper Theorem B.1(ii): scalarized convolution decomposition for Gaussian-shift limit
experiments. -/
theorem gaussianShift_scalarizedConvolution
    {H ι : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    {T : Semiparametric.TangentSpace H} [T.HasOrthogonalProjection]
    (ψ : H) :
    ψ = T.starProjection ψ + Tᗮ.starProjection ψ :=
  Semiparametric.scalarizedConvolutionDecomposition T ψ

/-- Paper Theorem A.1 / Lemma A.1: local just identification for cones is equivalent to a trivial
inner dual cone. -/
theorem coneLocalJustIdentification_iff_trivialInnerDual
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (C : Semiparametric.ClosedConvexCone H) :
    Semiparametric.IsLocallyJustIdentifiedCone C ↔ ProperCone.innerDual (C : Set H) = ⊥ :=
  Semiparametric.isLocallyJustIdentifiedCone_iff_innerDual_eq_bot C

/-- Paper Theorem A.2 / Lemma A.2: local overidentification for cones is equivalent to a
nontrivial inner dual cone. -/
theorem coneLocalOveridentification_iff_nontrivialInnerDual
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (C : Semiparametric.ClosedConvexCone H) :
    Semiparametric.IsLocallyOveridentifiedCone C ↔ ProperCone.innerDual (C : Set H) ≠ ⊥ :=
  Semiparametric.isLocallyOveridentifiedCone_iff_innerDual_ne_bot C

/-- Paper Theorem A.3 / Lemma A.2: local overidentification for cones yields a nonzero dual
direction. -/
theorem coneLocalOveridentification_iff_exists_nonzeroInnerDual
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (C : Semiparametric.ClosedConvexCone H) :
    Semiparametric.IsLocallyOveridentifiedCone C ↔
      ∃ h ∈ ProperCone.innerDual (C : Set H), h ≠ (0 : H) :=
  Semiparametric.isLocallyOveridentifiedCone_iff_exists_nonzero_innerDual C

/-- Paper Theorem A.3(i): local just identification rules out nontrivial dual-cone directions. -/
theorem noNontrivialInnerDual_underLocalJustIdentification
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (C : Semiparametric.ClosedConvexCone H)
    (hJust : Semiparametric.IsLocallyJustIdentifiedCone C) :
    ¬ ∃ h ∈ ProperCone.innerDual (C : Set H), h ≠ (0 : H) :=
  Semiparametric.no_nontrivial_innerDual_of_locallyJustIdentifiedCone (C := C) hJust

/-- Equations (7)-(9): linear GMM model. -/
abbrev LinearGMMModel (dρ dγ : Type*) [Fintype dρ] [Fintype dγ]
    [DecidableEq dρ] [DecidableEq dγ] :=
  Econometrics.GMM.LinearModel dρ dγ

/-- Concrete DQM families associated with a linear GMM model. -/
abbrev LinearGMMDQMAssociatedFamily
    (Ω : Type*) [MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
    [MeasureTheory.IsFiniteMeasure μ]
    (dρ dγ : Type*) [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    (model : Econometrics.GMM.LinearModel dρ dγ) :=
  Econometrics.GMM.DQMAssociatedFamily (Ω := Ω) (μ := μ) model

/-- Equation (8): the linear GMM residual-maker. -/
abbrev gmmResidualMaker {dρ dγ : Type*} [Fintype dρ] [Fintype dγ]
    [DecidableEq dρ] [DecidableEq dγ] (model : Econometrics.GMM.LinearModel dρ dγ) :=
  Econometrics.GMM.residualMaker model

/-- Equation (9): the linear GMM orthogonal restriction space. -/
abbrev gmmOrthogonalRestrictionSpace {dρ dγ : Type*} [Fintype dρ] [Fintype dγ]
    [DecidableEq dρ] [DecidableEq dγ] (model : Econometrics.GMM.LinearModel dρ dγ) :=
  Econometrics.GMM.orthogonalRestrictionSpace model

/-- Equations (7)-(9): local just identification in linear GMM is equivalent to a zero
residual-maker. -/
theorem gmmLocalJustIdentification_iff_residualMaker_zero
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    (model : Econometrics.GMM.LinearModel dρ dγ) :
    Econometrics.GMM.IsLocallyJustIdentified model ↔
      Econometrics.GMM.residualMaker model = (0 : Matrix dρ dρ ℝ) :=
  Econometrics.GMM.locallyJustIdentified_iff_residualMaker_eq_zero model

/-- Equation (9): local overidentification in linear GMM is equivalent to the existence of a
nonzero overidentifying restriction direction. -/
theorem gmmLocalOveridentification_iff_exists_nonzeroRestriction
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    (model : Econometrics.GMM.LinearModel dρ dγ) :
    Econometrics.GMM.IsLocallyOveridentified model ↔
      ∃ g ∈ Econometrics.GMM.orthogonalRestrictionSpace model, g ≠ (0 : dρ → ℝ) :=
  Econometrics.GMM.locallyOveridentified_iff_exists_nonzero_restriction model

/-- Paper Equation (25): incremental Sargan statistics are criterion differences. -/
theorem gmmIncrementalSargan_expansion (Jfull Jmaintained : ℝ) :
    Econometrics.GMM.incrementalSarganStatistic Jfull Jmaintained = Jfull - Jmaintained :=
  Econometrics.GMM.incrementalSarganExpansion Jfull Jmaintained

/-- Smoke instance from the paper's GMM discussion: just identification removes the orthogonal
complement. -/
theorem gmmJustIdentified_killsOrthogonalComplement
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    (model : Econometrics.GMM.LinearModel dρ dγ)
    (hZero : Econometrics.GMM.residualMaker model = (0 : Matrix dρ dρ ℝ)) :
    Econometrics.GMM.orthogonalRestrictionSpace model = ⊥ :=
  Econometrics.GMM.justIdentified_kills_orthogonalComplement model hZero

/-- Smoke instance from the paper's GMM discussion: overidentification yields a nontrivial
`J`-direction. -/
theorem gmmOveridentified_yieldsNontrivialJDirection
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    (model : Econometrics.GMM.LinearModel dρ dγ)
    (hOver : Econometrics.GMM.IsLocallyOveridentified model) :
    ∃ g ∈ Econometrics.GMM.orthogonalRestrictionSpace model, g ≠ (0 : dρ → ℝ) :=
  Econometrics.GMM.overidentified_yields_nontrivialJDirection model hOver

/-- Finite-dimensional local moment drift in linear GMM. -/
abbrev gmmLocalMomentDrift {dρ : Type*} [Fintype dρ] [DecidableEq dρ] :=
  Econometrics.GMM.localMomentDrift (dρ := dρ)

/-- Canonical local Hansen-`J` drift in linear GMM. -/
abbrev gmmHansenJLocalDrift {dρ : Type*} [Fintype dρ] [DecidableEq dρ] :=
  Econometrics.GMM.hansenJLocalDrift (dρ := dρ)

/-- Canonical local Hausman drift in linear GMM. -/
abbrev gmmHausmanLocalDrift {dγ : Type*} [Fintype dγ] [DecidableEq dγ] :=
  Econometrics.GMM.hausmanLocalDrift (dγ := dγ)

/-- Canonical local incremental-Sargan drift in linear GMM. -/
abbrev gmmIncrementalSarganLocalDrift {dρ : Type*} [Fintype dρ] [DecidableEq dρ] :=
  Econometrics.GMM.incrementalSarganLocalDrift (dρ := dρ)

/-- Overidentified linear GMM yields a strictly positive local Hansen-`J` drift direction. -/
theorem gmmOveridentified_yieldsPositiveHansenJDrift
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    (model : Econometrics.GMM.LinearModel dρ dγ)
    (hOver : Econometrics.GMM.IsLocallyOveridentified model) :
    ∃ g ∈ Econometrics.GMM.orthogonalRestrictionSpace model,
      0 < Econometrics.GMM.hansenJLocalDrift g :=
  Econometrics.GMM.overidentified_yields_positiveHansenJDrift model hOver

/-- Overidentified linear GMM yields a strictly positive local incremental-Sargan drift
direction. -/
theorem gmmOveridentified_yieldsPositiveIncrementalSarganDrift
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    (model : Econometrics.GMM.LinearModel dρ dγ)
    (hOver : Econometrics.GMM.IsLocallyOveridentified model) :
    ∃ g ∈ Econometrics.GMM.orthogonalRestrictionSpace model,
      0 < Econometrics.GMM.incrementalSarganLocalDrift g :=
  Econometrics.GMM.overidentified_yields_positiveIncrementalSarganDrift model hOver

/-- Linear GMM local just identification transfers to any associated concrete DQM family. -/
theorem gmmPathwiseLocalJustIdentification_iff
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    {model : Econometrics.GMM.LinearModel dρ dγ}
    (family : Econometrics.GMM.DQMAssociatedFamily (Ω := Ω) (μ := μ) model) :
    Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) family.paths ↔
      Econometrics.GMM.IsLocallyJustIdentified model :=
  family.pathwiseLocallyJustIdentified_iff_gmmJustIdentified

/-- Linear GMM local overidentification transfers to any associated concrete DQM family. -/
theorem gmmPathwiseLocalOveridentification_iff
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    {model : Econometrics.GMM.LinearModel dρ dγ}
    (family : Econometrics.GMM.DQMAssociatedFamily (Ω := Ω) (μ := μ) model) :
    Semiparametric.IsPathwiseLocallyOveridentified (μ := μ) family.paths ↔
      Econometrics.GMM.IsLocallyOveridentified model :=
  family.pathwiseLocallyOveridentified_iff_gmmOveridentified

/-- Pathwise local overidentification for an associated linear GMM family yields a strictly
positive local Hansen-`J` drift direction. -/
theorem gmmPathwiseOveridentified_yieldsPositiveHansenJDrift
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    {model : Econometrics.GMM.LinearModel dρ dγ}
    (family : Econometrics.GMM.DQMAssociatedFamily (Ω := Ω) (μ := μ) model)
    (hOver : Semiparametric.IsPathwiseLocallyOveridentified (μ := μ) family.paths) :
    ∃ g ∈ Econometrics.GMM.orthogonalRestrictionSpace model,
      0 < Econometrics.GMM.hansenJLocalDrift g :=
  family.pathwiseOveridentified_yields_positiveHansenJDrift hOver

/-- Pathwise local overidentification for an associated linear GMM family yields a strictly
positive local incremental-Sargan drift direction. -/
theorem gmmPathwiseOveridentified_yieldsPositiveIncrementalSarganDrift
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {dρ dγ : Type*} [Fintype dρ] [Fintype dγ] [DecidableEq dρ] [DecidableEq dγ]
    {model : Econometrics.GMM.LinearModel dρ dγ}
    (family : Econometrics.GMM.DQMAssociatedFamily (Ω := Ω) (μ := μ) model)
    (hOver : Semiparametric.IsPathwiseLocallyOveridentified (μ := μ) family.paths) :
    ∃ g ∈ Econometrics.GMM.orthogonalRestrictionSpace model,
      0 < Econometrics.GMM.incrementalSarganLocalDrift g :=
  family.pathwiseOveridentified_yields_positiveIncrementalSarganDrift hOver

/-- Section 4 linearized conditional moment models. -/
abbrev LinearizedConditionalMomentModel (H W S : Type*)
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    [AddCommGroup S] [Module ℝ S] :=
  Econometrics.ConditionalMoments.LinearizedModel H W S

/-- Concrete DQM families associated with a linearized conditional moment model. -/
abbrev ConditionalMomentDQMAssociatedFamily
    (Ω : Type*) [MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
    [MeasureTheory.IsFiniteMeasure μ]
    (H W S : Type*)
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    [AddCommGroup S] [Module ℝ S]
    (model : Econometrics.ConditionalMoments.LinearizedModel H W S) :=
  Econometrics.ConditionalMoments.DQMAssociatedFamily (Ω := Ω) (μ := μ) model

/-- Theorem 4.1: dense derivative range is equivalent to vanishing orthogonal score space. -/
theorem conditionalMomentOrthogonalScoreSpace_eq_bot_iff_denseRange
    {H W S : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    [AddCommGroup S] [Module ℝ S]
    (model : Econometrics.ConditionalMoments.LinearizedModel H W S) :
    Econometrics.ConditionalMoments.orthogonalScoreSpace model = ⊥ ↔
      Econometrics.ConditionalMoments.HasDenseRange model :=
  Econometrics.ConditionalMoments.orthogonalScoreSpace_eq_bot_iff_denseRange model

/-- Paper Lemma 4.1: dense range is equivalent to a trivial adjoint kernel. -/
theorem conditionalMomentDenseRange_iff_trivialAdjointKernel
    {H W S : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    [AddCommGroup S] [Module ℝ S]
    (model : Econometrics.ConditionalMoments.LinearizedModel H W S) :
    Econometrics.ConditionalMoments.HasDenseRange model ↔
      LinearMap.ker (ContinuousLinearMap.adjoint model.derivative) = ⊥ :=
  Econometrics.ConditionalMoments.denseRange_iff_adjointKer_eq_bot model

/-- Paper Theorem 4.2 / Theorem E.1: full efficiency on a dense set is equivalent to dense
range. -/
theorem conditionalMomentFullEfficiency_onDenseSet_iff_denseRange
    {H W S : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    [AddCommGroup S] [Module ℝ S]
    (model : Econometrics.ConditionalMoments.LinearizedModel H W S)
    {D : Set W} (hDense : Dense D) :
    (∀ w ∈ D,
        Semiparametric.EfficientVarianceBound
            (Econometrics.ConditionalMoments.rangeSpace model).topologicalClosure w =
          Semiparametric.FullVarianceBound w) ↔
      Econometrics.ConditionalMoments.HasDenseRange model :=
  Econometrics.ConditionalMoments.fullEfficiency_on_denseSet_iff_denseRange model hDense

/-- Paper Lemma 4.2 / Lemma F.1-style local overidentification characterization for linearized
conditional moment models. -/
theorem conditionalMomentLocalOveridentification_iff_exists_nonzeroScore
    {H W S : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    [AddCommGroup S] [Module ℝ S]
    (model : Econometrics.ConditionalMoments.LinearizedModel H W S) :
    Econometrics.ConditionalMoments.IsLocallyOveridentified model ↔
      ∃ s ∈ Econometrics.ConditionalMoments.orthogonalScoreSpace model, s ≠ (0 : S) :=
  Econometrics.ConditionalMoments.locallyOveridentified_iff_exists_nonzero_score model

/-- Norm-based local drift statistic for orthogonal-score directions in conditional-moment
models. -/
abbrev conditionalMomentOrthogonalScoreLocalDrift {W : Type*}
    [NormedAddCommGroup W] :=
  Econometrics.ConditionalMoments.orthogonalScoreLocalDrift (W := W)

/-- Dense-range conditional moment models transfer to pathwise local just identification for any
associated DQM family. -/
theorem conditionalMomentPathwiseLocalJustIdentification_iff
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {H W S : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    [AddCommGroup S] [Module ℝ S]
    {model : Econometrics.ConditionalMoments.LinearizedModel H W S}
    (family : Econometrics.ConditionalMoments.DQMAssociatedFamily (Ω := Ω) (μ := μ) model) :
    Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) family.paths ↔
      Econometrics.ConditionalMoments.IsLocallyJustIdentified model :=
  family.pathwiseLocallyJustIdentified_iff_modelJustIdentified

/-- Conditional-moment overidentification transfers to pathwise local overidentification for any
associated DQM family. -/
theorem conditionalMomentPathwiseLocalOveridentification_iff
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {H W S : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    [AddCommGroup S] [Module ℝ S]
    {model : Econometrics.ConditionalMoments.LinearizedModel H W S}
    (family : Econometrics.ConditionalMoments.DQMAssociatedFamily (Ω := Ω) (μ := μ) model) :
    Semiparametric.IsPathwiseLocallyOveridentified (μ := μ) family.paths ↔
      Econometrics.ConditionalMoments.IsLocallyOveridentified model :=
  family.pathwiseLocallyOveridentified_iff_modelOveridentified

/-- Pathwise local overidentification in a conditional-moment model yields a strictly positive
orthogonal-score drift direction. -/
theorem conditionalMomentPathwiseOveridentified_yieldsPositiveScoreDrift
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {H W : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    {model : Econometrics.ConditionalMoments.LinearizedModel H W W}
    (family : Econometrics.ConditionalMoments.DQMAssociatedFamily (Ω := Ω) (μ := μ) model)
    (hOver : Semiparametric.IsPathwiseLocallyOveridentified (μ := μ) family.paths) :
    ∃ s ∈ Econometrics.ConditionalMoments.orthogonalScoreSpace model,
      0 < Econometrics.ConditionalMoments.orthogonalScoreLocalDrift s :=
  family.pathwiseOveridentified_yields_positiveScoreDrift hOver

/-- Paper Corollary 4.1 smoke instance: conditional mean regression is locally just identified. -/
theorem conditionalMeanExample_locallyJustIdentified
    {W : Type*} [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W] :
    Econometrics.ConditionalMoments.IsLocallyJustIdentified
      (Econometrics.ConditionalMoments.identityFirstStageModel (W := W)) :=
  Econometrics.ConditionalMoments.conditionalMean_locallyJustIdentified

/-- Corollary 4.1 in concrete pathwise form for any DQM family associated with the conditional
mean prototype. -/
theorem conditionalMeanExample_pathwiseLocallyJustIdentified
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {W : Type*} [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    (family : Econometrics.ConditionalMoments.DQMAssociatedFamily (Ω := Ω) (μ := μ)
      (Econometrics.ConditionalMoments.identityFirstStageModel (W := W))) :
    Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) family.paths :=
  Econometrics.ConditionalMoments.conditionalMean_pathwiseLocallyJustIdentified family

/-- Constructor-backed associated family for the conditional-mean prototype. -/
abbrev conditionalMeanAssociatedFamily
    (Ω : Type*) [MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
    [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ))
    (hTangent : Semiparametric.dqmTangentSpace (μ := μ) paths = ⊤) :=
  Econometrics.ConditionalMoments.conditionalMeanAssociatedFamily (μ := μ) paths hTangent

/-- Paper Corollary 4.1 smoke instance: quantile-style first stages with nonzero derivative scale
are locally just identified. -/
theorem quantileExample_locallyJustIdentified
    {W : Type*} [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    (c : ℝ) (hc : c ≠ 0) :
    Econometrics.ConditionalMoments.IsLocallyJustIdentified
      (Econometrics.ConditionalMoments.scalarRescaledFirstStageModel (W := W) c) :=
  Econometrics.ConditionalMoments.quantileStyle_locallyJustIdentified c hc

/-- Corollary 4.1 in concrete pathwise form for nonzero scalar first-stage rescalings. -/
theorem quantileExample_pathwiseLocallyJustIdentified
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    {W : Type*} [NormedAddCommGroup W] [InnerProductSpace ℝ W] [CompleteSpace W]
    (c : ℝ) (hc : c ≠ 0)
    (family : Econometrics.ConditionalMoments.DQMAssociatedFamily (Ω := Ω) (μ := μ)
      (Econometrics.ConditionalMoments.scalarRescaledFirstStageModel (W := W) c)) :
    Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) family.paths :=
  Econometrics.ConditionalMoments.quantileStyle_pathwiseLocallyJustIdentified c hc family

/-- Constructor-backed associated family for nonzero scalar-rescaled first stages. -/
abbrev quantileAssociatedFamily
    (Ω : Type*) [MeasurableSpace Ω] (μ : MeasureTheory.Measure Ω)
    [MeasureTheory.IsFiniteMeasure μ]
    (c : ℝ) (hc : c ≠ 0)
    (paths : Set (Semiparametric.DQMPath Ω μ))
    (hTangent : Semiparametric.dqmTangentSpace (μ := μ) paths = ⊤) :=
  Econometrics.ConditionalMoments.scalarRescaledAssociatedFamily (μ := μ) c hc paths hTangent

/-- Conditional-mean prototype in constructor-backed pathwise form, requiring only that the DQM
tangent space be all of `L²₀(P)`. -/
theorem conditionalMeanExample_pathwiseLocallyJustIdentified_of_tangent_eq_top
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    (paths : Set (Semiparametric.DQMPath Ω μ))
    (hTangent : Semiparametric.dqmTangentSpace (μ := μ) paths = ⊤) :
    Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) paths :=
  Econometrics.ConditionalMoments.conditionalMean_pathwiseLocallyJustIdentified_of_tangent_eq_top
    (μ := μ) paths hTangent

/-- Nonzero scalar-rescaled first stages in constructor-backed pathwise form, requiring only that
the DQM tangent space be all of `L²₀(P)`. -/
theorem quantileExample_pathwiseLocallyJustIdentified_of_tangent_eq_top
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    (c : ℝ) (hc : c ≠ 0)
    (paths : Set (Semiparametric.DQMPath Ω μ))
    (hTangent : Semiparametric.dqmTangentSpace (μ := μ) paths = ⊤) :
    Semiparametric.IsPathwiseLocallyJustIdentified (μ := μ) paths :=
  Econometrics.ConditionalMoments.quantileStyle_pathwiseLocallyJustIdentified_of_tangent_eq_top
    (μ := μ) c hc paths hTangent

/-- Paper Examples 4.1-4.3 / Appendix G smoke instance: a partially linear or additive
restriction can generate local overidentification. -/
theorem partiallyLinearExample_locallyOveridentified :
    Econometrics.ConditionalMoments.IsLocallyOveridentified
      Econometrics.ConditionalMoments.coordinateRestrictionModel :=
  Econometrics.ConditionalMoments.partiallyLinearRestriction_locallyOveridentified

/-- Example 4.3 / Appendix G in concrete pathwise form for any DQM family associated with the
partially linear restriction model. -/
theorem partiallyLinearExample_pathwiseLocallyOveridentified
    {Ω : Type*} [MeasurableSpace Ω] {μ : MeasureTheory.Measure Ω}
    [MeasureTheory.IsFiniteMeasure μ]
    (family : Econometrics.ConditionalMoments.DQMAssociatedFamily (Ω := Ω) (μ := μ)
      Econometrics.ConditionalMoments.coordinateRestrictionModel) :
    Semiparametric.IsPathwiseLocallyOveridentified (μ := μ) family.paths :=
  Econometrics.ConditionalMoments.partiallyLinearRestriction_pathwiseLocallyOveridentified family

end OveridentificationRegularModels
end Econometrics
